### ISSUE TITLE
OMR Acceptance failure on Win32

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#10308]
See https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/680/console
```
05:17:35  ./common/omrstr.c(3130) : error C2220: warning treated as error - no 'object' file generated
05:17:35  ./common/omrstr.c(3130) : warning C4018: '<=' : signed/unsigned mismatch
05:17:35  make[5]: *** [../omrmakefiles/rules.mk:372: omrstr.obj] Error 2
```
I believe this is failing because of eclipse/omr#5435.   @keithc-ca

**Comment by keithc-ca** [comment]
Sorry. That should be fixed by omr#5443.
 
----- Original message -----From: Daryl Maier <notifications@github.com>To: eclipse/openj9 <openj9@noreply.github.com>Cc: "Keith W. Campbell" <keithc@ca.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] [eclipse/openj9] OMR Acceptance failure on Win32 (#10308)Date: Fri, Jul 31, 2020 9:28 AM 
 
See https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/680/console
05:17:35  ./common/omrstr.c(3130) : error C2220: warning treated as error - no 'object' file generated05:17:35  ./common/omrstr.c(3130) : warning C4018: '<=' : signed/unsigned mismatch05:17:35  make[5]: *** [../omrmakefiles/rules.mk:372: omrstr.obj] Error 2
I believe this is failing because of eclipse/omr#5435. @keithc-ca
