### ISSUE TITLE
JVM crash when use chinese path (java14)

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse/openj9#10312]
Java -version output
--------------------

openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 14 Windows 7 amd64-64-B
it Compressed References 20200715_148 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 1d231bd6a2 based on jdk-14.0.2+12)

Summary of problem
------------------
Chinese path cause java14 can not launch. Java8 with openj9 and java14 with hotspot can running.

test log:
```
E:\>cd 测试java

E:\测试java>jdk-14.0.2+12\bin\java -version
JVMJ9VM013W 在函数 VMInitStages(7) 中发生初始化错误 cannot initialize modules pa
th
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

E:\测试java>jdk-8.0.265.01-openj9\bin\java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Windows 7 amd64-64-Bit Compres
sed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
```

**Comment by ChengJin01** [comment]
I tried with the latest nightly builds on Java 8, 11, 14 & 15 and the problem still occurred on 11, 14 & 15:
```
c:\JCHAU\测试java>jdk8u272-b09_openj9\bin\java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-202010061755-b09)
Eclipse OpenJ9 VM (build master-cc06e6bc1, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20201006_842 (JIT enabled, AOT enabled)
OpenJ9   - cc06e6bc1
OMR      - d405b96ec
JCL      - 52122fb6 based on jdk8u272-b09)

c:\JCHAU\测试java>jdk_11.0.9_10_openj9\bin\java  -version
JVMJ9VM013W Initialization error in function VMInitStages(7): cannot initialize modules path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

c:\JCHAU\测试java>jdk14.0.2_12_openj9\bin\java  -version
JVMJ9VM013W Initialization error in function VMInitStages(7): cannot initialize modules path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

c:\JCHAU\测试java>jdk15_36_openj9\bin\java  -version
JVMJ9VM013W Initialization error in function VMInitStages(7): cannot initialize modules path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Will further investigate to see what happened to our code.

**Comment by ChengJin01** [comment]
Looking at the printing messages (added to the source) without Chinese & with Chinese in the module path:
[1] without Chinese in the module path
```
C:\JCHAU>jdk11_openj9_win_v2\bin\java -version

initializeClassPathEntry: attr = 1
JIMAGE_Open: name = C:\JCHAU\jdk11_openj9_win_v2\lib\modules

ImageFileReader::open(): find_image: name = C:\JCHAU\jdk11_openj9_win_v2\lib\modules, reader = 0000000000000000
JIMAGE_Open: ImageFileReader::open: jfile = 00000234E37E73F0

initializeClassPathEntry:jimageOpen: jimageFile = 00000234E37E73F0, error = 0

initializeClassPathEntry:jimageOpen: rc = 0
openjdk version "11.0.9-internal" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.jenkins.BuildJDK11x86-64windowsPersonal)
Eclipse OpenJ9 VM (build vm_VMInitStages_init_class_path-23d598486b5, JRE 11 Windows 10 amd64-64-Bit Compressed References 20201008_774 (JIT enabled, AOT enabled)
OpenJ9   - 23d598486b5
OMR      - a2de3ba284f
JCL      - c260bbf3152 based on jdk-11.0.9+10)
```
[2] with Chinese in the module path
```
C:\JCHAU\测试java>jdk11_openj9_win_v2\bin\java  -version
initializeClassPathEntry: attr = 1
JIMAGE_Open: name = C:\JCHAU\娴嬭瘯java\jdk11_openj9_win_v2\lib\modules

ImageFileReader::open(): find_image: name = C:\JCHAU\娴嬭瘯java\jdk11_openj9_win_v2\lib\modules, reader = 0000000000000000
ImageFileReader::open(): reader->open(): Failed to open: return NULL
JIMAGE_Open: ImageFileReader::open: jfile = 0000000000000000

initializeClassPathEntry:jimageOpen: jimageFile = 0000000000000000, error = 0

maplibJImageToJImageIntfError:JIMAGE_NOT_FOUND: return J9JIMAGE_RESOURCE_NOT_FOUND

initializeClassPathEntry:jimageOpen: rc = -21

initializeClassPathEntry:zip_openZipFile: rc = -4
initializeClassPathEntry: attr = -108
initializeModulesPath: CPE_TYPE_UNUSABLE

JVMJ9VM013W Initialization error in function VMInitStages(7): cannot initialize modules path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
It turns out the problem came from `initializeModulesPath()` in dealing with the module path as follows:
```
/runtime/vm/jvminit.c
initializeModulesPath(J9JavaVM *vm) {
...
	memset(vm->modulesPathEntry, 0, sizeof(J9ClassPathEntry));
	modulesPath = (U_8 *)(vm->modulesPathEntry + 1);
	j9str_printf(PORTLIB, (char*)modulesPath, (U_32)modulesPathLen + 1, "%s" DIR_SEPARATOR_STR "lib" DIR_SEPARATOR_STR "modules", javaHome->value);

	vm->modulesPathEntry->path = modulesPath;  <--------
	vm->modulesPathEntry->pathLength = (U_32)modulesPathLen;
	rc = initializeClassPathEntry(vm, vm->modulesPathEntry);
	if (CPE_TYPE_UNUSABLE == rc) {
		vm->modulesPathEntry->type = CPE_TYPE_UNKNOWN;
		/* If <JAVA_HOME>/lib/modules is not usable, try to use <JAVA_HOME>/modules dir */
		modulesPathLen = strlen(javaHome->value) + LITERAL_STRLEN(DIR_SEPARATOR_STR) + LITERAL_STRLEN("modules");
		j9str_printf(PORTLIB, (char*)modulesPath, (U_32)modulesPathLen + 1, "%s" DIR_SEPARATOR_STR "modules", javaHome->value);
		vm->modulesPathEntry->pathLength = (U_32)modulesPathLen;
		rc = initializeClassPathEntry(vm, vm->modulesPathEntry);
		if (CPE_TYPE_UNUSABLE == rc) {  <---------
			printf("\ninitializeModulesPath: CPE_TYPE_UNUSABLE");
			goto _error;
		}
	}
...

initializeClassPathEntry (J9JavaVM * javaVM, J9ClassPathEntry *cpEntry)
{
...
	if ((EsIsFile == attr) && (J2SE_VERSION(javaVM) >= J2SE_V11)) {
		J9JImageIntf *jimageIntf = javaVM->jimageIntf;
		if (NULL != jimageIntf) {
			UDATA jimageHandle = 0;
			I_32 rc = jimageIntf->jimageOpen(jimageIntf, (char *)cpEntry->path, &jimageHandle); <------
			printf("\ninitializeClassPathEntry:jimageOpen: rc = %d\n", (int)rc);
			if (J9JIMAGE_NO_ERROR == rc) {
...
```
So,  It looks like we need to convert the module path containing Chinese to Unicode on Windows to avoid such issue.

**Comment by ChengJin01** [comment]
Further investigation shows the problem was triggered by calling :`:open()` in ` osSupport::openReadOnly` at `/openj9-openjdk-jdk11/src/java.base/windows/native/libjimage/osSupport_windows.cpp`
```
jint osSupport::openReadOnly(const char *path) {
    // jimage file descriptors must not be inherited by child processes
    //return ::open(path, O_BINARY | O_NOINHERIT, O_RDONLY);
	int fd = ::open(path, O_BINARY | O_NOINHERIT, O_RDONLY);  <----- ::open() returns -1
	printf("\nosSupport::openReadOnly: ::open(): path = %s, fd = %d\n", path, fd);
	return fd;
}
```
against the printing messages:
```
initializeClassPathEntry: attr = 1
ImageFileReader::open(): find_image: name = C:\jchau\娴嬭瘯java\jdk11_openj9_win_v7\lib\modules, reader = 0000000000000000
osSupport::openReadOnly: ::open(): path = C:\jchau\娴嬭瘯java\jdk11_openj9_win_v7\lib\modules, fd = -1
ImageFileReader::open: _fd == -1: return false: _name = C:\jchau\娴嬭瘯java\jdk11_openj9_win_v7\lib\modules
ImageFileReader::open(): Failed to open: return NULL: reader = 000001A5B0EFF080
```

Looking at the calling path as follows:
```
initializeModulesPath (/runtime/vm/jvminit.c)
      |
      v
initializeClassPathEntry (/runtime/vm/jvminit.c)
      |
      v
jimageIntf->jimageOpen (/runtime/vm/jvminit.c)
      |
      v
libJImageOpen (/runtime/bcutil/jimageintf.c)
      |
      v
JIMAGE_Open (/openj9-openjdk-jdk11/src/java.base/share/native/libjimage/jimage.cpp) 
      |
      v
ImageFileReader::open (/openj9-openjdk-jdk11/src/java.base/share/native/libjimage/imageFile.cpp)
      |
      v
osSupport::openReadOnly (/openj9-openjdk-jdk11/src/java.base/windows/native/libjimage/osSupport_windows.cpp)
      |
      v
::open() (#include <fcntl.h>)
```
It means OpenJ9 has to call in this way to get the jimage file descriptor, in which case the conversion from UTF8 encoded string to Unicode shouldn't happen in OpenJ9 (it won't help to pass the Unicode string in `wchar_t` to OpenJDK11) but in OpenJDK11 at `osSupport::openReadOnly` on Windows.

Given that `::open()` itself doesn't address the case of UTF8 encoded string, I will try to the following steps to see how it goes:
1) replace `::open()` with `_open` (Windows extension) to see whether it works.
2) if not, convert the UTF8 encoded string to Unicode string (`wchar_t`) with `mbstowcs()` and then call `_wopen()` (Windows extension for `wchar_t`)

**Comment by ChengJin01** [comment]
> The description says `java14 with hotspot can running.`. Does that mean the OpenJDK code already contains a fix that just needs to be backported to jdk11?

I am not too sure about that as there is no code change in osSupport::openReadOnly at `https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/master/src/java.base/windows/native/libjimage/osSupport_windows.cpp`
```
jint osSupport::openReadOnly(const char *path) {
    // jimage file descriptors must not be inherited by child processes
    return ::open(path, O_BINARY | O_NOINHERIT, O_RDONLY);
}
```

I also tried with OpenJDK11/Hotspot from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-10-12-08-13/OpenJDK11U-jdk_x64_windows_hotspot_2020-10-12-08-13.zip which works good:
```
C:\JCHAU\测试java>jdk11.0.9_10_hotspot_win\bin\java  -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment Hotspot (build 11.0.9+10-202010112338)
OpenJDK 64-Bit Server VM Hotspot (build 11.0.9+10-202010112338, mixed mode)
```
So I suspect the implementation of Hotspot is different from ours so it doesn't reply on `osSupport::openReadOnly` to get the jimage file descriptor; otherwise, it should end up with the same failure.

**Comment by pshipton** [comment]
I wonder if it's related to the Windows _MBCS setting. Perhaps Hotspot sets this and passes in appropriate data to open().

**Comment by pshipton** [comment]
Another possibility is that Hotspot opens the file using a relative path.

**Comment by ChengJin01** [comment]
> I wonder if it's related to the Windows _MBCS setting. Perhaps Hotspot sets this and passes in appropriate data to open().

The _MBCS is used for Windows specificAPIs something like xxxA(). I don't think it is accepted by open() according to the description parameter of ::open() (standard API in fcntl.h) according to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=vs-2019

> Another possibility is that Hotspot opens the file using a relative path.

I need to double-check this to see whether it works in this way. If so, then it means we shouldn't reply on an absolute path (which contains UTF8 encoded characters) when passing over to open() in OpenJDK

**Comment by ChengJin01** [comment]
Directly changing `modulesPath` in  `initializeModulesPath` from `C:\JCHAU\娴嬭瘯java\jdk11_openj9_win_v3\lib\modules` to `jdk11_openj9_win_v3\lib\modules` doesn't work because `j9file_attr` is called in initializeClassPathEntry (which is called by `initializeModulesPath`) as follows:
```
initializeModulesPath(J9JavaVM *vm) {
...
	vm->modulesPathEntry->path = modulesPath;
	vm->modulesPathEntry->pathLength = (U_32)modulesPathLen;
	rc = initializeClassPathEntry(vm, vm->modulesPathEntry); <-----

initializeClassPathEntry (J9JavaVM * javaVM, J9ClassPathEntry *cpEntry)
{
...
	/* Start guessing. Is it a directory? */
	attr = j9file_attr((char *)cpEntry->path); <-----
...
	if ((EsIsFile == attr) && (J2SE_VERSION(javaVM) >= J2SE_V11)) {
		J9JImageIntf *jimageIntf = javaVM->jimageIntf;
		if (NULL != jimageIntf) {
			UDATA jimageHandle = 0;
			I_32 rc = jimageIntf->jimageOpen(jimageIntf, (char *)cpEntry->path, &jimageHandle); <-----

omrfile_attr(struct OMRPortLibrary *portLibrary, const char *path)
{
	DWORD result;
	wchar_t unicodeBuffer[UNICODE_BUFFER_SIZE], *unicodePath;

	Trc_PRT_file_attr_Entry(path);

	/* Convert the filename from UTF8 to Unicode */
	unicodePath = port_file_get_unicode_path(portLibrary, path, unicodeBuffer, UNICODE_BUFFER_SIZE);
	if (NULL == unicodePath) {
		return -1;
	}

	result = GetFileAttributesW(unicodePath); <------
```
in which case it calls `GetFileAttributesW` which requires the absolute path to get this work (detected at https://stackoverflow.com/questions/27420831/getfileattributes-function-doesnt-work-with-a-relative-path-to-a-folder).

To avoid changing the code in OMR, I will try to copy out `modulesPathEntry->path` after calling `j9file_attr` and change it to the relative path which is passed into `jimageIntf->jimageOpen` to see whether it helps to bypass the issue.

**Comment by pshipton** [comment]
I was speculating how the existing openjdk code might be able to work with Hotspot. It's probably easier/better to patch the OpenJDK code to work with OpenJ9.

In order for a relative path to work, the current directory also needs to be set properly, which might involve setting it and then restoring it. I'm not sure what the cd is at the point the jimage is opened.

**Comment by ChengJin01** [comment]
> I was speculating how the existing OpenJDK code might be able to work with Hotspot. 

This is something really confused me.
If Hotspot calls `jimageIntf->jimageOpen`, it should end up with the same failure at `::open()` in `osSupport::openReadOnly` as `open()` doesn't handle the case of UTF8 encoded string unless 1) there is no UTF8 encoded characters in the string

A relative path might work with the case of `jdk/lib/modules` in `initializeModulesPath ` but it doesn't guarantee there is no UTF8 string for class path called from other functions, in which case `jimageIntf->jimageOpen` might still end up with the same failure.

> It's probably easier/better to patch the OpenJDK code to work with OpenJ9.

Theoretically yes as I mentioned earlier. The problem in this case is `jimageIntf->jimageOpen` eventually depends on `::open()` in `osSupport::openReadOnly` .  If we intend to replace `::open()` with new code to covert UT8 string to Unicode when open a file, we might need to do something quite similar to the following code in OMR:
/eclipse_omr/port/win32/omrfile.c
```
intptr_t
omrfile_open(struct OMRPortLibrary *portLibrary, const char *path, int32_t flags, int32_t mode)
{
...
	/* Convert the filename from UTF8 to Unicode */
	unicodePath = port_file_get_unicode_path(portLibrary, path, unicodeBuffer, UNICODE_BUFFER_SIZE);
	if (NULL == unicodePath) {
		return -1;
	}
...
	if (flags & EsOpenForInherit) {
		ZeroMemory(&sAttrib, sizeof(sAttrib));
		sAttrib.bInheritHandle = 1;
		sAttrib.nLength = sizeof(sAttrib);
		aHandle = CreateFileW(unicodePath, accessMode, shareMode, &sAttrib, createMode, flagsAndAttributes, NULL);
	} else {
		aHandle = CreateFileW(unicodePath, accessMode, shareMode, NULL, createMode, flagsAndAttributes, NULL);
	}
...
```
The idea is calling `MultiByteToWideChar` or `mbstowcs` at first to convert UTF8 string to Unicode string and then calling _wopen (Windows extension for Unicode string) to get the file descriptor.  As compared to the code changes in OpenJ9 to deal with relative path but more generic & straightforwards, it might be clearer & straightforward to change in this way.

**Comment by ChengJin01** [comment]
> In order for a relative path to work, the current directory also needs to be set properly, which might involve setting it and then restoring it. I'm not sure what the cd is at the point the jimage is opened.

We can determine it by calling `getcwd` (Linux) or `_getcwd` (Windows) to obtain the current directory. I tried a simple code as follows: in `initializeModulesPath` and `initializeClassPathEntry` before calling `jimageIntf->jimageOpen`
```
char cwd[1024];
   if (getcwd(cwd, sizeof(cwd)) != NULL) {
       printf("Current working dir: %s\n", cwd);
   }
```
e.g. On Linux:
```
~/X86_64_OPENJ9/测试java$ jdk11_openj9_linux_v4/bin/java -version

initializeModulesPath: Current working dir: /home/jincheng/X86_64_OPENJ9/测试java
initializeClassPathEntry: Current working dir: /home/jincheng/X86_64_OPENJ9/测试java
```
But the problem with whether the relative path still contains UTF8 string if we change the current directory, which means a relative path might not fundamentally solve the issue. Changing the code on OpenJDK side is still an option to go.

**Comment by pshipton** [comment]
> unless there is no UTF8 encoded character in the passed-in string

If the cwd is the java directory (or similarly the java/bin directory), the relative path for running the JVM will always be `lib\modules`. There is no other jimage or jimage location atm. The jimage utility can open a jimage file with any path but I believe it's all written in java.

> it might be clearer & straightforward to change in this way in the OpenJDK code

I don't like having to set the cwd, but moving the code to open the jimage from initializeClassPathEntry() to initializeModulesPath() seem feasible. I think it's also correct, as I don't believe it's legal to have a jimage file on the classpath, other than the default lib/modules file. It would also speed up opening jar files slightly since it wouldn't try to open them as a jimage first.

**Comment by pshipton** [comment]
We should be able to convert JAVA_HOME to the Windows platform encoding, append "lib\modules", and use that to call jimageOpen().

**Comment by ChengJin01** [comment]
I tried to convert `modulesPath` from UTF8 to the platform encoding with `j9str_convert` in `initializeModulesPath` but ended up failure with `j9file_attr` in `initializeModulesPathEntry` (split from `initializeClassPathEntry` to deal with the case of jimage).
```
	attr = j9file_attr((char *)cpEntry->path);  <------ return -100
	if (EsIsDir == attr) {
		cpEntry->type = CPE_TYPE_DIRECTORY;
		return CPE_TYPE_DIRECTORY;
	}
```
this is because `j9file_attr` will automatically change the passed-in string to Unicode in any cases before getting the file attribute.
Meanwhile, the check of directory on `/modules` is still required in compilation (I tried to remove the check of dir with `j9file_attr` for the module directory at  https://github.com/ChengJin01/openj9/commit/90f2cac5858d5f85f9e3a6d2878e96ee06e484be but ended up with failure in the last stage of compilation)

To cover the two cases (dir & file) for `/modules`,  there are two ways to go:
1) keep the original  `modulesPath` unchanged & introduce a new field called `convertedModulesPath` in `J9ClassPathEntry` to hold the converted string on Windows, in which case `modulesPath` is handled by `j9file_attr` while `convertedModulesPath` is handled by `jimageIntf->jimageOpen` (this should be easier & it minimizes the changes in `initializeModulesPath`)
2) convert the `modulesPath`  after calling `j9file_attr`  in `initializeModulesPathEntry`, in which case we need to do pretty much the same code as in `initializeModulesPath` to construct the string in addition to the code with `j9str_convert`.

Will investigate the two options next week (off this afternoon) to see which option is better to go.

**Comment by pshipton** [comment]
Pls use approach 2.

**Comment by pshipton** [comment]
Modify your initializeModulesPathEntry() helper running on Windows to convert the `cpEntry->path` to platform in order to call jimageOpen(). The string doesn't need to be reconstructed from scratch.

**Comment by ChengJin01** [comment]
I double-checked the code in omrstr_convert() at https://github.com/eclipse/omr/blob/master/port/common/omrstr.c and suspect it won't work when converting from `J9STR_CODE_MUTF8` (modified UTF8) to `J9STR_CODE_WINDEFAULTACP` (still waiting for the result in compilation).

In our case, the passed-in string of `jimageIntf->jimageOpen` is standard UTF8 instead of modified UTF8. 
However, the existing code in `omrstr_convert()` only supports the conversion from a standard UTF8 string to a modified UTF8 string as follows:
```
case J9STR_CODE_UTF8: {
		switch (toCode) {
		case J9STR_CODE_MUTF8: {
			const uint8_t *utf8Cursor = inBuffer;
			uintptr_t utf8Remaining = inBufferSize;
			result = convertUtf8ToMutf8(portLibrary, &utf8Cursor, &utf8Remaining, outBuffer, outBufferSize);
			/*
			 * convertUtf8ToMutf8 is resumable so does not return error if buffer too small.
			 * In this case we should have consumed all the data
			 */
			if (utf8Remaining > 0) {
				result = OMRPORT_ERROR_STRING_BUFFER_TOO_SMALL;
			}
		}
		break;
		default:
			result = OMRPORT_ERROR_STRING_UNSUPPORTED_ENCODING;
			break;
		}
	}
```
which means we have to call  `omrstr_convert()` twice (convert from `J9STR_CODE_UTF8` to  `J9STR_CODE_MUTF8`at first and then convert from `J9STR_CODE_MUTF8` to `J9STR_CODE_WINDEFAULTACP` )  if we need to convert from `J9STR_CODE_UTF8` to `J9STR_CODE_WINDEFAULTACP` to ensure it works in `jimageIntf->jimageOpen`.

**Comment by ChengJin01** [comment]
I updated the code with the conversion from `J9STR_CODE_MUTF8` to `J9STR_CODE_WINDEFAULTACP` at
https://github.com/ChengJin01/openj9/commit/b6b73d6fbbf60f43629d20b8ed4645bb67fcb7c5, which seems working good as expected as follows:
```
C:\JCHAU\测试java>jdk11_openj9_win_fix_v2\bin\java -version

initializeModulesPathEntry: attr = 1

initializeModulesPathEntry: convertedModulesPathLen1_1 = 53

initializeModulesPathEntry: convertedModulesPathLen1_2 = 53

initializeModulesPathEntry: conversionSucceed = TRUE: modulesPath = C:\JCHAU\测试java\jdk11_openj9_win_fix_v2\lib\modules

JIMAGE_Open: name = C:\JCHAU\测试java\jdk11_openj9_win_fix_v2\lib\modules

osSupport::openReadOnly: ::open(): path = C:\JCHAU\测试java\jdk11_openj9_win_fix_v2\lib\modules, fd = 3

ImageFileReader::open: osSupport::openReadOnly(): _name = C:\JCHAU\测试java\jdk11_openj9_win_fix_v2\lib\modules, _fd = 3

ImageFileReader::open: module_data != NULL = 1

JIMAGE_Open: ImageFileReader::open: jfile = 000001B6390F76D0

initializeClassPathEntry:jimageOpen: jimageFile = 000001B6390F76D0, error = 0

initializeModulesPathEntry: rc = 0, modulesPath = C:\JCHAU\测试java\jdk11_openj9_win_fix_v2\lib\modules

initializeModulesPathEntry: return CPE_TYPE_JIMAGE
openjdk version "11.0.9-internal" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.Administrator.openj9-openjdk-jdk11master10082020)
Eclipse OpenJ9 VM (build vm_VMInitStages_init_class_path-5b7b7a29d, JRE 11 Windows 10 amd64-64-Bit Compressed References 20201019_000000 (JIT enabled, AOT enabled)
OpenJ9   - 5b7b7a29d
OMR      - b0a570300
JCL      - cf49ddabb9 based on jdk-11.0.9+10)
```

Will double-check again tomorrow to make sure everything is logically correct & launch personal builds to see whether no issue is introduced with the changes.

**Comment by pshipton** [comment]
I'm sure it would be fine to convert from UTF8 to J9STR_CODE_WINDEFAULTACP. The modified UTF8 is only related to how enbedded null character are encoding, and the file path won't have any embedded null characters.

**Comment by ChengJin01** [comment]
The code at `omrstr_convert` shows it only converts from `J9STR_CODE_UTF8` (fromCode) to `J9STR_CODE_MUTF8` (toCode) as follows:
```
https://github.com/eclipse/omr/blob/master/port/common/omrstr.c
`omrstr_convert`(struct OMRPortLibrary *portLibrary, int32_t fromCode, int32_t toCode,
			  uint8_t *inBuffer, uintptr_t inBufferSize, uint8_t *outBuffer, uintptr_t outBufferSize)
{
	int32_t result = OMRPORT_ERROR_STRING_UNSUPPORTED_ENCODING;

	switch (fromCode) {
	...
	case J9STR_CODE_UTF8: {  <-------
		switch (toCode) {
		case J9STR_CODE_MUTF8: {
			const uint8_t *utf8Cursor = inBuffer;
			uintptr_t utf8Remaining = inBufferSize;
			result = convertUtf8ToMutf8(portLibrary, &utf8Cursor, &utf8Remaining, outBuffer, outBufferSize);
			/*
			 * convertUtf8ToMutf8 is resumable so does not return error if buffer too small.
			 * In this case we should have consumed all the data
			 */
			if (utf8Remaining > 0) {
				result = OMRPORT_ERROR_STRING_BUFFER_TOO_SMALL;
			}
		}
		break;
		default:
			result = OMRPORT_ERROR_STRING_UNSUPPORTED_ENCODING;
			break;
		}
	}
```
So specifying `J9STR_CODE_WINDEFAULTACP` as `toCode` ends up with `OMRPORT_ERROR_STRING_UNSUPPORTED_ENCODING`.

**Comment by pshipton** [comment]
Either way, converting MUTF8 to J9STR_CODE_WINDEFAULTACP is also fine.

**Comment by ChengJin01** [comment]
By checking the jdk created on the personal build (Java 11 & 15):
```
C:\JCHAU\测试java>jdk11_win\bin\java  -version
openjdk version "11.0.9-internal" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.jenkins.BuildJDK11x86-64windowsPersonal)
Eclipse OpenJ9 VM (build vm_VMInitStages_init_class_path-12d067f168c, JRE 11 Windows 10 amd64-64-Bit Compressed References 20201020_790 (JIT enabled, AOT enabled)
OpenJ9   - 12d067f168c
OMR      - b7e8a5d7804
JCL      - 5e617ab0c87 based on jdk-11.0.9+10)

C:\JCHAU\测试java>jdk15_win\bin\java  -version
<error: unable to load C:\JCHAU\埈<error: unable to load C:\JCHAU\埈Exception in thread "main" java/lang/UnsatisfiedLinkError: sun/nio/fs/WindowsNativeDispatcher.initIDs()V
        at sun/nio/fs/WindowsNativeDispatcher.<clinit> (java.base@9/WindowsNativeDispatcher.java:1157)
        at sun/nio/fs/WindowsFileAttributes.get (java.base@9/WindowsFileAttributes.java:307)
        at sun/nio/fs/WindowsFileAttributeViews$Basic.readAttributes (java.base@9/WindowsFileAttributeViews.java:51)
        at sun/nio/fs/WindowsFileAttributeViews$Basic.readAttributes (java.base@9/WindowsFileAttributeViews.java:38)
        at sun/nio/fs/WindowsFileSystemProvider.readAttributes (java.base@9/WindowsFileSystemProvider.java:198)
        at sun/nio/fs/AbstractFileSystemProvider.isRegularFile (java.base@9/AbstractFileSystemProvider.java:137)
        at java/nio/file/Files.isRegularFile (java.base@9/Files.java:2353)
        at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:272)
        at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:331)
        at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:305)
        at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:390)
        at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:119)
        at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:236)
        at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:215)
        at java/lang/Thread.initialize (java.base@9/Thread.java:435)
        at java/lang/Thread.<init> (java.base@9/Thread.java:160)
```
it seems the fix works fine on Java 11 but ends up with exception on Java 15 as above.
Currently the converted module path is  temporarily allocated for open the jimage file (not set in `vm->modulesPathEntry->path`).  Not sure whether we need to directly set the converted module path in there to avoid this issue.

**Comment by pshipton** [comment]
The jdk15 problem isn't related to opening the jimage file. Since it only occurs on jdk15, it might be related to changes recently made by @JasonFengJ9 to load libraries in Java 15+. https://github.com/eclipse/openj9/pull/10653

**Comment by ChengJin01** [comment]
But it appears to the jdk works fine if there is no Chinese on the path:
```
C:\JCHAU>jdk15_win\bin\java  -version
openjdk version "15-internal" 2020-09-15
OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15x86-64windowsPersonal)
Eclipse OpenJ9 VM (build vm_VMInitStages_init_class_path-12d067f168c, JRE 15 Windows 10 amd64-64-Bit Compressed References 20201020_104 (JIT enabled, AOT enabled)
OpenJ9   - 12d067f168c
OMR      - b7e8a5d7804
JCL      - 0757efcf6c1 based on jdk-15+36)
```
