### ISSUE TITLE
Create release notes for V0.8

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9#1052]
** What needs to go in?**
- Release information (VRMF?)
- Overview
- Issues and limitations (Can we add links to working issues in this issue? I believe we need something around DDR/KCA and signal handling for CTRL-C?)

** Where do we publish?**
I'm assuming we want something on the web site or in the user doc (if we can make an IBM contribution ahead of the release). However, there is also a page for release bugs at the Eclipse project site ( https://projects.eclipse.org/projects/technology.openj9/releases/0.8/bugs), but we could just provide a link from there. I guess we also need to link to the release notes from the OpenJ9 branch that gets created?

Thoughts??
@pshipton @DanHeidinga @mstoodle @jonathanwoodford

**Comment by DanHeidinga** [comment]
@SueChaplain Can you expand "VRMF" for the rest of us?  That's one I don't know.

In the release process document https://github.com/eclipse/openj9/blob/master/doc/processes/release_process.md), we state we'll make a Github release (https://help.github.com/articles/creating-releases/).  We can put the release notes into that item.  

By the Eclipse process, they should probably also go into the release document you linked to in the description.

All the content for the release note should be tagged with the `doc:releaseNote` tag.

**Comment by pshipton** [comment]
For preparation and discussion, some preliminary release notes follow.

Java 8: expected compliant 
Java 9: not compliant
Supported platforms: Linux x, z, p (le)
AIX should be working, but untested
Windows has known issues (including #727), also untested

Known issues (some of which may be fixed by the time 0.8 is released): 
#54 - signals are not handled properly, in particular using Ctrl-C or other signals to shutdown the VM does not run the shutdown hooks
#378 - the direct dump reader isn't yet working, which has an impact on diagnosing problems in the VM/GC/JIT (such as #968)
#479 - Java heaps bigger than 57GB (or ~62GB with command line opts) are not supported
No Issue - com.ibm.gpu is not supported
Some functional verification testing is not yet working, which may hide functional problems:
   #238 (#252), #244, #362, #366, #368, #480, #849, #995
No Issue - some IBM authored functional verification testing is not yet contributed to OpenJ9, such as #724
#897 - javadoc does not contain OpenJ9 extensions 
#898 - javadoc contains unsupported extensions 
https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/18 - OpenJ9 builds contain unusable/unsupported executables
https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/17 - OpenJ9 builds contain extra dlls, some unneeded and others used only for test

**Comment by SueChaplain** [comment]
By VRMF I meant the 0.8.0.0 (?) notation. I recall some discussion recently about what this would be, but the Eclipse release page just says 0.8, which is fine.

I did read the release process doc but didn't see any mention of release documentation. Wherever it lives, we can still link to it from all the places people might expect to find it, including the user documentation.

@DanHeidinga - I assigned this to myself assuming we were creating content in the user docs. Still happy to do this work though. Can you suggest where would be a good place to start a *.md for the release that people can review and discuss here?

**Comment by pshipton** [comment]
I was thinking only resolved issues might be tagged with `doc:releaseNote`. Do we want to tag open issues?

**Comment by DanHeidinga** [comment]
> I was thinking only resolved issues might be tagged with doc:releaseNote. Do we want to tag open issues?

My thought was some of the open items need to be called out - ie: lack of DDR support.  Tagging them ensures they're looked as part of the release notes.  I'm open to other suggestions though.

**Comment by DanHeidinga** [comment]
> Can you suggest where would be a good place to start a *.md for the release that people can review and discuss here?

@SueChaplain That's a good question.  Are the release notes expected to be a long lived document?  If so, then maybe creating an *.md file in the repo makes sense.  My initial thought was that we append comments or edit the description of this issue to build up the list and then copy it into the github release when it's complete.

Which approach do you prefer?

**Comment by SueChaplain** [comment]
@DanHeidinga 

I guess they need to be reasonably long lived so that users can tie the version of OpenJ9 in their binary to a list of "behavior changes" / "limitations". Here are a couple of examples I initially looked at:

- Express.js: https://expressjs.com/en/changelog/4x.html
- Node.js: https://nodejs.org/en/blog/release/v6.12.3/

Is this the sort of thing you had in mind too or do you see the OpenJ9 "source only" releases slightly differently? 

I've had a look at the "Creating releases" GitHub user documentation and it is not clear to me where the release notes would actually reside. The doc says that you can link to the release, but what do you link to? Is it just a record of the release in GitHub? Would we be able to target the release notes directly with a URL?

Happy to edit in this issue until we have the content we want to use, wherever we decide to put it. No point creating an .md file if it's temporary.

**Comment by SueChaplain** [comment]
I see. So we could have an  openj9/releasenotes directory that contains a /0.8 subdir and a 0.8.md file. 
We could then create 0.8.1.md until we are ready to release a /0.9

We could still create links directly to the gihub.com/eclipse/openj9/<blob>/releasenotes/0.8/0.8.md for the website, user docs and Eclipse project sites.

I know that the Node release notes are automated via tooling that grabs all the issues together and compiles the list. It then just takes someone to pull out the notable changes at the top. That would be a good goal longer term.

**Comment by pshipton** [comment]
Re the question about VRMF, I found this https://www.ibm.com/developerworks/community/blogs/nfrsblog/entry/decoding_ibm_s_release_terminology_v_r_m_f43?lang=en

Since VRMF appears to be IBM specific terminology, I suggest we avoid it.

**Comment by pshipton** [comment]
The release notes #1052 were merged.
