### ISSUE TITLE
Optional workaround for jextract RAS build id difference when processing core file

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10676]
There was a crash on plinux in the builds last night (https://github.com/eclipse/openj9/issues/10588#issuecomment-697467680), something we've been chasing. I want to jextract the core file and get the system libraries so we can look at it (the crashing machine doesn't have gdb installed). The builds last night don't contain the latest jextract fix https://github.com/eclipse/openj9/pull/10661, when I tried to use a build containing the fix, I got the following error.
```
java.lang.Error: J9RAS.buildID is incorrect (found bca9b0bb00000039, expecting bca9b0bb000003a5). This version of jextract is incompatible with this dump.
	at com.ibm.jvm.j9.dump.extract.Main.getEnvironmentPointer(Native Method)
	at com.ibm.jvm.j9.dump.extract.Main.<init>(Main.java:469)
	at com.ibm.jvm.j9.dump.extract.Main.main(Main.java:342)
Error. Unable to locate executable for core.20200923.055935.1753.0001.dmp
```

I think there is no reason a different buildID can't be used to process the core file and collect the system libraries. Discussing with Keith on slack, he suggested this is advanced behavior, as it could end up collecting the wrong set of shared libraries for the jvm if the original jvm has been replaced at the same location. 

We can still have a workaround to disable the check, in the form of a system properly like `jextract -J-Djextract.disable.J9RAS.buildID.check <core>` to be used by advanced users only. Keith suggested printing a warning is appropriate when using this option, which I agree with.

**Comment by pshipton** [comment]
It's also likely the buildID isn't as unique as we expect, or isn't working for versions after jdk8. I manually created a core file with an older jdk15 (9/18) build, and used newer builds with updated jextract to process it without any errors.

**Comment by pshipton** [comment]
Related to the previous comment, if you want to look at the core and builds I used, they are in /home/jenkins/peter on cent7-ppcle-3.

**Comment by keithc-ca** [comment]
The way the buildID is formed differs in cmake and UMA builds.
* in cmake builds it is `yyyyMMddHHmmss` (see [build_tags.cmake](https://github.com/eclipse/openj9/blob/6fd34cb50272d9a1ff02611c349699b620ae8a4d/runtime/cmake/build_tags.cmake#L25))
* in UMA builds it is derived from the hash code of the build spec id and the build number (the value of the `-buildId` option) (see [BuildInfo.java](https://github.com/eclipse/openj9/blob/master/sourcetools/com.ibm.uma/com/ibm/j9/uma/configuration/freemarker/BuildInfo.java#L52))

If you used local UMA-based builds, I expect that's because you didn't specify the `BUILD_ID` and so it defaulted to zero (see [OpenJ9.gmk](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/OpenJ9.gmk#L32)). That effectively nullifies the check performed by `jextract`.

I suggest we ought to improve the cmake situation so that it not so easy to produce builds for distinct platforms that think they can `jextract` each other's core files.

**Comment by pshipton** [comment]
The original jdk15 build that produced the core is from Adopt. The builds running jextract on the core are the PR builds from the pull requests, first jdk15 and then jdk8. None of these should be cmake builds since only jdk11 uses cmake.

**Comment by keithc-ca** [comment]
The code that checks the buildID is currently only invoked if the basic lookup of the executable name fails and then only for ELF dumps. I propose the buildID check should always occur and on all platforms, given that we will add a way to (knowingly) ignore mismatches.

The buildID generated using cmake should be improved so it is more likely to actually be unique.

**Comment by manqingl** [comment]
@pshipton @keithc-ca : jextract not only gets the native libraries from OS, it also gets the native libraries from java itself.  Will this change messes up the native libraries from Java itself?

**Comment by keithc-ca** [comment]
The proposed change should not affect the set of files collected by `jextract`.
