### ISSUE TITLE
Eliminate vm.heapBaseAddress()

### ISSUE THREAD

**Issue by dchopra001** [eclipse/openj9#11263]
Should we remove this routine as it always returns 0?
https://github.com/eclipse/openj9/blob/8c76311cdcccaa6def680d362df418eca6ae9325/runtime/compiler/env/J9VMEnv.cpp#L65-L69

Note that if we plan to support non-zero based heap in the future, then we cannot remove this routine.

If we do decide to go ahead with this work, we will also have to remove all resulting dead code associated with this routine.

**Comment by dmitripivkine** [comment]
Do I understand correctly this feature supports Compressed Refs heap operations with non-zero heap base (like 0-bit shift heap can be located for example at [4G,8G] with base address 4G)?

**Comment by fjeremic** [comment]
> Do I understand correctly this feature supports Compressed Refs heap operations with non-zero heap base (like 0-bit shift heap can be located for example at [4G,8G] with base address 4G)?

I believe the feature being talked about here predates my time, but it was the shift + offset calculation for compressedrefs that we used to have way back in the day (10 years ago?). Perhaps someone more knowledgable can chime in here. Tagging @0xdaryl and perhaps @vijaysun-omr for some historical context.

Looking back into git history + CMVC this value has been 0 for as long back as I can look.

**Comment by 0xdaryl** [comment]
It has been about 15 years and I don't remember all the history behind this but I do recall that a non-zero heap base was experimented with early on as a possible solution.  At some point we decided that HB 0 was the best implementation but left the logic in place to resurrect it if necessary.

I believe the decision to go with HB0 was driven by performance (or more importantly, it was the approach with the least overhead), in part due to the complexity of the addressing mode.  In addition, I seem to recall one of the challenges with selecting a non-zero HB was what happens to the representation of NULL and the impact that has on the performance of NULLCHKs (implicit or explicit).

I consider this to be technical debt that can be eliminated, unless someone can offer a compelling reason to keep it.

**Comment by dmitripivkine** [comment]
Thank you. At GC side we are considering possibility to investigate using of non zero heap base (better reliability due elimination of possible collisions with loaded DLLs, no need to set special system page size on OSX to simplify building process of Java based tools etc.). However performance impact is unknown.
I guess because this JIT feature has not been used for very long time (and never in production build) it most likely would not work if enabled. I agree this code can be deleted.

**Comment by vijaysun-omr** [comment]
Yes the non zero heap base was superseded by the shift based solution we have in place relatively early on since it provides a much larger heap threshold for when compressed refs can be used than simply a displacement based scheme would have. I agree with Dmitri and Daryl that it can probably be deleted if we wanted to.
