### ISSUE TITLE
OpenJ9/JIT: no responses on a trivial program

### ISSUE THREAD

**Issue by tianxiaogu** [eclipse/openj9#1126]
JIT seems to do crazy optimizations on the following trivial program.
The problem can be reproduced on the nightly build.

`java Test`: no response
`java -Xint Test`: StackOverflowError

<https://github.com/AdoptOpenJDK/openjdk9-openj9-nightly/releases/download/jdk-9%2B181-20180702/OpenJDK9-OPENJ9_x64_Linux_20180702.tar.gz>

```
public class Test {

    static int m() {
        return m();
    }

    public static void main(String[] args) {
        m();
    }
}
```

**Comment by ymanton** [comment]
Why is it a problem? The JIT is allowed to and does tail recursion elimination.

**Comment by fjeremic** [comment]
@tianxiaogu I did a quick test to limit down the JIT optimizations on your test. The reason there is no response when JIT is enabled is because of a tail recursion optionzation that is performed. You can reproduce the issue with the following command-line:

```
bin/java -Xjit:'{Test.m()I}(tracefull,log=m.trace,optlevel=warm,lastoptindex=14)' Test
```

Taking a look at the trace file generated on `optimization id=14` we can see the following transformation performed:

```
<optimization id=14 name=inlining method=Test.m()I>
Performing 14: inlining
[     1]  14.1    O^O INLINER: Eliminating tail recursion to
```

This is effectively [tail recursion](https://en.wikipedia.org/wiki/Tail_call) as pointed out by @ymanton. This is a valid transformation. The transformation is performed here:

https://github.com/eclipse/openj9/blob/4752e61733524e340f4a781adf2a8f16bdd2c4a3/runtime/compiler/trj9/optimizer/InlinerTempForJ9.cpp#L2600-L2832

Hope that helps get a clear picture! Note if you play around with the commandline, and try `lastoptindex=13` you will note inlining optimization will not run and you will get the same result as with running under the interpreter.

**Comment by tianxiaogu** [comment]
Thank you all for pointing out my problem. I really appreciate your explanations.

I reported this issue because the HotSpot VM throws a StackOverflowException instead. Since the behavior depends on the implementation, it is not a problem. Please help me to close the issue. Thanks.
