### ISSUE TITLE
OpenJ9 win32 build failure

### ISSUE THREAD

**Issue by harpreetbamrah** [eclipse/openj9#11519]
The win32 OpenJ9 build fails while using VS 2010. Changing ``BOOLEAN isInline = (1 == (*cursor & 1));`` to two separate instruction lines ``BOOLEAN isInline = FALSE;`` and ``isInline = (1 == (*cursor & 1));`` in openj9\runtime\util\romclasswalk.c fixes the problem. Not sure whether this is related to changes in #11330

**Comment by pshipton** [comment]
VS2010 is no longer supported for building OpenJ9. Note VS2010 is out of support. Since OpenJ9 doesn't test building with VS2010, although there is only a single error now in the future I expect there will be more.

We're behind updating the docs and build instructions. https://github.com/eclipse/openj9/issues/11477 is open to fix the build instructions, and I'll open a PR to fix https://www.eclipse.org/openj9/docs/openj9_support/ shortly.

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9-docs/pull/663
