### ISSUE TITLE
The flag in the InnerClass table affects runtime semantics

### ISSUE THREAD

**Issue by lvitaly** [eclipse/openj9#11538]
Issue details and reproduction steps described in https://github.com/scala/bug/issues/12291

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@fengxue-IS Can you please take a look at this

**Comment by fengxue-IS** [comment]
looking into this

**Comment by fengxue-IS** [comment]
Traced the error to use of class.getModifiers() API during access check. due to historic reasons, getModifiers() searches the innerclass attribute to find modifiers for innerclasses. I have created changeset to use Reflection.getClassAccessFlags which always return the modifiers from the runtime class header.

**Comment by tajila** [comment]
The behaviour of `Class.getModifiers()` is as follows:
```
Returns the Java language modifiers for this class or interface, encoded in an integer. The modifiers consist of the Java Virtual Machine's constants for public, protected, private, final, static, abstract and interface; they should be decoded using the methods of class Modifier.

If the underlying class is an array class, then its public, private and protected modifiers are the same as those of its component type. If this Class object represents a primitive type or void, its public modifier is always true, and its protected and private modifiers are always false. If this Class object represents an array class, a primitive type or void, then its final modifier is always true and its interface modifier is always false. The values of its other modifiers are not determined by this specification. 
```

The key part is "Returns the Java language modifiers ". This implies that for inner classes, member access flags (ie. inner_class_access_flags) must be returned since those represent the language level modifiers for the inner class. This is the current behaviour of `Class.getModifiers()` and it matches the RI.

```
inner_class_access_flags

    The value of the inner_class_access_flags item is a mask of flags used to denote access permissions to and properties of class or interface C as declared in the source code from which this class file was compiled. It is used by a compiler to recover the original information when source code is not available. 
```

In the openj9 method handle code we use `Class.getModifiers()` to retrieve the modifiers for access checks. We have noticed that has caused issues when dealing with inner classes, and this is the cause of the issue here. Also, in the interpreter (non-MH paths) we never use the member access_flags for inner classes we always just use the access_flags on the inner class itself. So there is a difference between how the access checks work in the MH code versus the regular paths with respect to inner classes.

This would imply that all the places where `Class.getModifiers()` is being used for access checks in the MethodHandle code today are errors. And that we should be using `Reflection.getClasssAccessFlags` instead. This would also mean that we need a more performant implementation of `Reflection.getClasssAccessFlags`. `Class.getModifiers()` has a C_INL and fastJNI implementation.

@DanHeidinga @gacholio What are your thoughts on this?

**Comment by gacholio** [comment]
Changing/adding the primitive implementation is trivial.

Does this also imply changing the rules that the VM itself uses when checking access during resolves? Presumably that's already correct or we wouldn't run properly (perhaps we're too permissive?).

**Comment by DanHeidinga** [comment]
> Changing/adding the primitive implementation is trivial.

Agreed.

> Does this also imply changing the rules that the VM itself uses when checking access during resolves? 

I think the VM code is correct.  The MethodHandle access checking has always been tricky code to get right as it has always wanted a mix of the VM and JLS rules

**Comment by gacholio** [comment]
What does `Reflection.getClasssAccessFlags` do now? Native calling a JVM function?

The comment for `lookupNativeAddress` says that JNI implementations win out over INL implementations, which would make accelerating this in the interpreter problematic. The code itself appears to do the opposite - INLs are bound first, which IMO is more sensible behaviour anyway. We'll need to be certain that the JCL native library is checked first as it is the only one allowed to bind INLs.

**Comment by tajila** [comment]
> > Does this also imply changing the rules that the VM itself uses when checking access during resolves?

> I think the VM code is correct. The MethodHandle access checking has always been tricky code to get right as it has always wanted a mix of the VM and JLS rules

Yes the VM code is correct.

> What does Reflection.getClasssAccessFlags do now? Native calling a JVM function?

Pretty much, https://github.com/eclipse/openj9/blob/master/runtime/sunvmi/sunvmi.c#L257

**Comment by gacholio** [comment]
OK, give me the native class/name/signature and I'll put something together.

**Comment by tajila** [comment]
`jint JNICALL Java_jdk_internal_reflect_Reflection_getClassAccessFlags(JNIEnv *env, jclass unused, jclass cls)`

**Comment by tajila** [comment]
The java8 version is `jint JNICALL Java_sun_reflect_Reflection_getClassAccessFlags(JNIEnv *env, jclass unused, jclass cls)`

**Comment by gacholio** [comment]
The jdk internal one is for 11+ ?

**Comment by tajila** [comment]
Yes

**Comment by gacholio** [comment]
Is the native method static?

**Comment by gacholio** [comment]
The native code as it stands is doing a NULL check on the parameter - if the java code is already doing this, we could remove it.

**Comment by gacholio** [comment]
I've got this working - it appears the JIT already does its own inlining for the method so the fast JNI is never called. I'm tempted to remove the implementation.

@tajila @0xdaryl Any reason to include the fast JNI version?

**Comment by tajila** [comment]
> it appears the JIT already does its own inlining for the method so the fast JNI is never called. I'm tempted to remove the implementation.
 
 I see no reason to include the fastJNI version

**Comment by 0xdaryl** [comment]
I think that method will likely be trivially inlined (probably highly likely in fact), but I'm not an expert on the inliner yet to be convinced that it is guaranteed to happen in most common circumstances.

@liqunl : can you offer your opinion on whether the `getClassAccessFlags` will always be inlined (in the normal course of events, as opposed to disabling inlining via a debug option):

https://github.com/eclipse/openj9/blob/6485d7550c994521c5ba78744d5530b78986d9a9/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L2279

**Comment by liqunl** [comment]
Yes, it should always be inlined unless `TR_DisableInliningOfNatives` is set

**Comment by 0xdaryl** [comment]
Thanks @liqunl.  It doesn't seem like the JIT needs the fast version then.  In the rare event inlining is disable we'll just take the slow path out.

**Comment by gacholio** [comment]
https://github.com/eclipse/openj9/pull/11786
