### ISSUE TITLE
Test_openjdk11_j9_extended.functional_ppc64_aix tests not deleting j9core.dmp files

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11674]
The following testcases are not deleting their j9core.dmp file, resulting with an eventual out of disk space after 23Gb is consumed:
```
3.0G	cmdLineTest_J9test_extended_0
3.1G	cmdLineTester_classesdbgddrext_1
3.1G	cmdLineTester_classesdbgddrext_aix_1
3.1G	cmdLineTester_modularityddrtests_1
5.1G	cmdLineTester_shrcdbgddrext_1
2.0G	gcPolicyNogcOOMTest_0
2.0G	testSoftMxLocal_2
2.0G	testSoftMxLocal_LP64k_2
```
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_extended.functional_ppc64_aix/64/console

**Comment by pshipton** [comment]
I believe it's intentional. We could delete the core files as the last step in the cmdLineTest, but I think it's more important to keep them for debugging in case the test fails. We could delete them in the case where the test passes, but not sure how to do that. @llxia is there a way to delete the testcase directory in the playlist.xml if the test passes?

**Comment by andrew-m-leonard** [comment]
@llxia Can each testcase delete the j9core.dmp just at the very end just before Successful completion?

**Comment by andrew-m-leonard** [comment]
@llxia I think the answer is to set KEEP_REPORTDIR to "false" ?

**Comment by llxia** [comment]
yes, TKG will delete the test output if KEEP_REPORTDIR set to `false` and the test passes. In OpenJ9 Jenkins, functional test builds are already set KEEP_REPORTDIR to `false`. This problem is that the AdoptOpenJDK functional test builds set KEEP_REPORTDIR to `true` and this should be changed.

Please note, not all test builds should set to KEEP_REPORTDIR to `false`. For example, openjdk tests need to keep test output dirs as we need to collect junit files at the end.

**Comment by andrew-m-leonard** [comment]
> yes, TKG will delete the test output if KEEP_REPORTDIR set to `false` and the test passes. In OpenJ9 Jenkins, functional test builds are already set KEEP_REPORTDIR to `false`. This problem is that the AdoptOpenJDK functional test builds set KEEP_REPORTDIR to `true` and this should be changed.
> 
> Please note, not all test builds should set to KEEP_REPORTDIR to `false`. For example, openjdk tests need to keep test output dirs as we need to collect junit files at the end.

@llxia thanks Lan, I remember now, that's a really good point about openjdk tests, thanks
