### ISSUE TITLE
JITServer and client should not require write permissions for SSL certificate and key files

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [eclipse/openj9#11702]
When JITServer uses encrypted communication, the server and the client read the SSL certificate and keys from files that they open with write permissions. These files are only read by the JITServer and the JVM, and requiring write permissions for them is not something a user would expect.

**Comment by AlexeyKhrabrov** [comment]
@mpirvu FYI. Ran into this while trying to run a JIT client with encryption in a container.

**Comment by dmitry-ten** [comment]
So the issue is that we read the certificate and key files with `j9jit_fopen_existing`.
https://github.com/eclipse/openj9/blob/38f2941de7e3de78c41b68d712de662ca55f2ac6/runtime/compiler/control/J9Options.cpp#L1069-L1074
which is a function in `jitsupport.cpp`. 
https://github.com/eclipse/openj9/blob/38f2941de7e3de78c41b68d712de662ca55f2ac6/runtime/compiler/env/jitsupport.cpp#L96-L105
So it automatically opens a file for both read and write. 

The easiest way to fix this seems to be to use `j9jit_fopen` instead, pass the correct mode, and make it use `fopen` directly, instead of going through the J9 IO infrastructure, which doesn't seem to have a way to open a file in read-only mode.
