### ISSUE TITLE
Adaptive GC Threading VM Options

### ISSUE THREAD

**Issue by RSalman** [eclipse/openj9#12119]
I had posted in the Eclipse OpenJ9 slack sometime ago to get some thoughts on vm options to tune Adaptive GC Threading _(also referred to as Thread Throttling or Dynamic Threading)_ - _a GC optimization being introduced to adjust the thread count between cycles for better parallelism and overall performance_ (for more background, see https://github.com/eclipse/omr/issues/5829).

Now that we’re moving forward with implementation and have some code to share, I’d like to get thoughts once again regarding the options, specifically:
- Naming/style of options (e.g., XX, Xgc, XXgc etc)
- Behaviour when used with other existing options

Please have a look at  https://github.com/eclipse/openj9/pull/11999 for the options being proposed.

In terms of the desired behaviour with other documented options, we currently have options to **hard set/force the GC thread count** (e.g., `-Xgcthreads` and `-XX:ParallelGCThreads=`). These options are used to manually tune the GC thread count, however Adaptive Threading intends to take care of this and be more effective. There are still cases where the user may want to arbitrary set the thread count, so we should  respect the thread count provided by the user and disable Adaptive Threading when such options are used. However, the user may find it beneficial to have Adaptive Threading enabled along with providing a thread count  _(i.e manual tuning + adaptive threading)_. Also note that adaptive threading will be enabled by default.

With that being said, we have the following:
- We can have another separate option similar to  `-Xgcthreads` but it keeps adaptive threading enabled. A `-Xmaxgcthreads`(or `-Xgc:adaptiveThreadCount`) option, It can be used to set the max thread count _(also acts as initial thread count/starting point)_  for adaptive threading .
- **Force enable Adaptive Threading:** If GC thread count is forced  (`Xgcthreads` )  and user explicitly enables Adaptive Threading `-XX:+AdaptiveThreading` then treat `Xgcthreads` as `Xmaxgcthreads`  
  - **OR, force disable Adaptive Threading**:  completely disable, even if option to enable Adaptive threading is provided )`-XX:+AdaptiveThreading`)  **when** options to hard set/force the GC thread count are used

**Comment by RSalman** [comment]
cc @pshipton @amicic @dmitripivkine @DanHeidinga @keithc-ca @vij-singh

Thoughts and inputs into this are greatly appreciated, thanks!

**Comment by pshipton** [comment]
Using `-XX:` is always preferred, if for no other reason than the VM ignores these options when they are not understood. This means that users can set them in environment variable or scripts, and if running on an older OpenJ9 JVM they are just ignored. The downside is if you misspell the option, it gets ignored with no warning.

**Comment by amicic** [comment]
I'm for introducing a new set of options. To maintain symmetry with 2 existing ones (that set thread count to exact value) they could be:

-Xgcmaxthreads
-XX:MaxParallelGCThreads= (or ParallelGCMaxThreads)

The feature would be enabled by default, but could be disabled (and re-enabled) with -XX:+/-AdaptiveGCThreading (note GC is added to the initial proposal), regardless if maxthreads is explicitly specified or default max threads is used.

As per Peter's suggestions, we would remove  -Xgc:adaptiveThreadCount (it's in current pull request).

**Comment by RSalman** [comment]
cc @vijaysun-omr

I got mixed with names when I initially subscribed everyone :sweat_smile:

**Comment by RSalman** [comment]
>-Xgcmaxthreads
-XX:MaxParallelGCThreads= (or ParallelGCMaxThreads)

Do we intend to have these options independent of Adaptive Threading? That is, if these options are set and adaptive threading is disabled, through command line or because collector doesn't support it, e.g.:
- `-Xgcpolicy:balanced` `-XgcmaxthreadsN`
- `-XX:-AdaptiveGCThreading` `-XgcmaxthreadsN`
- `-Xgc:concurrentScavenge` `-XgcmaxthreadsN`

Would `Xgcmaxthreads` just act a `Xgcthreads`?

It's important to make the distinction because then `gcmaxthreads` must be propagated to `gcThreadCount` in the code. If however `Xgcmaxthreads` is only used for Adaptive threading then it'll simply be ignored (where it's not supported) and default would be used for `gcThreadCount` rather than  `Xgcmaxthreads`. And this also has subtle implications if `XgcmaxthreadsN` sets addaptive threading flag (similar to how `Xgcthreads` sets forced flag), in a case like `-XX:-AdaptiveGCThreading` `-XgcmaxthreadsN` behaviour would be different if `gcmaxthreads` go on to set adaptive threading

**Comment by amicic** [comment]
Before I try to (somewhat indirectly) answer your questions, I'd say that I'm also open to some other approaches, for example, not introducing new -Xmaxthreads option, but just apply adaptive threading to the existing one. That would mean a change in behavior for a large number customers (this option after Xmx/Xmn is the most popular one). I personally think the risk is not high (if we do additionally reduce GC thread count, it's because we believe we can improve GC pause times, and hardly would anyone complain about it), but some does exist (with any new thing, heuristic can go wrong). However, the risk would not different from enabling adaptive threading by default. Still, we would do it only if a couple other people in this discussion explicitly agree it's a preferred way. Benefit of this, of course, is long term - having one option less, hence less documentation and hopefully less confusion what option is used for what scenario.

If we do settle with new -Xmaxthreads options here are my thoughts:

-Xgcmaxthreads would be a variant of -Xgcthreads, but it just allows a collector to adapt/reduce the count beyond the specified argument. If a specific collector does not have adaptive capability, it just stays always at the specified value. So, internally, yes, it does set gcThreadCount.

If -XX:-AdaptiveGCThreading is specified (does not matter in what order relative to 2 variants of threads options) , -Xgcmaxthreads is identical to -Xgcthreads. As usual, if there is a series of AdaptiveGCThreading  option with + or -, last one wins.

If both variants are specified, the latter one wins: if -Xgcmaxthreads is last, adaptive threading is used (and gcThreadCount is set to its argument value), if -Xgcthreads is last, no adaptive threading is used (and again, gcThreadCount is set to its argument value).

If some collector needs some specific value, they will have their specific option, that will win over generic ones. We already have two specific options for Concurrent Scavenger Background thread and Concurrent Mark Background threads (both default to a significantly lower value then -Xgcthreads, but can be overridden through these specific options). We don't support adaptive threading for them yet , but if we ever do, we will then decide if those options behave as 'max' already or we will introduce a new 'max' variant (to be consistent, they might warrant a new variant).

**Comment by amicic** [comment]
Closing... we settled with not changing behavior of existing option -Xgcthreads and not apply adaptive threading to it, and introduce the new one -Xmaxgcthreads that will cap the thread count, but allow adaptive.
