### ISSUE TITLE
Documentation for #1033 permission checking for shared cache utilities

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1268]
https://github.com/eclipse/openj9/pull/1033 added permissions checks which need to be documented.
fyi @SueChaplain 

If a SecurityManager is being used with class data sharing and the running application is calling the com.ibm.oti.shared.SharedClassUtilities APIs getSharedCacheInfo() or destroySharedCache(), you must grant the code calling these APIs the appropriate SharedClassesNamedPermission.

	permission com.ibm.oti.shared.SharedClassesNamedPermission "getSharedCacheInfo";
	permission com.ibm.oti.shared.SharedClassesNamedPermission "destroySharedCache";

**Comment by SueChaplain** [comment]
@pshipton I see from the issue that this is a 9+ doc update. Do you also want this in the 0.8 release notes?

**Comment by pshipton** [comment]
@SueChaplain the change also affects Java 8. I don't think it needs to be in the 0.8 release notes because 0.8 is the first release and its not a change from any previous release.

**Comment by SueChaplain** [comment]
@pshipton 

The following topic in the IBM docs looks to be appropriate for this update, although the title might be changed to reflect considerations when the securitymanager is being used, so that it covers this case as well as class loaders.

https://rtpdoc01.rtp.raleigh.ibm.com:9443/kc/SSYKE2_8.0.0_test/com.ibm.java.vm.80.doc/docs/shrc_permissions.html

We'll also need to plan for content at OpenJ9, once we have contributed the initial lump of documentation, although I think we are going to be relying on remnants of IBM documentation for some time while we grow the content at Eclipse.

**Comment by SueChaplain** [comment]
@pshipton 

I've just found your PR136952 for this change, which suggests the same topic - you can ignore the earlier comment.

**Comment by SueChaplain** [comment]
Supporting documentation at IBM updated (see PR136952). Future documentation at OpenJ9 will include this information.
API documentation update already in place at OpenJ9.
