### ISSUE TITLE
ConstantDynamic: Add support for Gencon (including optthruput + avgpause)

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1279]
Dmitri "Scavenger does not scan CP at the moment. There is no need to because all possible references from CP use to be limited to be intern strings. Such strings are always allocated in Tenure, so they are not involved. With new behavior however scanning of CP should be added to Scavenger. Optthruput and Optavgpause should work "as is" with (if any) changes in CP Iterator"

In addition, we will add a flag to the J9Class classFlags `J9ClassRAMClassContainsNonTenuredObject`. This will be set when a non tenured CondyConstant is loaded.

**Comment by dmitripivkine** [comment]
Scavenger does not scan CP at the moment. There is no need to because all possible references from CP use to be limited to be intern strings. Such strings are always allocated in Tenure, so they are not involved. With new behavior however scanning of CP should be added. Optthruput and Optavgpause should work "as is" with (if any) changes in CP Iterator

**Comment by pshipton** [comment]
@dmitripivkine is there still work to do here?
@DanHeidinga @tajila

**Comment by tajila** [comment]
This can be closed

**Comment by tajila** [comment]
This can be closed

**Comment by dmitripivkine** [comment]
Fixed missed place #2873

**Comment by dmitripivkine** [comment]
I believe it is complete
