### ISSUE TITLE
OpenJ9 Tests compile fail when running with hotspot

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#1314]
With a hotspot `JAVA_BIN` And `JAVA_IMPL=hotspot` I get the following error when running a test:

```
Unrecognized option: -Xcompressedrefs
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by smlambert** [comment]
Please provide the other environment variables you are using also, in particular, what SPEC you are using.

**Comment by llxia** [comment]
We should add check for JAVA_IMPL. -Xcompressedrefs should be added only if JAVA_IMPL=openj9.
@renfeiw , could you take care this issue. Thanks.

**Comment by theresa-m** [comment]
`JAVA_BIN=/team/theresa-m/builds/oracle/jre-9.0.4/jdk-9.0.4/bin`
`JAVA_IMPL=hotspot`
`SPEC=linux_x86-64_cmprssptrs`

**Comment by renfeiw** [comment]
Thanks @llxia , will work on it.

**Comment by smlambert** [comment]
So the 2 part solution to @theresa-m 's problem is:
1) for her to use SPEC=linux_x86-64 
2) for us to add the check for JAVA_IMPL

We have not seen this issue when using testkitgen and running tests at AdoptOpenJDK, is that because the -Xcompressedrefs is being added to the command line of the  "functional" test targets (FV tests) in this case?

**Comment by renfeiw** [comment]
The -Xcompressedrefs is being appended in the extraSettings.mk. We have not seen this issue in AdoptOpenJDK, because the get.sh script will remove extraSettings.mk. I will also delete the remove part after JAVA_IMPL check is aded.

**Comment by smlambert** [comment]
Thanks for the explanation @renfeiw (and the follow-up on the Adopt-side get.sh script !
