### ISSUE TITLE
Print timestamp before and after the execution of each test target.

### ISSUE THREAD

**Issue by renfeiw** [eclipse/openj9#1356]
To help triage test failure, we want to have the ability to track the duration of each test target.

**Comment by smlambert** [comment]
Thanks for raising this @renfeiw - this will also help us to figure out which tests run longer for the execution time anomaly that @AdamBrousseau noticed.

From Adam:

Just looking at the time to do Sanity PRs at eclipse/openj9
zLinux:
  JDK8: (boot JDK openjdk7) Compile: 1h10m Sanity: 27m
  JDK9: (boot jdk IBM8) Compile: 11m Sanity: 1h15m
pLinux:
  JDK8: (boot jdk IBM7) Compile: 19m Sanity: 30m
  JDK9: (boot jdk IBM8) Compile: 13m Sanity: 36m
I know compile on z/8 is slow because of openjdk7, but I'm wondering why sanity on z/9 is so much slower

I looked at the testng test execution times and see no big differences, so suspect that its in the cmdlinetester tests, which adding timestamps will help to shine a light on.
