### ISSUE TITLE
Openj9 build is missing sun/reflect/misc 

### ISSUE THREAD

**Issue by cathyzhyi** [eclipse/openj9#1469]
I made some changes in the java/lang/Class.java file unzipped from src.zip under an openj9 build and javac java/lang/Class.java (from the same openj9 build) gives me the following error:

```'java/lang/Class.java:221: error: package sun.reflect.misc does not exist
      if (sun.reflect.misc.ReflectUtil.needsPackageAccessCheck(callerClassLoader, loader)) {
                          ^
java/lang/Class.java:223: error: package sun.reflect.misc does not exist
            sun.reflect.misc.ReflectUtil.checkProxyPackageAccess(callerClassLoader, this.getInterfaces());
                            ^
java/lang/Class.java:250: error: package sun.reflect.misc does not exist
      if (!(Proxy.isProxyClass(this) && packageName.equals(sun.reflect.misc.ReflectUtil.PROXY_PACKAGE)) &&
                                                                           ^
java/lang/Class.java:251: error: package sun.reflect.misc does not exist
            packageName != null && packageName != "" && sun.reflect.misc.ReflectUtil.needsPackageAccessCheck(callerClassLoader, loader)) 
``` 
The Class.java from src.zip should have been preprocessed for openj9 and should have worked.

**Comment by DanHeidinga** [comment]
Is the `src.zip` from a build you compiled or from an AdoptOpenJDK binary?  If it's an Adopt binary, can you provide a link to the build you used?

**Comment by cathyzhyi** [comment]
It’s not an Adopt binary.  Its an internally built binary.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you take a look at this?

**Comment by JasonFengJ9** [comment]
Sure, looking at it.

**Comment by JasonFengJ9** [comment]
Following command line option can workaround the compilation for `java.base` classes like `Class.java`:
`javac --patch-module java.base=. java/lang/Class.java`.

**Comment by pshipton** [comment]
@cathyzhyi is your build Java 8 or 9?

**Comment by JasonFengJ9** [comment]
For `Java 8`, use command line `javac java/lang/Class.java`.

**Comment by JasonFengJ9** [comment]
@cathyzhyi given the progress at https://github.com/eclipse/openj9/pull/1540, can we assume this issue has been resolved?

**Comment by JasonFengJ9** [comment]
Chatted with Cathy, the problem reported was about `OpenJ9 Java 8`, `IBM Java 8` works fine which I verified.
Will investigate `OpenJ9 Java 8 javac`.

**Comment by JasonFengJ9** [comment]
This behaviour matches RI (similar compilation error presents with RI `Java 8`).
`Java 8 javac` refers `lib/ct.sym` for class compilation. It appears some package/class were excluded from `lib/ct.sym`.
Following script creates `META-INF/sym/rt.jar`:
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/make/CreateJars.gmk#L567 
Following define excludes the package `sun.*`
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/make/common/CORE_PKGS.gmk#L35
IBM internal builds seem refer `rt.jar` directly for `javac compilation` hence it works.

For `OpenJ9 Java 8` (and RI `Java 8`), following command can workaround the the errors reported in this issue:
`javac -bootclasspath ../jre/lib/rt.jar java/lang/Class.java`

I think this issue should be fixed in `OpenJDK Java 8`.

@DanHeidinga @pshipton please comment.

fyi @andrew-m-leonard

**Comment by pshipton** [comment]
I believe you can also use the javac option `-XDignore.symbol.file`. Agreed OpenJ9 isn't doing anything wrong, workarounds have been provided, so I'm closing this.
