### ISSUE TITLE
Create a dockerfile for OpenJDK 10 builds and update v8 & v9 dockerfiles

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9#1497]
/buildenv/docker/* dockerfiles  for Java 8 & 9 pull  OpenJDK builds from Ubuntu as the bootjdk images. These should be replaced with Adopt builds.

We also need a dockerfile for Java 10 which we can link to from the OpenJ9 website build page:
https://www.eclipse.org/openj9/oj9_build.html

**Comment by DanHeidinga** [comment]
@babsingh Can you create the JDK 10 docker file?

The Extensions repo is at https://github.com/ibmruntimes/openj9-openjdk-jdk10 and should have content soon.

**Comment by DanHeidinga** [comment]
For the bootjdk, we should try to use an AdoptOpenJDK JDK9 build.  Adopt has an API that can be used to download specific binaries https://api.adoptopenjdk.net/README

Let's get the 10 dockerfile asap and then look at updating the 8/9 ones

**Comment by babsingh** [comment]
Started dockerfile work for OpenJDK 10 builds here: https://github.com/eclipse/openj9/pull/1514

**Comment by babsingh** [comment]
Started work to update JDK9 (`buildenv/docker/jdk9/*`) Dockerfile(s) here: https://github.com/eclipse/openj9/pull/1541

**Comment by babsingh** [comment]
For JDK 8 DockerFiles, we won't be able to use Adopt builds since AdoptOpenJDK doesn't support OpenJ9 OpenJDK 7 builds.

An exception was made for JDK8 `s390x` DockerFile to use AdoptOpenJDK OpenJ9 OpenJDK 8 build as the boot jdk: https://github.com/eclipse/openj9/issues/1526.

**Comment by babsingh** [comment]
@SueChaplain @DanHeidinga All changes have been delivered. This issue can be closed.

**Update:**
1) OpenJDK 10 DockerFile(s) have been added (#1514; merged).
2) OpenJDK 9 DockerFiles(s) have been updated to use AdoptOpenJDK OpenJ9 JDK8 builds as the boot JDK (#1541; merged).
3) Only OpenJDK 8 `s390` was updated to use AdoptOpenJDK OpenJ9 JDK8 build due to a performance issue (#1545; merged). Other OpenJDK 8 DockerFile(s) need to follow the convention of using `(N -1)` JDK7 builds as the boot JDK. AdoptOpenJDK doesn't support JDK7 builds so we can't use AdoptOpenJDK builds for the remaining OpenJDK 8 DockerFile(s).

**Comment by DanHeidinga** [comment]
Thanks @babsingh 

> We also need a dockerfile for Java 10 which we can link to from the OpenJ9 website build page:
https://www.eclipse.org/openj9/oj9_build.html

Have you opened a PR for the update to the website as well?

**Comment by babsingh** [comment]
created a pull request - https://github.com/eclipse/openj9-website/pull/73

**Comment by babsingh** [comment]
@DanHeidinga all changes are compete for this issue. the eclipse openj9 build page has been updated to show Java 10 instructions: https://www.eclipse.org/openj9/oj9_build.html. so, this issue can be closed.
