### ISSUE TITLE
Class.getDeclaredFields throws exception after invoking Class.newInstance

### ISSUE THREAD

**Issue by felipepontes-research** [eclipse/openj9#1627]
Accordingly to Javadoc of Class.getDeclaredFields, "...an array of Field objects reflecting all the fields declared by the class or interface represented by this Class object" must be returned. But using the following program declared fields of class B can not be retrieved:

```
public class A {
   static {
      String x = null;
      x.getClass();
   }
}

public class B extends A {
   public int x;
}

public class C {
   public static void main(String[] args) throws NoSuchMethodException, NoSuchFieldException {
      try {
         B.class.newInstance();
      } catch (ExceptionInInitializerError e) {
      } catch (Exception e) {
      } finally {
         for (Field f : B.class.getDeclaredFields()) {
            System.out.println(f);
         }
      }
   }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

Steps to reproduce:

	1. Compile above program
	2. Run it using openj9 java

**Current result:**

Exception in thread "main" java.lang.NoClassDefFoundError: samples.newInstance.B (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96)
	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:300)
	at java.lang.Class.getDeclaredFields(Class.java:830)
	at samples.newInstance.C.main(C.java:27)
Caused by: java.lang.NullPointerException
	at samples.newInstance.A.<clinit>(A.java:7)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1773)
	at samples.newInstance.C.main(C.java:11)

**Expected result:**

public int x

**Comment by DanHeidinga** [comment]
The `static` block in A.class attempts to call `getClass()` on `null`.  This will always throw an NPE and should prevent A from being successfully initialized.

Since A wasn't successfully initialized, the `B.class.newInstance();` call should fail with an exception (that's why the rest of the code is in the finally block, right?)

I need to check the code but I believe `getDeclaredFields` forces class initialization before it attempts to find the fields.  Time to check the spec to see what is required when initialization fails.

**Comment by felipepontes-research** [comment]
Accordingly to Section 4.9.2 Structural Constraints of The Java Virtual Machine Specification Java SE 8 Edition "When any instance method is invoked or when any instance variable is accessed,
the class instance that contains the instance method or instance variable must
already be initialized". Wouldn't B.class instance be initialized instead of B instance?

**Comment by JasonFengJ9** [comment]
`B.class.getDeclaredFields()` doesn't require the successful instantiation of class `B`. Actually `for (Field f : B.class.getDeclaredFields())` can be executed and print out `public int x` if it is put before `B.class.newInstance()`.

It appears `J9VMInternals.prepare(this)` within `j.l.Class.getDeclaredFields()` remembers last initialization error caused by `B.class.newInstance()`. 
Probably `ClassInitialization.cpp.prepareClass()` need reset `clazz->initializeStatus` before invoking `classInitStateMachine(currentThread, clazz, J9_CLASS_INIT_PREPARED);`.

RI can still call `B.class.getDeclaredFields()` without exception after `B.class.newInstance()`.

**Comment by DanHeidinga** [comment]
> need reset `clazz->initializeStatus`

We can't change the `initializeStatus` back to a valid state here.  The prepare happens here to ensure that we don't need an `Unsafe.ensureInitialized()` call on every Method/Field access.  I think we're OK to ignore the invalid `initializeStatus` here as we know there will never be an instance.

**Comment by felipepontes-research** [comment]
@DanHeidinga for sure! I will do that.
