### ISSUE TITLE
Windows j9jit29.dll needs MSVCP100.dll (for Java 8) as a prereq

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1632]
For Java 8, the Windows j9jit29.dll has msvcp100.dll as a prerequisite and is the only dll in the OpenJ9 VM with this requirement. Unlike msvcr100, the msvcp100 dll is not included in the OpenJDK / OpenJ9 build packaging. Its needed by the JIT for the following:

```
                         49F ?max@?$numeric_limits@_K@std@@SA_KXZ
                         251 ?_Orphan_all@_Container_base0@std@@QEAAXXZ
                          9A ??1_Container_base12@std@@QEAA@XZ
                         28E ?_Xout_of_range@std@@YAXPEBD@Z
                         28C ?_Xlength_error@std@@YAXPEBD@Z
                         252 ?_Orphan_all@_Container_base12@std@@QEAAXXZ
```

I expect its similar for newer versions of Java, except they need msvcp120.dll, which today is typically already installed on Windows boxes, but this may not be true in the future.

**Comment by sxa555** [comment]
Yep - users at the moment who don't have it can grab https://www.microsoft.com/en-us/download/details.aspx?id=13523 to get hold of it for now. The problem doesn't affect the openjdk10 builds.

**Comment by pshipton** [comment]
I see three choices:

1. Change the JIT to stop using msvcp
1. Patch the build process to include msvcp with OpenJ9 builds
1. Document that users need msvcp100 installed and how to get the redistrubtable package and install it

**Comment by sxa555** [comment]
Since I believe we're already shipping msvcr100 my gut feel would be option 2, unless option 1 is easy to achieve.

**Comment by DanHeidinga** [comment]
@mstoodle Can one of the JIT committers comment on this?

Assuming those are C++ symbols, on linux we statically link the C++ runtime.  Is that something that we should be doing on windows as well?

**Comment by andrewcraik** [comment]
So I've been through that list of symbols from @pshipton using the power of a search engine - they all look to be part of the core C++ library:
- ?max@?$numeric_limits@_K@std@@SA_KXZ: I believe this is std::numeric_limits::max which is fairly fundamental in the STL
- ?_Orphan_all@_Container_base0@std@@QEAAXXZ: looks to be for iterator invalidation for at least deque and vector - with debug off it does nothing and debug on it does iterator validation
- ??1_Container_base12@std@@QEAA@XZ: not quite sure, but this is a base class of std::Container so looks like it is part of the underpinnings of the core STL
- ?_Xout_of_range@std@@YAXPEBD@Z: this is error handling for going past the end of an STL container like vector
- ?_Xlength_error@std@@YAXPEBD@Z: this is error handling for trying to exceed the length of std::string and some container operations
- ?_Orphan_all@_Container_base12@std@@QEAAXXZ: another part of that iterator invalidation logic

Given all of the above it looks like they are part of the core STL and not something the JIT is including directly (there are no references to those symbols directly in the JIT, but I think they are grown from however we are linking the C++ libraries.

The JIT has made the decision to use the STL to simplify its data structures and make the code more accessible. If we are linking in the C++ runtime then this file was missed and we need to link it in as well otherwise things just won't work.

Out of the options listed by @pshipton I don't think 1 is an option. As a result we are left with 2 and 3 as options and if we are allowed to do 2 that would seem to be the cleanest thing to do. If licenses or whatever don't allow it then we need to consider 3.

**Comment by pshipton** [comment]
We can do 2, msvcp is a redistributable file. I expect adding msvcp will become a patch to the extensions repo.

**Comment by andrewcraik** [comment]
Should it be a patch to the extension repo or should it be part of the JIT build process since that is the component that requires it?

**Comment by pshipton** [comment]
I'm not sure the JIT build process can put the file in the correct places in the build structure.

**Comment by andrewcraik** [comment]
ah ok - that is a shame, but your proposal makes sense if that is the case
