### ISSUE TITLE
jdk11 add String.repeat(count)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1660]
http://cr.openjdk.java.net/~iris/se/11/build/latest/diffsFrom10%2b45/java/lang/String.html

**Comment by babsingh** [comment]
fyi - @Ali-Ni

**Comment by Ali-Ni** [comment]
Possible solutions:

1 - Create an empty string, then loop count times, each time using ’+’ to concatenate the original string onto the end. This will create a new string every iteration, and time efficiency of each iteration depends on optimization of ‘+’ concatenation

2 - Apply the same design as 1, using String.concat() instead of ‘+’

3 - create a StringBuffer of the appropriate capacity (count * lengthInternal()) using the StringBuffer (int capacity) constructor, and loop through StringBuffer.append(this) count times, then return StringBuffer.toString()

4 - Apply the same design as 3, using StringBuilder instead of StringBuffer, and using StringBuilder.append() instead of StringBuffer.append(). This MAY be faster than 3, but is not thread-safe (the consequences of which I am not aware of)

5 - Create a byte/char array of the appropriate size (count * lengthInternal()), then in a loop, use the private array copy functions in java.lang.String to sequentially populate this data array with ‘this.value’ count times. (Note that compression must be handled if it is enabled) Then, pass this array into a String constructor and return

In all these implementations, cases where count < 0, count == 0, and count == 1 may be handled in conditional checks, out of necessity (in the case of count < 0 for all these implementations), or as optimizations (in the case of count == 1 for all implementations, ‘return new String(this)’ could avoid extra steps)

**Comment by pshipton** [comment]
1 & 2 will create too many interim objects. Out of 3 & 4, 4 is better as it avoids unnecessary synchronization provided by StringBuffer. Using 4 wouldn't be horrible but does add unnecessary overhead to run the same checks for compression and buffer sizes over and over. Option 5 is the most efficient.

**Comment by pshipton** [comment]
Note you should load https://github.com/eclipse/openj9/pull/1786 and make the changes on top of this.

**Comment by pshipton** [comment]
The spec doesn't say. I wrote a small test to check if repeat(1) returns a new String or just returns this and found it returns this.
```
public class Test {
public static void main(String args[]) {
String str = "abc";
String str2 = str.repeat(1);
System.out.println(str == str2);
}
}
```

**Comment by Ali-Ni** [comment]
When trying to compile with #1786 changes applied, the following error comes up:
```
/jdk11/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/trj9/x/codegen/J9TreeEvaluator.cpp: In static member function 'static TR::Register* J9::X86::TreeEvaluator::VMifArrayCmpEvaluator(TR::Node*, TR::CodeGenerator*)':
/jdk11/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/trj9/x/codegen/J9TreeEvaluator.cpp:4978:4: error: 'SSE2IfArraycmpEvaluator' is not a member of 'TR::TreeEvaluator'
    TR::TreeEvaluator::SSE2IfArraycmpEvaluator(node->getFirstChild(), branchLabel, branchOnEqaul, cg);
```
I'm going to ignore this for now and test my own changes without applying these older commits while waiting for a fix

**Comment by pshipton** [comment]
ok, but note the code will be different when applied on top of #1786

**Comment by babsingh** [comment]
fyi - @tajila
