### ISSUE TITLE
Remove SVT_LoadTest and SVT_Modularity directories

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#206]
Link to Jenkins console output:
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-linux_390-64_cmprssptrs/14/consoleFull

Cause: $(JAVASVT_ROOT) is not set. 

Test Output:
```
01:40:14 ===============================================
01:40:14 Running test SVT_LoadTest.AnnotationsLoadTest_1 ...
01:40:14 ===============================================
01:40:14 test with Mode624
01:40:14 { perl "/javasvt/stf/scripts/stf.pl" -java-args=" -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:optavgpause -Xquickstart -Xjit " -test-root="/javasvt" -javasvt-prereqs="/../javasvt_prereqs" -test=AnnotationsLoadTest -results-root="/AnnotationsLoadTest"; \
01:40:14 if [ $? -eq 0 ] ; then echo "SVT_LoadTest.AnnotationsLoadTest_1""_PASSED"; else echo "SVT_LoadTest.AnnotationsLoadTest_1""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
01:40:14 Can't open perl script "/javasvt/stf/scripts/stf.pl": No such file or directory
01:40:14 SVT_LoadTest.AnnotationsLoadTest_1_FAILED
```

**Comment by smlambert** [comment]
Please exclude these tests for now.  They need to be updated such that the build step will need to clone the stf repo from adoptopenjdk (rather than expect that framework to be available in mounted drive /javasvt).  While this step can be done in the Jenkinsfile, it may not be the right place to do this if we want people to be able to download and run the test suite locally on their laptop.

**Comment by llxia** [comment]
@Mesbah-Alam, could you take care of this issue? Thanks.

**Comment by Mesbah-Alam** [comment]
@llxia We need to clone stf and openjdk-systemtest from github and compile them as part of the build and test compilation of this Jenkins job. Then we'd have to update the playlist.xml of the system tests with the correct path to stf.pl etc svt artifacts so that the tests run off of the latest svt test materials and not point to an obsolete location.

**Comment by smlambert** [comment]
Changing the title of this to remove these directories.  When we integrate SV testing into PR builds, we will approach it differently than this previous solution that we were using for internal testing.

While this is a prio:low item, the 'fix' is straight-forward, remove the dirs.
