### ISSUE TITLE
omr acceptance Build-JDK10-win_x86-64_cmprssptrs failing to clone

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2107]
https://ci.eclipse.org/openj9/job/Build-JDK10-win_x86-64_cmprssptrs/102/console
https://ci.eclipse.org/openj9/job/Build-JDK10-win_x86-64_cmprssptrs/103/console
https://ci.eclipse.org/openj9/job/Build-JDK8-win_x86-64_cmprssptrs/70/console

```
18:57:59 Cloning repository https://github.com/ibmruntimes/openj9-openjdk-jdk10.git
18:57:59  > git init C:\Users\jenkins\workspace\Build-JDK10-win_x86-64_cmprssptrs # timeout=10
18:57:59 ERROR: Error cloning remote repo 'origin'
18:57:59 hudson.plugins.git.GitException: Could not init C:\Users\jenkins\workspace\Build-JDK10-win_x86-64_cmprssptrs
```

**Comment by pshipton** [comment]
@jdekonin fyi

**Comment by AdamBrousseau** [comment]
No space left on device

**Comment by AdamBrousseau** [comment]
Cleaned up. I had accidentally left the nightly cleanup job disabled.

We need to figure out a fix for the windows cleanWs() issue. The issue is that `cleanWs()` renames the workspace directory (appends a random number), then does an asynchronous delete. The directory never gets cleaned up though. We talked about changing the `cleanWs()` to a `rm -rf` but I'm not sure if that will work. I don't think you can rm the workspace of the current job. We could try `deleteDir()` The nightly job that cleans up runs in the parent of the workspace directory and does `ls | grep -v ${JOB_NAME} | xargs rm -rf`. I believe I added the grep becasue you can't rm the cleanup of the current job. Perhaps we need to dig into the cleanWs plugin more.

**Comment by pshipton** [comment]
I assume the cleanWs() problems will be a separate issue. Closing this one since the immediate problem is resolved.
