### ISSUE TITLE
Timeout for omr acceptance not long enough

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2301]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/574/ was one platform away, within an hour of promoting, but then got timed out. I'm suggesting increasing the timeout to 10 hours from 8 hours.

**Comment by AdamBrousseau** [comment]
Usually it is enough.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/buildTimeTrend
It failed last 2 because we were down 3/4 zLinux machines.
I don't mind increasing it if you still want to.


 Build   | Duration |
 -- | -- | 
 `#576` | 2 hr 16 min and counting |  
 `#575` | 8 hr 0 min |  
 `#574` | 8 hr 0 min |  
 `#573` | 5 hr 53 min |  
 `#572` | 5 hr 26 min |  
 `#571` | 5 hr 16 min |  
 `#570` | 4 hr 49 min |  
 `#569` | 3 hr 50 min |  
 `#568` | 4 hr 56 min |  
 `#567` | 5 hr 40 min |  
 `#566` | 5 hr 14 min |  
 `#565` | 4 hr 54 min |  
 `#564` | 4 hr 7 min |  
 `#563` | 2 hr 53 min |  
 `#562` | 3 hr 1 min |  
 `#561` | 2 hr 31 min |  
 `#560` | 2 hr 43 min |  
 `#559` | 2 hr 47 min |  
 `#558` | 2 hr 37 min |  
 `#557` | 2 hr 13 min |  
 `#556` | 2 hr 27 min

**Comment by pshipton** [comment]
zLinux wasn't the only build lagging last night, there was a Windows build that finished just under the wire. I'm not sure if there is drawback to increasing the time. If things go horribly wrong does it matter if they run for 10 hours instead of 8? I'll go ahead and merge #2304 to make it less likely to lose a build because of timeout.
