### ISSUE TITLE
Jenkins Blue Ocean view shows green although builds are failing

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2352]
Looking at a recent OMR acceptance build [1], some of the pipeline builds are failing. Looking at the Blue Ocean view [2], all the builds are showing as green.

[1] https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/591/console
[2] https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-OMR-Acceptance/detail/Pipeline-OMR-Acceptance/591/pipeline

@jdekonin @AdamBrousseau fyi

**Comment by AdamBrousseau** [comment]
I don't think this would be our bug, but it may have been exposed by the way we run our pipelines. There are a number of plugin updates we can apply as a first step to see if the problem resolves. Jenkins is asking for a restart after plugin upgrades so I'll wait till off hours to to that.

**Comment by AdamBrousseau** [comment]
Is this still an issue?
I thought this may have been caused by https://github.com/eclipse/openj9/commit/43a69e33e979a23638b25f99099f19b2431145b5#diff-20461a6c80089cdd81dc68619d2c1a0f
which was resolved by https://github.com/eclipse/openj9/commit/005017e39f0020634cec39dff336e0f0f91fb24e#diff-20461a6c80089cdd81dc68619d2c1a0f
But that was delivered after this issue was created.

**Comment by pshipton** [comment]
Not sure, I've been on vacation for a while so I haven't been looking at builds.

**Comment by jdekonin** [comment]
I believe this is working as expected.  Looking at 804 there is a spec failure and the entire job is red/failed as expected.  I think this can be closed.

**Comment by pshipton** [comment]
Closing. I haven't seen the problem in a while.
