### ISSUE TITLE
threadMXBeanTestSuite2_1 hangs

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2643]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_x86-64/48/console:

```
01:11:17 ===============================================
01:11:17 Running test threadMXBeanTestSuite2_1 ...
01:11:17 ===============================================
01:11:17 threadMXBeanTestSuite2_1 Start Time: Fri Aug 17 05:11:17 2018 Epoch Time (ms): 1534482677791
01:11:17 test with Mode301
01:11:17 { "/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdkbinary/j2sdk-image/bin/java"  -Xnocompressedrefs -Xgcpolicy:metronome -Xnocompressedrefs \
01:11:17 -cp "/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
01:11:17 org.testng.TestNG -d "/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15344816822623/threadMXBeanTestSuite2_1" "/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" \
01:11:17 -testnames \
01:11:17 threadMXBeanTestSuite2 \
01:11:17 -groups level.extended \
01:11:17 -excludegroups d.*.linux_x86-64,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
01:11:17 if [ $? -eq 0 ] ; then echo ""; echo "threadMXBeanTestSuite2_1""_PASSED"; echo ""; else echo ""; echo "threadMXBeanTestSuite2_1""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15344816822623/TestTargetResult";
01:11:18 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test-extended.functional-JDK10-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE100.txt
01:11:18 ...
01:11:18 ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
01:11:18 ...
01:11:18 
01:12:19 ............................................................
01:12:32 
01:12:32  Sleeping for 10s 
01:12:43 ..........
Cancelling nested steps due to timeout
08:43:51 ................Sending interrupt signal to process
08:43:53 make[2]: *** wait: No child processes.  Stop.
08:43:53 make[2]: *** Waiting for unfinished jobs....
08:43:53 make[2]: *** wait: No child processes.  Stop.
```

Looks like a regression as of https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_x86-64/45/console Tue Aug 14.
Changes listed for https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/182/

- Test Cases for Modularity DDR Commands (detail / githubweb)
- Use vector size method in z codegen caseConversionHelper (detail / githubweb)
- FV tests for Skipping parameter access check for reflect objects (detail / githubweb)
- Add support for vendor tests to Jenkins pipelines (detail / githubweb)
- Provide alternative API to J9::CodeCache::initialize() (detail / githubweb)
- Fixup module-info.java.extra files (detail / githubweb)
- Add access check to invokespecialsplit (detail / githubweb)
- Fix X86 32-bit opcode bug in wrtbar optimization (detail / githubweb)
- Optimized Unsafe getAndAdd and getAndSet on X86 (detail / githubweb)
- Revert "Fixup module-info.java.extra files" (detail / githubweb)
- Revert "Build JNI IFA switching helpers as C calls" (detail / githubweb)
- Don't require full syntax for module-info.java.extra files (detail / githubweb)
- Fixup module-info.java.extra files (detail / githubweb)
- Revert "Provide alternative API to J9::CodeCache::initialize()" (detail / githubweb)

**Comment by babsingh** [comment]
Referring to https://github.com/eclipse/openj9/pull/2658, `threadMXBeanTestSuite2_2` also hangs. The hang is intermittent, and it seems to be an exclusive VM access issue. More details for hang are available [here](https://github.com/eclipse/openj9/pull/2658#issuecomment-414474905).

@DanHeidinga does the `threadMXBeanTestSuite*` failures block the Eclipse CI builds? do we need to disable `threadMXBeanTestSuite*` tests?

**Comment by DanHeidinga** [comment]
It's an intermittent failure so definitely a candidate for exclusion.  The only time it will block anything is if it fails in a PR build where committer will have to either rerun the build or recognize this as a known issue.

**Comment by gacholio** [comment]
I know what the problem is.

Each thread handing off (the hander) expects not to have the "not counted" bit set, so that the thread will eventually report in and allow the thread which was handed off to (the handee) to obtain exclusive and proceed. In normal exclusive, this is guaranteed by the fact that the thread which first acquires exclusive never sets "not counted" on itself, and when handoff from normal exclusive occurs, the handee has "not counted" cleared before it is resumed.

In the metronome case (and anyone else using releaseExclusiveVMAccessFromExternalThread), the handee does not get "not counted" clear before resumption.

What actually happens is metronome acquires exclusive and eventually releases it, handing off to handee1 (without clearing "not counted"). handee1 runs successfully, eventually handing off to handee2 (clearing "not counted" on handee2). handee1 runs until releasing VM access, but does not decrement the response count (since "not counted" is still set). handee2 waits forever for the response count to become 0.

I'll decide which of the solutions is best:

- Remove "not counted" from the handee when handing off from external (what I'm currently testing)
- Remove "not counted" from the hander when handing off in the normal case
- Both

**Comment by gacholio** [comment]
The reason this is so intermittent is that it requires a very precise set of circumstances.

When exclusive begins, all threads are hammered with "halt for exclusive" and "not counted". Any thread which checks in before the exclusive acquirer starts counting will end up with the "not counted" bit still being set, since releaseVMAccess does not clear it.

This would be the case if multiple threads want exclusive - the first one hammers the threads, subsequent ones queue themselves and release VM access, resulting in threads which want exclusive but have the "not counted" bit set.

I'll update the comment above with more possibilities for clearing "not counted".

**Comment by gacholio** [comment]
Please unexclude any tests.
