### ISSUE TITLE
Option to not pass `disable-warnings-as-errors` to OpenJ9 & OMR

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#2748]
UB16/18 PPCLE compiles are fine with gcc 7.3, but fail on on redhat7 with gcc 7.3.  As an example...
```
14:27:17 /home/j9build/workspace/vs_Build/src/java.base/unix/native/libjava/TimeZone_md.c: In function ‘findZoneinfoFile’:
14:27:17 /home/j9build/workspace/vs_Build/src/java.base/unix/native/libjava/TimeZone_md.c:150:5: error: ‘readdir64_r’ is deprecated [-Werror=deprecated-declarations]
14:27:17      while (readdir64_r(dirp, entry, &dp) == 0 && dp != NULL) {
14:27:17      ^~~~~
14:27:17 In file included from /home/j9build/workspace/vs_Build/src/java.base/unix/native/libjava/TimeZone_md.c:36:0:
14:27:17 /opt/at11.0/include/dirent.h:201:12: note: declared here
14:27:17  extern int readdir64_r (DIR *__restrict __dirp,
14:27:17             ^~~~~~~~~~~
14:27:17 cc1: all warnings being treated as errors
```

Running with `--disable-warnings-as-errors` at time of configure works around this issue, but that disables warning for OpenJ9, OMR and Openjdk sources, which I don't believe is ideal.

It would be nice to have the option to disable for openjdk (existing option), but also not force that down to OpenJ9 and OMR as is the current situation.

fyi @keithc-ca

**Comment by keithc-ca** [comment]
My plan is to introduce two new configure options:
```
  --(disable|enable)-warnings-as-errors-omr
  --(disable|enable)-warnings-as-errors-openj9
```
When either option is absent (neither explicitly enabled nor disabled) it will default to the current behavior of tracking `--(disable|enable)-warnings-as-errors`.

Where openjdk requires use of `--disable-warnings-as-errors` we will be able to add `--enable-warnings-as-errors-omr` and `--enable-warnings-as-errors-openj9` to avoid relaxing expectations that OMR and OpenJ9 code be warning-free.

**Comment by pshipton** [comment]
Having -(disable|enable)-warnings-as-errors affect all 3 components seems too complicated. It would be much simpler only have --(disable|enable)-warnings-as-errors affect openjdk and have -omr and -openj9 affect the corresponding component. 

Instead of having to use 
`-disable-warnings-as-errors --enable-warnings-as-errors-omr --enable-warnings-as-errors-openj9`
only `-disable-warnings-as-errors` would be required. 

This also means users would have to be specific about disabling warnings-as-errors for omr/openj9 and wouldn't disable them as a side affect. I'd hope the omr/openj9 projects would be responsive to fixing any warnings so disabling warnings-as-errors should not typically be necessary.

**Comment by keithc-ca** [comment]
I was trying not to change the behavior of existing configure options, but, I agree it's more complicated that way. I'm updating my branch to make the new options independent of `--disable-warnings-as-errors` so they'll all be independent.

**Comment by pshipton** [comment]
@keithc-ca Did you warn AdoptOpenJDK of these pending changes?

**Comment by pshipton** [comment]
fyi @jdekonin @sxa555

**Comment by keithc-ca** [comment]
No, I hadn't warned them. I don't expect the change to the meaning of `--disable-warnings-as-errors` to cause any problems because OMR and OpenJ9 compile without warning up to gcc 8.

In fact, I'm not sure that that option should be applied universally:
https://github.com/keithc-ca/openjdk-build/blob/213e1dfc07dbf9f18aafc720edd405a7886c3f9b/makejdk-any-platform.sh#L75
