### ISSUE TITLE
Performance questions for low-latency app

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2782]
akrus wrote on the openj9-dev mailing list.

I think I collected enough test results for now, so I'd like to share them here and ask for any ideas/suggestions.
- with almost default settings, I saw the app being 'paused' for ~20 msec on almost every GC
- with hugepages enabled it improved a bit, but still about 90% of 'pauses' were seen during GC
- with isolcpus/CPUAffinity configured on Java process, this improved dramatically, although still these 20 msec spikes appear from time to time (depending on the load) - with the difference that only some threads are affects, not the whole app

I tried changing regionSize to 262144 and enabling -Xtune:virtualized, but cannot see any changes actually. 

here is the latest one [gc log]:
[jvm_20180904.log](https://github.com/eclipse/openj9/files/2357108/jvm_20180904.log)

Example times when app logged 'pauses' (and GC logged activity):
2018-09-06 00:14:55.030 - 17 ms
2018-09-06 01:06:55.027 - 17 ms
2018-09-06 03:36:25.033 - 16 ms
2018-09-06 05:41:20.016 - 17 ms

**Comment by pshipton** [comment]
@amicic @dmitripivkine

**Comment by amicic** [comment]
Extracting logs for GC activity for all 4 points. Note that the second one shows no GC activity.

```
2018-09-06 00:14:55.030 - 17 ms

<trigger-start id="5558" timestamp="2018-09-06T00:14:54.088" />
<cycle-start id="5559" type="global" contextid="0" timestamp="2018-09-06T00:14:54.090" intervalms="298292.798" />
<gc-op id="5560" type="heartbeat" contextid="5559" timestamp="2018-09-06T00:14:55.091">
  <quanta quantumCount="112" quantumType="mark" minTimeMs="0.508" meanTimeMs="1.091" maxTimeMs="3.334" maxTimestampMs="141383589.583" />
  <exclusiveaccess-info minTimeMs="0.001" meanTimeMs="0.043" maxTimeMs="0.604" />
  <free-mem type="heap" minBytes="90058977056" meanBytes="90732567558" maxBytes="91265830184" />
  <thread-priority maxPriority="11" minPriority="11" />
</gc-op>

-----------

2018-09-06 01:06:55.027 - 17 ms
landed between two cycles
<trigger-end id="5669" timestamp="2018-09-06T01:02:18.903" />

<trigger-start id="5670" timestamp="2018-09-06T01:07:43.336" />

-------------

2018-09-06 03:36:25.033 - 16 ms

<trigger-start id="5983" timestamp="2018-09-06T03:36:23.108" />
<cycle-start id="5984" type="global" contextid="0" timestamp="2018-09-06T03:36:23.110" intervalms="202953.904" />
<gc-op id="5985" type="heartbeat" contextid="5984" timestamp="2018-09-06T03:36:24.115">
  <quanta quantumCount="138" quantumType="mark" minTimeMs="0.596" meanTimeMs="1.092" maxTimeMs="3.580" maxTimestampMs="153472609.784" />
  <exclusiveaccess-info minTimeMs="0.001" meanTimeMs="0.020" maxTimeMs="0.205" />
  <free-mem type="heap" minBytes="90217674144" meanBytes="90728526099" maxBytes="91265551256" />
  <thread-priority maxPriority="11" minPriority="11" />
</gc-op>
<gc-op id="5986" type="heartbeat" contextid="5984" timestamp="2018-09-06T03:36:25.136">
  <quanta quantumCount="202" quantumType="mark" minTimeMs="0.821" meanTimeMs="1.078" maxTimeMs="1.317" maxTimestampMs="153473894.439" />
  <exclusiveaccess-info minTimeMs="0.001" meanTimeMs="0.012" maxTimeMs="0.186" />
  <free-mem type="heap" minBytes="89761010936" meanBytes="89910399143" maxBytes="90206180680" />
  <thread-priority maxPriority="11" minPriority="11" />
</gc-op>

--------------

2018-09-06 05:41:20.016 - 17 ms

<trigger-start id="6216" timestamp="2018-09-06T05:41:19.851" />
<cycle-start id="6217" type="global" contextid="0" timestamp="2018-09-06T05:41:19.853" intervalms="275356.199" />
<gc-op id="6218" type="heartbeat" contextid="6217" timestamp="2018-09-06T05:41:20.854">
  <quanta quantumCount="175" quantumType="mark" minTimeMs="0.640" meanTimeMs="1.088" maxTimeMs="3.404" maxTimestampMs="160969352.656" />
  <exclusiveaccess-info minTimeMs="0.001" meanTimeMs="0.021" maxTimeMs="0.382" />
  <free-mem type="heap" minBytes="90536733464" meanBytes="90720137768" maxBytes="91265962920" />
  <thread-priority maxPriority="11" minPriority="11" />
</gc-op>
```

**Comment by amicic** [comment]
-Xgc:regionSize=262144 was meant to help reducing  GC overhead on application throughput (by reducing the duration of GC cycle, due to less overhead on meta-structure processing, by having fewer/larger regions), but if the worst case GC pause time is bigger concern, than the default should be better (smaller work unit), specifically during sweep phase (which indeed exhibits some 3-5ms pauses relatively frequently).

What can help with worst case pause times is reducing GC utilization. Default is 30% (application targetUtilization 70%), so 10-20% should be tried. This will, however, make GC cycle about 2-3x longer, and there is a risk of not completing the cycle concurrently, but enter synchronous mode. Hence, compensation might be needed in setting an earlier trigger point and/or increasing heap size.

I'm not completely clear why gcthreads shows as 12, while numCPUs is 24, but I'm guessing it has to do something with setting CPU affinity. I would expect that GC would scale fine even with 24 threads (and make GC cycle shorter, while not affecting the worst case pause times) and would be preferred over 12 (as long as there are 24 h/w threads available).

Some outliers of 3-4ms show in the first heartbeat of a GC cycle. Just from verbose GC we cant tell why, but if I remember well, we can enable some trace logging for more detailed breakdown when the pauses occur). I can look a bit more if extra tracing is ok to be enabled (adds some throughput overhead)... If the delay adds being during roots processing, specifically if it takes that much to scan one very large thread stack, we cannot do anything about it.

Overall, while GC certainly contributes to the pauses observed from the app level, I don't see it causing 17ms delays just by itself. The second example (01:06:55.027) indeed shows that there was no active GC cycle at the time.

**Comment by akrus** [comment]
@amicic, thanks for your comments. I've returned regionSize back to normal and changed targetUtilization to 85%.

gcthreads is 12 because of CPU affinity, yes, JVM can only use 12 cores there, so should be OK.

I'll collect some more metrics and report here.

**Comment by akrus** [comment]
OK, posting results here.

Applied all the changes and also did a few optimizations on OS level, now everything is perfect. Thanks everyone for assistance!

@amicic, for metronome pause times are you using GCMV? I can see there is 'Exclusive access time' and 'GC quantum time' - are those showing the actual pause?

**Comment by amicic** [comment]
There is no link to results.

I do use GCMV for first pass analysis. You can spot outliers etc. But deeper analysis I also look into the logs, do some parsing that GCMV does not. Especially true for non-metronome GC policies where verbose GC is much more verbose.

Yes, exclusive access time and quantum times are the actual pauses. 

Exclusive access is time to stop application threads so that a GC increment can be performed. This is async mechanism within VM (has nothing to do with OS thread suspend - threads themselves eventually recognize that they should stop). Typically they respond within a few microsec, but sometimes it could take milisec.

Quantum (increment) times are actual GC pauses, once all threads stop. 

Both are grouped in one verbose GC stanza (gc-op hearbeat) that covers a period of 1 sec, where we report averages and extremes (it would be to much text to report every single quanta). With default utilization (70%) and 1ms increment, there could be up to 300 quantas in one GC heartbeat.

GC heartbeats are grouped in GC cycle (periods when GC is active), with cycle-start/cycle-end stanza.

**Comment by akrus** [comment]
Sorry, here is the link:
http://nya.im/jvm_20180915.log

**Comment by pshipton** [comment]
Just in case, attaching the file
[jvm_20180915.log](https://github.com/eclipse/openj9/files/2390407/jvm_20180915.log)

**Comment by amicic** [comment]
An excerpt from trace point logs:

06:16:11.027736000  0x00007f4690003c00 j9mm.467            Event       Cycle Start: type 1 approximateFreeMemorySize 93952224376
06:16:11.027773000  0x00007f4690003c00 j9mm.474            Event       GlobalGC start: globalcount=554
06:16:11.036980000  0x00007f4690003c00 j9mm.190            Entry      >MM_GlobalCollector_isTimeForClassUnloading. dynamicClassUnloading:1 classLoaderBlocks:381 dynamicClassUnloadingThreshold:1 lastUnloadNumOfClassLoaders:381

As before, this shows that the pause very early in a GC cycle before we even start heavy GC work.

**Comment by amicic** [comment]
I guess, this should be closed. https://github.com/eclipse/openj9/issues/4769 is more up to date.
