### ISSUE TITLE
sun_misc_Unsafe.cpp fails to register 18_03 methods

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#292]
sun_misc_Unsafe.cpp is meant to run registerJdkInternalMiscUnsafeNativesJava18_3 from Java_jdk_internal_misc_Unsafe_registerNatives(JNIEnv *env, jclass clazz)

The "if" statement surrounding the 18_3 method call does not appear to work, and a build will fail after it begins the "Creating support/modules_libs/java.base/libjsig.so from J9 sources" step with an UnsatisfiedLinkError: Unsafe.objectFieldOffset1(Class,String)J

Note: changing classlib.properties to 1803 doesn't appear to fix the issue.

**Comment by JasonFengJ9** [comment]
The reason "changing classlib.properties to 1803 doesn't appear to fix the issue" might be due to that the binaries like `libjvm.so` weren't copied to correct locations. One way to confirm that is to identify the command line hitting `UnsatisfiedLinkError: Unsafe.objectFieldOffset1(Class,String)J`, and verify if the `libjvm.so` binary files are correct for that running JVM.

Another hack could be to remove the check for `J2SE_SHAPE_B1803` temporarily, and perform the native registration unconditionally such that we will know more about the nature of this error.

**Comment by pshipton** [comment]
The correct libjvm.so files are the b156 ones. 
redirector/libjvm_b156.so is renamed to libjvm.so and goes in lib/jvm and lib/server
j9vm_b156/libjvm.so is copied to lib/compressedrefs/libjvm.so

**Comment by pshipton** [comment]
and classlib.properties if found in the lib directory.

**Comment by adamfarley** [comment]
After discussing this with Jason late last week, he proposed that we use the "release" file to trigger/block objectFieldOffset1's registration based on the java version, as the existing method isn't triggering properly for 18.3 at this stage in the build.

Jason, any luck with this?

**Comment by JasonFengJ9** [comment]
Working on a draft pull request, expected to be submitted for reviewing today or tomorrow.

**Comment by adamfarley** [comment]
Thanks Jason. :)

**Comment by pshipton** [comment]
@JasonFengJ9 is this Issue resolved now with the merge of #371?

**Comment by JasonFengJ9** [comment]
@pshipton yes, this issue can be closed by #371.
