### ISSUE TITLE
Add a better project description

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#306]
When searching for "OpenJ9" on GitHub or even Google the description is what gets picked up (ex. [GitHub](https://github.com/search?utf8=%E2%9C%93&q=openj9&type=) or [Google](https://www.google.ca/search?q=openj9)). We should add a better, more descriptive project description, similarly to how [OMR](https://github.com/eclipse/omr) does. And perhaps we can add a link to the website in the description as well: https://www.eclipse.org/openj9

Perhaps:

> Eclipse OpenJ9™ is a high performance, scalable, Java virtual machine (JVM) implementation
> https://www.eclipse.org/openj9

(copied from the website)

**Comment by DanHeidinga** [comment]
Thanks for suggesting this @fjeremic.  It's been on my "I should do that list" for a while now.

I'll leave this for a day or two to allow for feedback on the proposed wording and then will open the eclipse bugzilla to get it changed.

**Comment by mstoodle** [comment]
Suggested text: OpenJ9: A Java Virtual Machine for OpenJDK that's optimized for low footprint, quick start-up, and high throughput.

**Comment by mstoodle** [comment]
Alternate: OpenJ9: A Java Virtual Machine for OpenJDK optimized to save you money in the cloud.

**Comment by 0xdaryl** [comment]
I like @mstoodle's first suggestion with a couple of minor word tweaks:  "OpenJ9: A Java Virtual Machine for OpenJDK that's optimized for small footprint, fast start-up, and high throughput."

**Comment by samkamer** [comment]
I have a slightly different view. Someone directly searching for OpenJ9 or Google is going to get multiple links pointing to the various OpenJ9 resources. Even official resources that will show up are multiple - OpenJ9 website at eclipse foundation, OpenJ9 *repos (plural)* on github and so on. As we have multiple GitHub repos related to OpenJ9, the description of these should clearly identify the code / content that the repos hold more than anything else. So rather than repeating what already shows up as description for the OpenJ9 website (https://www.eclipse.org/openj9/), I would vote to describe this repo as the master / main repository of OpenJ9 source code. I would further urge to align the descriptions of the website repo, extension repo, adoptOpenJDK repo, such that all the relationships and dependencies make sense.

**Comment by DanHeidinga** [comment]
@samkamer I like the idea of describing the relationship between the repos.  Can you propose 1-2 sentences to add to Mark / Daryl's wording in https://github.com/eclipse/openj9/issues/306#issuecomment-336251973 ?

**Comment by samkamer** [comment]
I am not yet completely clear about the relationships, so I am going to start with describing what I understand as the relationship between the repos, and will leave it to better wordsmiths to compress it to fit the 'description' word limit.
*This is the main source code repo for Eclipse OpenJ9, a Java virtual machine implementation that builds on components from <link to Eclipse OMR repo>.  Add the Extensions for OpenJDK from <link to extensions repo>, get source from OpenJDK and build an Open Java SDK optimized for small footprint, fast start-up, and high throughput.* Test compatibility by running OpenJDK Regression tests (modified to exclude HotSpot specific tests) from AdopopenJDK <link to AdoptOpenJDK/openjdk-test repo>. If you just want the binaries, get them from AdoptOpenJDK <link to download>.

The part in bold above will fit the preview that is seen on the home page of the repo.

**Comment by DanHeidinga** [comment]
I've opened a bug with the Eclipse foundation to get the text updated: https://bugs.eclipse.org/bugs/show_bug.cgi?id=527017

The text is based on Mark & Daryl's version with small amendments from Samir.  I've also proposed text for the OpenJ9-OMR repo that directs most PRs to the upstream repo.

Thanks everyone!

**Comment by DanHeidinga** [comment]
Project descriptions updated.  Closing this now.  If further tweaking to the description is required, please reopen.
