### ISSUE TITLE
Investigate use of transparent large pages when set to [madvise]

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#3611]
While OpenJ9 already uses transparent_hugepages, it doesn't when the enabled setting is set to `[madvise]`: 

```
cat /sys/kernel/mm/transparent_hugepage/enabled
always [madvise] never
```

Investigate whether we should use `MADV_HUGEPAGE` & `madvise` to allocate the heap and / or the code cache.

**Comment by DanHeidinga** [comment]
Resources:
* https://lwn.net/Articles/423592/
* https://stackoverflow.com/questions/30470972/using-mmap-and-madvise-for-huge-pages

**Comment by fengxue-IS** [comment]
looking into this

**Comment by DanHeidinga** [comment]
@fengxue-IS Any update on this?

**Comment by fengxue-IS** [comment]
Read through the documentation for `madvise` with `MADV_HUGEPAGE`. Looking into GC code for locations to implement the call so only large memory mappings will be considered for promotion.

Discussed with @LinHu2016 on how GC manages heap initialization.

Continuing to investigate/test impact of adding madvise call

**Comment by amicic** [comment]
Looking from the perspective what is potentially bad about always enabled THP (specifically for object heap)....

When we tenure objects (during Scavenge), and we touch area of Tenure for the first time, it may cause long pauses (sometimes several seconds) to commit a few large pages (because kernel underneath may do de-fragmentation of used physical small pages to create unused large pages). These GC pauses may occur as long as there are un-commited area of Tenure. If heap is fully expanded from start, it's typically till first global GC. If heap is not fully expanded, it may stretch arbitrarily deep into the run.

[Btw, this de-fragmenation may occur during first touching of Nursery too, but I consider this less of a problem. It's spread among mutator accesses in relatively larger span of time, most of them will withing startup phase where there are heavy JIT compilations. Let alone it's not visible to GC and hard to quantify/report].

So, a simple proposal is: if application (customer) cares about pauses and don't want them to occur late in a run, we may want to disable THP on Tenure area but enable on Nursery. It will come will some throughput penalty, but probably not so much, since hot (frequently accessed) areas of the heap are typically in Nursery.

**Comment by dmitripivkine** [comment]
There is no other way to investigate this as to do a lot of performance testing using different benchmarks on various HW platforms and Linux Distributions (and be sure that usage of THP is set to madvise). In our experience we know that using of THP is beneficial for many customers but might create unwanted side effects as @amicic mentioned.

**Comment by amicic** [comment]
Just to clarify 'if application (customer)...'

By default all newer distros are configured with ALWAYS. I don't imagine system being 'randomly' configured with MADVISE global settings. 

So, if customer observes long Scavenge pauses due to THP enabled, it would have a choice of configuring the system with THP MADVISE (and do nothing else, like provide another VM option). Our VM would (for example) madvise THP disable on Tenure and enable on Nursery, which would maintain most of throughput benefits of THP, but remove THP related GC pauses.

**Comment by dmitripivkine** [comment]
@charliegracie FYI

**Comment by andrewcraik** [comment]
I just wanted to say I did run into this running a performance benchmark on SLES12sp3 (released late 2017) - the system default is madvise and for this benchmark the use of THP significantly reduced TLB misses allowing higher throughput. So newer release may default to ALWAYS, but I expect a non-trivial number of users may have madvise as the default still.

**Comment by andrewcraik** [comment]
FYI @vijaysun-omr since we were talking about this at one point.

**Comment by fengxue-IS** [comment]
https://github.com/eclipse/omr/pull/3611

I have wrote a prototype for using `madvise` to set hugepage flag for nursery region in gencon as @amicic have suggested.

FYI @dmitripivkine @DanHeidinga

**Comment by DanHeidinga** [comment]
@fengxue-IS Can you update this with a description of the discussion @dmitripivkine, you and I had about how to approach this?

**Comment by fengxue-IS** [comment]
Per discussion with Dan and Dmitri, we will start with 
- adding madvise functionality to portlibrary
    - check page size and THP option for system
- create vm option to enable / disable madvise (default to enable) 
- call madvise api for gc heap (may extend to JIT code cache)

**Comment by dmitripivkine** [comment]
I believe would be better to follow @charliegracie suggestions https://github.com/eclipse/omr/pull/3611#issuecomment-467489062
It would simplify implementation

**Comment by amicic** [comment]
I agree will simple initial approach. Setting only Nursery is an advanced/nice-to-have capability we can consider at a later point.

**Comment by pshipton** [comment]
This doesn't appear ready to be delivered in the 0.14 release. @DanHeidinga should it be moved to the next release?

**Comment by DanHeidinga** [comment]
Agreed.  The new design for this - https://github.com/eclipse/omr/pull/3647 - is still a draft PR.

**Comment by fengxue-IS** [comment]
initial OMR port library change merged, will work on the OpenJ9 side to add an `-X` cmdline option for controlling THP behaviour under `madvise`.

**Comment by pshipton** [comment]
I believe this is completed now, anything further will occur via https://github.com/eclipse/openj9/issues/6156

**Comment by pshipton** [comment]
The doc issue for this is https://github.com/eclipse/openj9-docs/issues/273
