### ISSUE TITLE
Verify the build instructions for OpenJDK 11 on macOS

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9#3971]
After completing the OpenJDK 8 on macOS build instructions, I'm concerned that we have some missing content for the OpenJDK 11 instructions here: https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V11.md#macos

Preparation: 
1. Although there are different Xcode versions and boot JDKs required, the following pre-reqs are not listed in the OpenJDK 11 instructions:

- autoconf
- freetype 2.9.1
- git 2.18.2
- gnu-sed 4.5
- pkg-config 0.29.2
- wget 1.19.5

Are any of these NOT required for OpenJDK 11 builds?

2. Preparation steps

- freemarker step to get and unpack is slightly different w.r.t --strip-components=2. Accurate?
- dscl steps missing. Needed?
- environment variables not set. Needed?
- On OSX 10.10 you need to change line 143 .... Don't think this is relevant to OpenJDK11. Confirm?

3. Configure

- extra steps in configure for OpenJDK 8. Don't think any of these are needed. Confirm?

4. Build

- do you also get bundle and image builds for macOS on OpenJDK 11. Plse confirm?

@babsingh - please can you help with this?

**Comment by babsingh** [comment]
1. `gnu-sed 4.5` may not be needed. But, I would suggest the usage of `gnu-sed` over OSX's default `bsd-sed`. So, all needed: `autoconf, freetype 2.9.1, git 2.18.2, gnu-sed 4.5, pkg-config 0.29.2 and wget 1.19.5`.

2. Preparation Steps:
a. freemarker step w.r.t `--strip-components=2` is accurate. `gtar --help` shows that `--strip-components=2` is a valid option.
b.`dscl` steps are not needed.
c. `change line 143` is required to fix a bug in `OSX 10.10`. JDK11 is built using `OSX 10.13+`. `OSX 10.13+` doesn't have the `OSX 10.10` bug. So, `change line 143` is not needed for JDK11.
d. To use `gsed` or `gtar`, the following environment variables can be set:
```
export SED=/usr/local/bin/gsed
export TAR=/usr/local/bin/gtar
```
`JAVA_HOME` is not needed because `--with-boot-jdk=` is specified in the configure options.

3. `extra steps in configure for OpenJDK 8` are not needed for JDK11. But, we can specify usage of `--with-freetype` in case `configure` doesn't automatically detect `freetype`. Usage: `--with-freetype=/usr/local/Cellar/freetype/2.9.1/`.

4. Yes, you will get bundle and image builds for macOS on OpenJDK 11. For JDK11, you won't get `j2sdk-image|bundle` or `j2re-image|bundle`. Naming is slightly different for JDK11:
```
build/macosx-x86_64-normal-server-release/images/jdk
build/macosx-x86_64-normal-server-release/images/jdk-bundle
```

fyi - @SueChaplain
