### ISSUE TITLE
15-39% ODM Regressions on All Platforms due to default SCC cache

### ISSUE THREAD

**Issue by piyush286** [eclipse/openj9#4205]
Discovered internal to IBM and being investigated. This Issue is created so the problem can be exposed to the Release 0.12.0 milestone plan.

**Comment by mpirvu** [comment]
I did some investigation using SPECjbb2005 as a benchmark. We know that the problem was triggered by enabling the shared class cache and AOT by default. The underlying issue is that enabling AOT also enables interpreter profiling data persistence. This means that, in order to improve start-up time, interpreter profiling data is stored in the SCC and in the warm run the JIT will turn off Iprofiler collection during start-up relying on data stored in SCC. The default/implicit SCC only allows bootstrap classes and methods in it, but when we disable Iprofiler collection we do it for all classes/methods (in fact the Iprofiler does not even know what method is profiling). This means that many non-bootstrap methods may be optimized without Iprofiler info.

Running with -Xjit:disableIprofilerDataPersistence improves SPECjbb2005 by 20% or so.

-Xshareclasses:none results: 
158174,  146175,  152664

With implicit SCC:
139054
119112
111787
110552

With implicit SCC and -Xjit:disableIProfilerDataPersistence:
140364
143295
146290
141335

@awsaf-sakif Could you please run the ODM benchmark with `-Xjit:disableIprofilerDataPersistence`

**Comment by pinicman** [comment]
Running the 1207 build with -Xjit:disableIprofilerDataPersistence there is an ~11.5% improvment:

With implicit SCC:
4756
1.5% CI

With implicit SCC and -Xjit:disableIProfilerDataPersistence:
5305
1.57% CI
Improvement over implicit = ~11.5%

**Comment by mpirvu** [comment]
Looking at the results with the 'good' build the scores were 5400-5500, so the remaining regression is ~3%

**Comment by vijaysun-omr** [comment]
@pshipton and @DanHeidinga I would like to propose reverting the "default shared classes" change for the 0.12 release. It does'nt seem like we would be able to fix the regression being investigated here and do the necessary performance testing on the fix in time for the 0.12 release.

**Comment by DanHeidinga** [comment]
I agree.  I don't want to eat the performance hit we're currently seeing due to the loss of iprofiler data.  @hangshao0 Can you put together a PR to disable SCC by default for both JDK8 & 11?

**Comment by pshipton** [comment]
@SueChaplain @doveye note this decision to disable shared classes by default.

**Comment by DanHeidinga** [comment]
I've opened a new issue to track the reverting SCC by default

**Comment by pshipton** [comment]
I wonder if the gcc 7.3 change on xlinux (~17% regressed -Xint) could be factor in the remaining  ODM regression.

**Comment by mpirvu** [comment]
I ran more SPECjbb2005 attempting to understand the cause of the remaining SCC- noSCC gap.
Assuming that the remaining gap is still due due to lower IProfiler data, I used disableIProfilerDatapersistence and scount=1000 (to collect more IP info for the AOT loads). This increased throughput somewhat, but still not enough:
145212
148240
150255
148746
151317
143087

In the same configuration as above, if I limit the AOT space to 512k (about 180 methods) the gap closes completely (I see scores ~ 156000). Continuing to increase the AOT space, the performance drops very little until 800k (~155000) then drops a bit more for 900k (~152000) and drops under 150000 for 950k. I am going to look more in this 900 - 950k interval, see what additional methods get AOTed and why are they so important,

**Comment by mpirvu** [comment]
I have the list of AOT methods that appear when I set the AOT space to 100k, but do not appear when I set the AOT space to 900k. However, looking at the perf profile during steady state, all methods that get at least one tick are NOT stuck in AOT bodies (they get recompiled). Thus I cannot explain why more AOT means lower performance. Note and in these experiments I already disabled IProfiler persistence and increased scount to 1000.

```
List of methods that had an AOT load in the second vlog that is not present in the first vlog:
java/lang/String.toUpperCaseCore(Ljava/lang/String;)Ljava/lang/String;
java/math/BigInteger.montReduce([I[III)[I
java/util/Hashtable.addEntry(ILjava/lang/Object;Ljava/lang/Object;I)V
java/util/Hashtable$Entry.<init>(ILjava/lang/Object;Ljava/lang/Object;Ljava/util/Hashtable$Entry;)V
java/lang/ThreadLocal$ThreadLocalMap.access$000(Ljava/lang/ThreadLocal$ThreadLocalMap;Ljava/lang/ThreadLocal;)Ljava/lang/ThreadLocal$ThreadLocalMap$Entry;
java/lang/ThreadLocal$ThreadLocalMap.getEntry(Ljava/lang/ThreadLocal;)Ljava/lang/ThreadLocal$ThreadLocalMap$Entry;
java/lang/StringCoding.deref(Ljava/lang/ThreadLocal;)Ljava/lang/Object;
java/lang/StringCoding$StringDecoder.requestedCharsetName()Ljava/lang/String;
java/lang/String.<init>([BLjava/lang/String;)V
com/sun/org/apache/xerces/internal/dom/ParentNode.internalRemoveChild(Lorg/w3c/dom/Node;Z)Lorg/w3c/dom/Node;
com/sun/org/apache/xerces/internal/dom/NodeImpl.ownerDocument()Lcom/sun/org/apache/xerces/internal/dom/CoreDocumentImpl;
com/sun/org/apache/xerces/internal/dom/NodeImpl.needsSyncData()Z
java/util/logging/Logger.entering(Ljava/lang/String;Ljava/lang/String;)V
com/sun/org/apache/xerces/internal/dom/ParentNode.getOwnerDocument()Lorg/w3c/dom/Document;
java/util/logging/Logger.exiting(Ljava/lang/String;Ljava/lang/String;)V
com/sun/org/apache/xerces/internal/dom/NodeImpl.isFirstChild()Z
com/sun/org/apache/xerces/internal/dom/NodeImpl.isNormalized(Z)V
com/sun/org/apache/xerces/internal/dom/CharacterDataImpl.setNodeValue(Ljava/lang/String;)V
com/sun/org/apache/xerces/internal/dom/CharacterDataImpl.setNodeValueInternal(Ljava/lang/String;)V
com/sun/org/apache/xerces/internal/dom/CharacterDataImpl.setNodeValueInternal(Ljava/lang/String;Z)V
com/sun/org/apache/xerces/internal/dom/DocumentImpl.modifyingCharacterData(Lcom/sun/org/apache/xerces/internal/dom/NodeImpl;Z)V
com/sun/org/apache/xerces/internal/dom/DocumentImpl.modifiedCharacterData(Lcom/sun/org/apache/xerces/internal/dom/NodeImpl;Ljava/lang/String;Ljava/lang/String;Z)V
java/util/ArrayList.access$000(Ljava/util/ArrayList;)I
com/sun/org/apache/xerces/internal/dom/ElementImpl.getNodeName()Ljava/lang/String;
com/sun/org/apache/xerces/internal/dom/ChildNode.getPreviousSibling()Lorg/w3c/dom/Node;
com/sun/org/apache/xerces/internal/dom/ParentNode.removeChild(Lorg/w3c/dom/Node;)Lorg/w3c/dom/Node;
java/util/ArrayList.remove(I)Ljava/lang/Object;
com/sun/org/apache/xerces/internal/dom/DocumentImpl.removingNode(Lcom/sun/org/apache/xerces/internal/dom/NodeImpl;Lcom/sun/org/apache/xerces/internal/dom/NodeImpl;Z)V
com/sun/org/apache/xerces/internal/dom/DocumentImpl.removedNode(Lcom/sun/org/apache/xerces/internal/dom/NodeImpl;Z)V
java/util/Calendar.complete()V
java/util/Calendar.internalGet(I)I
java/util/Calendar.get(I)I
java/math/BigDecimal.toString()Ljava/lang/String;
java/util/TreeMap.compare(Ljava/lang/Object;Ljava/lang/Object;)I
java/math/BigDecimal.compareTo(Ljava/math/BigDecimal;)I
java/util/ArrayList$Itr.hasNext()Z
java/util/ArrayList$Itr.checkForComodification()V
java/util/ArrayList$Itr.next()Ljava/lang/Object;
java/util/Calendar.setTimeInMillis(J)V
java/util/TreeMap.getEntry(Ljava/lang/Object;)Ljava/util/TreeMap$Entry;
sun/util/calendar/CalendarDate.getYear()I
java/util/GregorianCalendar.getWeekNumber(JJ)I
java/util/Calendar.getFirstDayOfWeek()I
sun/util/calendar/AbstractCalendar.getDayOfWeekDateOnOrBefore(JI)J
java/util/Calendar.getMinimalDaysInFirstWeek()I
java/util/Calendar.setTime(Ljava/util/Date;)V
java/util/Date.getTime()J
java/util/TreeMap.rightOf(Ljava/util/TreeMap$Entry;)Ljava/util/TreeMap$Entry;
sun/util/calendar/ZoneInfo.getTransitionIndex(JI)I
java/util/TreeMap.getFirstEntry()Ljava/util/TreeMap$Entry;
java/util/TreeMap.getCeilingEntry(Ljava/lang/Object;)Ljava/util/TreeMap$Entry;
sun/nio/cs/StreamEncoder.implFlushBuffer()V
java/lang/J9VMInternals.fastIdentityHashCode(Ljava/lang/Object;)I
```

**Comment by mpirvu** [comment]
One other far fetched theory is around the heuristics that decide not to inline certain methods if they are already compiled. AOT loads could change the timing leading to less inlining being performed. I am going to test this by disabling said heuristic.

**Comment by mpirvu** [comment]
Summary of SPECjbb2005 experiments so far:

```
Score   Config
154000  Xshareclasses:none (baseline)
114000  With implicit SCC                                 26% regression
141500	Implicit SCC, disableIProfilerDataPersistence      8% regression
149000  As above, scount=1000                              3.2% regression
149500  As above, gcrcount=1                               3.0% regression
150000  As above, largeCompiledMethodExemptionFreqCutoff=0 2.6% regression
```

The biggest impact is from IprofilerPersistence. After disabled that, the methods that get AOTed do not have enough IProfiler info because of the low invocation count (scount=20 for AOT loads). Increasing scount to 1000 makes the throughput improve by ~5%. Everything else I tried after this point had a negligible effect on throughput (Note that the confidence interval for these runs is about 2%)

Another experiment that I performed is with `export TR_DisableNoIProfilerDuringStartupPhase=1 `
This allows Iprofiler persistence, but allows the collection of IProfiler info during startup as well. The JIT will have two sources of Iprofiler info and will pick the one that has the most samples. I was hoping that this change would lift the score around 14.9K but it turn out to be ~141500 (similar to `disableIProfilerDataPersistence`).
This change cannot be made the default because the Iprofiler activity slows down start-up. In Liberty 18.0.0.4 I measured a 4.5% start-up regression when we allow IProfiler collection during start-up (config was without -Xquickstart)

The next best thing is to implement this change only when the SCC is implicitly defined (no -Xshareclasses option). This will eat into the improvements made by SCC/AOT but hopefully at the end of the day there will be some start-up improvement while throughput will be less affected. Liberty benchmarks will remain unaffected because Liberty explicitly defines a SCC.

As next step I would like to evaluate the effect of `export TR_DisableNoIProfilerDuringStartupPhase=1 ` on ODM throughput.

**Comment by mpirvu** [comment]
I evaluated the effect of `export TR_DisableNoIProfilerDuringStartupPhase=1` on ODM 5Path when using SCC with bootClassesOnly and the regressions seems to go away. I cannot give a precise number because the fluctuations were high and I had a small number of runs.

I also evaluated tomcat startup in 4 scenarios
1) No SCC ==> startTime=4009 ms
2) SCC ==> startTime=2268 ms
3) SCC bootClassOnly ==> startTime=2652 ms
4) SCC bootClassOnly TR_DisableNoIProfilerDuringStartupPhase=1 ==> startTime=2830 ms

As expected, caching only bootstrap classes increases startup time ( (2) vs (3)). 
Moreover, allowing IProfiler to work in the warm run makes the start-up time grow more ( (3) vs (4)).
However, in the end this is a win: 2830/4009=0.71 (29% startup time improvement)

**Comment by vijaysun-omr** [comment]
Thanks, this leads to potentially two things to do:

In the short term, maybe detect when we are dealing with a "default SCC" and run the IProfiler during startup as a change to perhaps allow "default SCC" to be enabled sooner rather than later (assuming other benchmarks are also good from a throughput standpoint with that change). 

In the longer term, understand why the persisted IProfiler info in the SCC was'nt good quality enough. I am unsure if the disabling of IProfiler during startup applies to all methods, but if it does, then one reason things may be worse is that we don't have good IProfiler info for non-bootstrap classes methods from the SCC (since they are not in the SCC) and we also don't have good IProfiler info for them from the running JVM instance since we have disabled IProfiler during startup.

**Comment by DanHeidinga** [comment]
@mpirvu Is this still relevant?  Default SCC has already been enabled at this point so I assume not.

**Comment by mpirvu** [comment]
The only remaining regression was one of the ILOG benchmarks, only on zLinux, only on Java11, only on one machine (Filip couldn't reproduce it) and even that regression seems to have gone away in the latest round of testing. All in all we should be good.
