### ISSUE TITLE
All JIT Power work for "Correctly truncate boolean values in the appropriate bytecodes #2049"

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#4241]
Power work for  https://github.com/eclipse/openj9/issues/2049

- [x] JNI methods: https://github.com/eclipse/openj9/issues/4244

**Comment by gita-omr** [comment]
@DanHeidinga is this all that is required from JIT for https://github.com/eclipse/openj9/issues/2049 ?

**Comment by DanHeidinga** [comment]
My understanding was the conversions for `bastore`, `putfield`, `putstatic` & and truncated return bytecodes were complete in `0.11.0`.   Can you confirm this is the case?

For JIT behaviour, `0.12.0` added checking jni boolean returns using ` != 0`.  

The Interpreter has also added similar checks for Unsafe access which the JIT will need to match in 0.13.0

**Comment by gita-omr** [comment]
@andrewcraik could you confirm comment above? I added 'JIT common work' bullet to the parent issue.

**Comment by andrewcraik** [comment]
yes bastore, putfield, putstatic and truncated return were done in `0.11.0`. The codegen change needed was the truncation of the jni Boolean returns where direct invocation was performed (the VM truncates already due to another change included in `0.12.0`). The work in `0.11.0` was done at the trees level and did not require specific codegen changes - we just added the appropriate iand operations.

**Comment by gita-omr** [comment]
Ok, so closing then.
