### ISSUE TITLE
Difference between JCL_VERSION 'latest' and 'current'?

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#451]
I followed instructions [here](https://github.com/eclipse/openj9/blob/master/test/README.md) to compile and run tests locally. I noticed 'pltest' didn't run because `make -f run_configure.mk` did not generate `autGenTest.mk` under `pltest` directory.
On further analysis I noticed following code:
https://github.com/eclipse/openj9/blob/05160934f57ada3fdf831d6a547715f1fc0055cc/test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl#L111-L112

That mean if JCL_VERSION is `latest`, pltest would be excluded.
Indeed, JCL_VERSION was set to `latest` by `make -f run_configure.mk`.
I am able to work around this by exporting `JCL_VERSION=current`.

But I didn't understand the significance of JCL_VERSION and the difference between `latest` and `current` value.
Are the excluded projects not stable when run with `JCL_VERSION=latest`?

Would it be better if couple of statements are added in README.md around the impact of JCL_VERSION?

**Comment by ashu-mehra** [comment]
@smlambert @llxia fyi

**Comment by smlambert** [comment]
I do not plan to update the README in this case.  We do not want to advertise that there is a (temporary) environment variable that we are currently leveraging to be able to support old class library versions in our internal builds (b148) and the single class library version (tip=b181 at the moment) in the OpenJ9 builds.  That is why there is no documentation for it, and that is also why latest is the default value, the one that matters in OpenJ9.

pltest are native tests for the port library (most of the tests that used to be in there have been moved to omr).  The libraries for native tests are not being built at the moment in OpenJ9, which is why pltest is in the disabled list.  Likely we should create an issue for this in the OpenJ9 repo, as there is only an open internal issue at the moment (which I think is a bit stale).

@pshipton @DanHeidinga - Do you have insight on when we will be able to remove this temporary support for multiple class libraries?  I am assuming it depends on having builds for all platforms on the latest CL available.

**Comment by pshipton** [comment]
We can remove b148 support when we have full platform coverage (+ Windows, AIX, z/OS) and roughly equivalent testing (+SVT).

**Comment by DanHeidinga** [comment]
Question appears to be answered.  Closing.
