### ISSUE TITLE
Running Java 12 pipelines

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4638]
Tried to run Java 12 functional.sanity testing with the changes from #3980 and #4531
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/30/

Seems like a setting is missing because the testing is looking for the jdk8 directory `j2sdk-image`.

`19:48:18 /home/jenkins/workspace/Test-sanity.functional-JDK12-linux_x86-64_cmprssptrs/openjdk-tests/functional/DDR_Test/build.xml:59: Error running /home/jenkins/workspace/Test-sanity.functional-JDK12-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/../../bin/javac compiler`

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau @llxia

**Comment by AdamBrousseau** [comment]
I think the j2sdk is expected. The double ../ is concerning. The jdk11 build doesn't have these.

**Comment by llxia** [comment]
The problem is that we set `-DJDK_VERSION=8` when running ant.

```
00:14:35.182 ant -f scripts/build_test.xml -DTEST_ROOT=/home/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/.. -DBUILD_ROOT=/home/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/../../jvmtest -DJAVA_BIN=/home/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/bin -DJDK_VERSION=8 -DJCL_VERSION=latest -DBUILD_LIST=functional -DRESOURCES_DIR=/home/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/../../jvmtest/TestConfig/resources -DPLATFORM=linux_x86-64_cr -DJDK_HOME=/home/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/bin/../.. -DJVM_VERSION=openjdk8-openj9
```

In case you want to know more detail:
`JAVA_VERSION` will be replaced by `JDK_VERSION`. Currently, we are supporting both of them. The covertion code from `JAVA_VERSION` to `JDK_VERSION` is not updated to support Java12. It does not understand `SE120`, so default value `8` is used.

I will have a PR to fix this soon.
