### ISSUE TITLE
Add PR build capability for ValueTypes

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#4719]
# Description
 - Add a PR build to test a ValueTypes enabled JDK. The valueTypes changes are not enabled by default and require to be compiled with specific flags turned on. For this reason, it cannot be tested with the existing PR builds.

# Reason for issue
- Valhalla is a multi-release project that contains many features. Some of these have already been released such as nestmates and varhandles. Some of these features are still to come, such as value types and specialized generics. In order to make progress on the upcoming features we need to prototype it in openj9. There is a risk if we commit changes without testing them so it is essential that we have a build that can run ValueTypes tests.

**Comment by pshipton** [comment]
@jdekonin

**Comment by AdamBrousseau** [comment]
Depends #2836

**Comment by AdamBrousseau** [comment]
Hacked up build that Tobi is running internally (job/Tobi_Pipeline-Build-Test-JDK11-linux_x86-64_cmprssptrs_nestmates_internal) uses JDK11 xlinux spec but it could be tested on more versions or platforms. The only change on the compile side is to run a `sed` command on `j9cfg.h.ftl`
see: https://github.com/eclipse/openj9/compare/master...tajila:valuetypesinternal
For the test side `AUTO_DETECT` needs to be disabled and `JDK_VERSION=Valhalla` needs to be set. `BUILD_LIST=functional/Valhalla` as well. The build also uses the old test pipeline that OpenJ9 wrote, not the one from Adopt. We would have to try out the Adopt pipelines and see what needs to be done.
cc @llxia

Not sure where the priority would be on this but if it's going to be needed long term it would be nice to have it as a real option rather than having to hack up the build scripts.

**Comment by tajila** [comment]
Thanks for working on this @AdamBrousseau. Currently, I am running two test commands:

`make BUILD_LIST=functional/Valhalla _sanity` and
`make BUILD_LIST=functional/cmdLineTests/valuetypeddrtests _extended`

But perhaps this can be turned into one command by running `make BUILD_LIST=functional _sanity` and putting all the Valhalla tests in sanity? (@llxia ??)

I think a good long term solution would be to come up with general way to run an experimental build where a `flag` can be provided as a param for the compilation as well as flag for `JDK_VERSION` that will be used when running the tests. This is essentially what my script does. With this approach we wont need to repeat this work any time we start working on a new project.

> Not sure where the priority would be on this but if it's going to be needed long term it would be nice to have it as a real option rather than having to hack up the build scripts.

Agreed, we are starting to get more teams (JIT, GC) working on ValueTypes so it would be nice to have a standard way to run these tests.

**Comment by llxia** [comment]
> But perhaps this can be turned into one command by running make BUILD_LIST=functional _sanity and putting all the Valhalla tests in sanity? (@llxia ??)

yes, we can. But when JDK_VERSION is set to Valhalla, only Valhalla tests will run. If we want to run other tests (non-Valhalla tests) and Valhalla tests together in one build, then more work needs to be done. This reason is that the formal support for JDK_VERSION is a real JDK version (i.e., 8, 11, 13, etc).

On the related note, will Valhalla be merged into main steam? If so, what is the timeframe?

**Comment by tajila** [comment]
> On the related note, will Valhalla be merged into main steam? If so, what is the timeframe?

Its still unclear when this will happen, perhaps within the next year but possibly longer.

**Comment by AdamBrousseau** [comment]
Did we determine or decide if the BUILD_LIST will need to be passed to the test jobs? Or can we just call sanity.functional?

**Comment by llxia** [comment]
Please pass in `BUILD_LIST` for now.

`JDK_VERSION=Valhalla`was initially designed as a temporary solution. It does not have the full feature as real JDK_VERSION. From a brief look, we need to modify build.xml that has if statement.  Not sure if there is other implication. We need to evaluate if this is worth implementing. 
fyi @renfeiw

**Comment by llxia** [comment]
Please note TRSS needs to be updated to handle this as we only expect JDK_VERSION to be a number. I will make the change in TRSS.

**Comment by AdamBrousseau** [comment]
What is the value of build list?
From Tobi's internal build I see the following steps
```
make configure BUILD_LIST=functional/Valhalla
make compile BUILD_LIST=functional/Valhalla
make compile BUILD_LIST=functional/cmdline_options_tester
make compile BUILD_LIST=functional/cmdLineTests/valuetypeddrtests
make _sanity BUILD_LIST=functional/Valhalla

make configure BUILD_LIST=functional/cmdline_options_tester
make configure BUILD_LIST=functional/cmdLineTests/valuetypeddrtests
make compile BUILD_LIST=functional/cmdline_options_tester
make compile BUILD_LIST=functional/cmdLineTests/valuetypeddrtests
make _extended BUILD_LIST=functional/cmdLineTests/valuetypeddrtests
```
Would it be `BUILD_LIST=functional/Valhalla functional/cmdline_options_tester functional/cmdLineTests/valuetypeddrtests`? (space separated or comma).

Currently, we don't pass build_list, we rely on the default value of the test job, which is put there by the test auto gen job. The value comes from Group. Where should we change this? In the test autogen, since the Valhalla tests will be separate. Who would be responsible for the build list? OpenJ9 pipeline side which calls the test auto gen job or test auto gen side? Or would we pass it during the OpenJ9 pipeline build. If we do that then we'll also have to pass it for all the existing tests or else we would override default values to blank. Either that or we could rewrite how we pass test params and only pass params that have values.

**Comment by smlambert** [comment]
Tobi's script could be simplified to this:

export BUILD_LIST=functional/Valhalla,functional/cmdline_options_tester,functional/cmdLineTests/valuetypeddrtests

make compile 
make _sanity 
make _extended

- using a comma-separated BUILD_LIST and TKG no longer needs the configure step

It makes sense to only pass params that have values.

**Comment by AdamBrousseau** [comment]
@tajila can you review my PR build and see if it's working as expected?
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDKnext_x86-64_linux_valhalla/2/

**Comment by tajila** [comment]
@AdamBrousseau the build job looks good, I was able to see the test results, https://ci.eclipse.org/openj9/blue/organizations/jenkins/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Personal/detail/Test_openjdkvalhalla_j9_sanity.functional_x86-64_linux_valhalla_Personal/1/pipeline

The link didnt work for me.

Also, https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/183. After this, only `--enable-inlinetypes` will be required.

**Comment by AdamBrousseau** [comment]
Yea the OpenJ9 Jenkins doesn't have blue ocean views anymore. Here is the classic view
https://ci.eclipse.org/openj9/job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Personal/1/
Note this is just sanity.

I will hold off on the PR until 183 :+1:

**Comment by tajila** [comment]
@AdamBrousseau The PR just got merged, note the option has been changed to `--enable-inline-types`

I also tested out Shelley's suggestion and it works

```
export BUILD_LIST=functional/Valhalla,functional/cmdline_options_tester,functional/cmdLineTests/valuetypeddrtests
make compile 
make _sanity 
make _extended
```

**Comment by llxia** [comment]
TRSS PR: https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/221

**Comment by AdamBrousseau** [comment]
Can this be closed then?

**Comment by tajila** [comment]
Yes, thanks for working on this

**Comment by llxia** [comment]
Internal TRSS: http://testci1.fyre.ibm.com/resultSummary?parentId=5e82971de2c3171da209f59f
