### ISSUE TITLE
Link to DockerFile on build instruction page is broken

### ISSUE THREAD

**Issue by r30shah** [eclipse/openj9#5]
Link for DockerFile on [build instruction page](https://www.eclipse.org/openj9/oj9_build.html) is broken for Linux on z Systems. It points to https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk9/390_64/ubuntu16/Dockerfile but it should be https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk9/s390x/ubuntu16/Dockerfile.

**Comment by mstoodle** [comment]
Because it has to do with the web site content, this issue should properly be opened against the web site (www.github.com/eclipse/openj9-website), and (luckily :) ) is already there: https://github.com/eclipse/openj9-website/issues/1 . I'm going to close this one, but you can track the progress at the linked issue.

Thanks for reporting the problem @r30shah !
