### ISSUE TITLE
JDK12: java.vm.vendor getting overridden by java.vendor

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#5002]
AdoptOpenJDK JDK12 testing is failing as the java.vm.vendor is getting set to "AdoptOpenJDK" due to the following code:
https://github.com/eclipse/openj9/blob/7eff4df230a4331e4f1d1b5ca3bd7f9d8483af64/jcl/src/java.base/share/classes/java/lang/System.java#L403

Adopt build scripts configure java.vendor.

**Comment by JasonFengJ9** [comment]
Looking at it.

**Comment by JasonFengJ9** [comment]
From [make/autoconf/spec.gmk](https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/565a9bd3b8b2d211292441f66367aebab6457d74/make/autoconf/spec.gmk.in#L225-L236)
<pre>
  # COMPANY_NAME is set to "N/A" in $AUTOCONF_DIR/version-numbers by default,
  # but can be customized with the '--with-vendor-name' configure option.
  # Only export "VENDOR" to the build if COMPANY_NAME contains a real value.
  # Otherwise the default value for <b>VENDOR</b>, which <b>is used to set the "java.vendor"</b>
  # <b>and "java.vm.vendor" properties</b> is hard-coded into the source code (i.e. in
  # VersionProps.java.template in the jdk for "vm.vendor" and
  # vm_version.cpp in the VM for "java.vm.vendor")
  ifneq ($(COMPANY_NAME), N/A)
    VERSION_CFLAGS += -DVENDOR='"$(COMPANY_NAME)"'
endif
</pre>

It is straightforward that `java.vm.vendor` should be `Eclipse OpenJ9`. 
The interesting question here is that who is `java.vendor` when `AdoptOpenJDK` builds the JDK, are we going to differentiate `java.vm.vendor` and `java.vendor`?

fyi: @DanHeidinga

**Comment by pshipton** [comment]
FYI
https://github.com/AdoptOpenJDK/openjdk-build/issues/935
https://github.com/AdoptOpenJDK/openjdk-build/issues/942

Adopt will set the java.vendor to something like "AdoptOpenJDK", and this is consistent with what other variants of OpenJDK are doing. java.vm.vendor should remain as "Eclipse OpenJ9". Please create a PR with the necessary changes.

This will also need to be fixed to use java.vm.vendor
https://github.com/eclipse/openj9/blob/bd0a4839cccedb3bc28716c6e67a67333ac983e2/test/functional/Java8andUp/src/org/openj9/test/support/Support_Exec.java#L143
