### ISSUE TITLE
JITaaS in remote AOT mode doesn't disable unsupported optimizations

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#5016]
Unsupported optimizations are disabled in `J9::Options::fePostProcessJIT`.
However, when run in AOT mode, they are re-enabled somewhere.
I observed that this can lead to crashes, for example, when server tries to use Known Object Table.
Since options specified on command line work as expected,
I suspect that the problem is due to option processing of `-Xaot` command line options.
We probably override disabled options sometime during processing of AOT options.

**Comment by a7ehuo** [comment]
@dmitry-ten @mpirvu I'll take a look at this one.

**Comment by a7ehuo** [comment]
The root cause of this issue is: although `TR_DisableKnownObjectTable` is set true for jitaas in `J9::Options::fePostProcessJIT`, the option is not the one that's used for the compilation request. A new option object is created for each compilation in `TR::CompilationInfoPerThreadBase::wrappedCompile()`. https://github.com/eclipse/openj9/blob/af8eeaa5638bcf67f812da613f5023bc300aa09d/runtime/compiler/control/CompilationThread.cpp#L7669.
