### ISSUE TITLE
jps output include the jps process itself

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#5039]
`jps` (both the reference and, for compatibility, OpenJ9 implementations) includes itself in the output:

> $ jps -l
> 24797 looper
> 24878 sun.tools.jps.Jps

This can be a problem if the output is piped into another tool such as `jstack`.

Suggest adding an option `-e` to exclude the current jps process from the output.

**Comment by DanHeidinga** [comment]
I think we should be looking to match the RI on these tools rather than adding new and potentially incompatible options.

> This can be a problem if the output is piped into another tool such as jstack.

The concern being that the jps tool will have excited before jstack is run on it?  That seems to be a general problem with the jps and actually, all tools that process `ps` style output - namely that the process being inspected may have died between getting the pid and doing the next thing,

I'm going to close this for now - please reopen if you disagree and we can discuss further.
