### ISSUE TITLE
Reduce the number of connections between JITaaS client and server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5289]
In the current implementation the JITaaS client establishes a new connection to the server for each compilation request. This adds unneeded overhead especially when encryption is enabled because SSL handshake is expensive.
One idea is to keep the connection open as long as the compilation thread at the client has something in the compilation queue.

**Comment by harryyu1994** [comment]
Looking into this one.

**Comment by harryyu1994** [comment]
One way to implement this:
`TR::CompilationInfoPerThread::processEntries()` is where each compilation thread on the client processes the compilation queue. We should open a connection here and maintain it as long as the compilation thread is in the  `while (getCompilationThreadState()==COMPTHREAD_ACTIVE)` loop. When we get out of the loop, it means there are no more work on the thread, so we close the connection.

**Comment by mpirvu** [comment]
That's the idea. I believe this will require changes to the infrastructure though.

**Comment by harryyu1994** [comment]
Infrastructure Changes:
Server side:
- `TR::CompilationInfoPerThreadRemote::processEntry` handles each entry/compilation on the server
- In this function, instead of recycling `entry` & deleting `entry->_stream` after the compilation, we should keep the same `entry->_stream` and put `entry` right back in the queue.
Client Side:
- Maintain only 1 connection per compilation thread.

Then when server fails to read from `entry->_stream` in `TR::CompilationInfoPerThreadRemote::processEntry` it means that the connection is gone and that's when we clean up `entry` & `entry->_stream`

**Comment by harryyu1994** [comment]
@mpirvu So after fixing a couple of corner cases, now this "simple" approach can run `-XX:JITaaSClient -version` without any issues. Will perform further testing tomorrow but it seems like it's working. No infrastructure changes required.

**Comment by mpirvu** [comment]
Great! I am eager to know the testing results

**Comment by harryyu1994** [comment]
28% improvement in cpu time for SSL.
