### ISSUE TITLE
Increased number of client-server messages in JITaaS when using AOT cold runs

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5464]
While running AcmeAir with JITaaS and AOT I observed that the frequency of some messages has increased substantially. Examples:
```
#0217  486665 VM_getClassFromSignature
#0286  487246 VM_getClassFromMethodBlock
#0304  276422 VM_getClassFromCP
#0601  267030 SharedCache_rememberClass
```
Without AOT, no message exceeds 100K.

**Comment by mpirvu** [comment]
@satbir-ca  Satbir, as discussed, please look into this issue.

**Comment by satbir-ca** [comment]
All of these call are increased after enabling the SVM

VM_getClassFromSignature —> caching is missing
Solution : enabling the caching.

VM_getClassFromMethodBlock —> call to this has increased due to being called inside the J9SharedCacheServerVM also. In non AOT the this was getting called only from outside the J9ServerVm class.

Solution: putting the cache for this or combining this message with the other message send from the  J9SharedCacheServerVM.

VM_getClassFromCP : Call to this has increased due to SVM.
Solution : Still To debug further.

SharedCache_rememberClass : New calls introduce on server due to AOT.
Solution: cache the class.

**Comment by mpirvu** [comment]
VM_getClassFromSignature: agreed. I think that the existing cache should work, but you have to remember to perform the validation.

VM_getClassFromMethodBlock: maybe we can extend  `PersistentUnorderedMap<J9Method*, J9MethodInfo> _J9MethodMap;`  to hold the j9class as well
Note that this looks identical to ::getClassOfMethod

VM_getClassFromCP: we could add a CP->j9class cache, but we need to invalidate the entries when classes get unloaded.

SharedCache_rememberClass: this method returns classChains. We could use a cache if we can guarantee than an existing classChain cannot disappear.
