### ISSUE TITLE
JITaaS client performance should not drop when server crashes

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5503]
If the JITaaS server happens to crash, the client still has the option to perform JIT compilations locally and (provided there is enough memory) there should be no observable drop in throughput.

**Comment by harryyu1994** [comment]
Taking this work on the side

**Comment by harryyu1994** [comment]
First plan I had was to put the client-server connection establish process inside `preCompilationTask` since that is where the decision of whether to do remote compilation or local compilation is done. If the decision is to do a remote compilation but the connection was failed due to server not available, we can change the decision to do a local compilation. We would do this check for every single compilation in case the server become available again. I relied on the connection throwing exceptions when it fails, but it turns out that exceptions are too expensive when the server doesn't come back on for a long time.

**Comment by harryyu1994** [comment]
Second plan is to use this check instead of relying on the `open_connection()` call to throw/catch `StreamFailure` exceptions.
