### ISSUE TITLE
JVMTI agent is unable to get Java version in native code on OpenJ9 JDK 12

### ISSUE THREAD

**Issue by AntonKatilin** [eclipse/openj9#5565]
We use JVMTI's GetSystemProperty function to get Java version as a number like 8, 9, 10, 11, 12 etc. in native code, in an early phase when no Java code has loaded yet. Since OpenJ9 Java 12 this approach no longer works.

Property "java.vm.version" on HotSpot returns something like "12.0.1+12" which we can parse to get the version. OpenJ9 returns "openj9-0.14.0" which is useless for our purpose because it indicates the entire release with different Java versions like Java 11, Java 12 etc.

Property "java.vm.specification.version" returns "11" on OpenJ9 Java 11, and we can parse it. Unfortunately, OpenJ9 Java 12 returns an empty string.

Neither can we use JVMTI's GetVersionNumber function because for Java 11 and Java 12  it returns the same value JVMTI_VERSION_11 = 300B0000.

Could you please make "java.vm.specification.version" return a meaningful value ("12"), or suggest a workaround.

**Comment by DanHeidinga** [comment]
This was changed in https://github.com/eclipse/openj9/commit/7e3036dc1b7203aaabe07305516766596a73d591

Likely due to VersionProps.init not setting `java.vm.specification.version`.  

Looks like we need to reorganize the property setting code a bit

**Comment by JasonFengJ9** [comment]
Will have a look this.

**Comment by AntonKatilin** [comment]
This bug was in JDK 12, and is labelled as fixed in 0.14.2. However, it seems there is no JDK 12 build 0.14.2 or newer available, there is only 0.14.2 for JDK 8 and 0.14.3 for JDK 11. Should we wait for upcoming 0.14.x release for JDK 12 with this bug fixed, or will its fix in a release (not in a nightly build) be actually postponed until 0.15?

**Comment by pshipton** [comment]
@AntonKatilin while technically the problem is fixed in the OpenJ9 0.14.2 branch (and also for 0.15), we decided against building a Java 12 release for 0.14.x at AdoptOpenJDK, since it is a short term support release, and to save on people resources. We're not planning any new release build at Adopt for Java 12 before 0.15. The nightly builds are available with the fix.

One option if you want to discuss it, there is an OpenJ9 community call at 11am EDT every Wed, details in the [#planning](https://openj9.slack.com/messages/C8RBG6N2W) channel on the OpenJ9 Slack.
