### ISSUE TITLE
Modifying enums at runtime - IllegalArgumentException

### ISSUE THREAD

**Issue by clienthax** [eclipse/openj9#5577]
Modifying a Enum via reflection at runtime and then attempting to access the modified enum will result in a IllegalArgumentException, the same code works correctly on OpenJDK standard / Oracle

It also seems that this only applies to the second inserted enum, the first one goes through fine with no error.
It seems that the enumConstantDirectory/enumConstants were moved into enumvars which can be workarounded with the following.
```
        blankField(enumClass, "enumVars");
```

Testcase:
[Test.zip](https://github.com/eclipse/openj9/files/3104864/Test.zip)

Output:
```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant TestEnum.THREE
	at java.lang.Enum.valueOf(Enum.java:238)
	at Test.main(Test.java:16)```

```
Version:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b03)
Eclipse OpenJ9 VM (build openj9-0.14.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20190417_339 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5590c4f818 based on jdk8u212-b03)
```

**Comment by DanHeidinga** [comment]
> It seems that the enumConstantDirectory/enumConstants were moved into enumvars which can be workarounded with the following.
> 
> ```
>         blankField(enumClass, "enumVars");
> ```

OpenJ9 replaces a small number of VM-specific classes such as java.lang.Class, Thread, String, etc.  These are classes that the VM knows a lot about to enable the VM to operate. 

Code that uses reflection to both access internal, implementation-specific fields and then removes the final modifier is operating pretty far outside the lines of expected behaviour.

Just as your example code had to know about the enum caches in OpenJDK, it'll also have to be aware of the `enumVars` cache in OpenJ9.  

I don't see us modifying OpenJ9's enum cache implementation to be identical to OpenJDKs.
