### ISSUE TITLE
 Add support for musl libc

### ISSUE THREAD

**Issue by bharathappali** [eclipse/openj9#5658]
As OpenJ9 is built on top of OMR technology, I'm raising this issue to have OpenJ9 to work with musl libc as OMR also started to implement [musl support](https://github.com/eclipse/omr/issues/3774)

FYI - @dinogun @ashu-mehra @charliegracie

**Comment by sxa** [comment]
@bharathappali @dinogun What's the current state of this? Will it build on Alpine? Is there a plan to e.g. make musl builds of OpenJ9 available?

**Comment by avermeer** [comment]
Hello,

[JEP 386: Alpine Linux Port](https://openjdk.java.net/jeps/386) is part of Java 16 specifications, so I'm wondering why OpenJ9 Java 16 implementation seems to be missing that target.

OpenJ9's home site claim it to be a JVM with smaller footprint than HotSpot and with faster startup time, but missing official Alpine Linux support means that OpenJ9 usage in Docker world is limited to "big operating systems", unless you use some un-official OpenJ9 ports on Alpine, like https://gitlab.alpinelinux.org/alpine/aports/-/issues/12118  (but this site has up to Java 15 version of OpenJ9, Java 16 version is not available)

Are OpenJ9 developers not interested in Alpine Linux official support, leaving some other community to patch/fork to provide Alpine support?

Kind regards,
Alexandre

**Comment by pshipton** [comment]
While the OpenJ9 (and OMR) projects are open to reviewing contributions that add support for musl/Alpine, I'm not aware of any recent efforts by committers or non-committers to make such contributions. Afaik there are no active plans for OpenJ9 to support JEP 386 in Java 16 or future releases. It appears there was an effort a couple years back to start porting OMR to musl but it was abandoned by the contributor, https://github.com/eclipse/omr/issues/3774.

If there was such an effort, the OpenJ9/OMR project would be looking for machine contributions in order to run builds and tests on the platform.

The links to builds in https://gitlab.alpinelinux.org/alpine/aports/-/issues/12118 appear just the regular builds which afaik don't include Alpine Linux. You can substitute 16 for 15 in the link and find the regular 16 builds as well.

I wouldn't say that Alpine Linux is part of the Java 16 specification, there is no requirement to support particular platforms in the Java specifications. Rather the OpenJDK project did a port to Alpine Linux and it was ready for Java 16.

I would hope that if some other community did create OpenJ9/OMR patches to support Alpine Linux they would work with the OpenJ9/OMR projects to contribute them back rather than trying to maintain a fork.

**Comment by pshipton** [comment]
As this is not active, I will close it.
