### ISSUE TITLE
attribute mismatch asserts in j9methodServer.cpp in debug build

### ISSUE THREAD

**Issue by caohaley** [eclipse/openj9#5841]
The following asserts comes up with JITaaS debug build, regarding to mismatched client and cache data.  The second asserts comes up when the first assert is commented out and reran. May be indicative of existing bugs:

```
Assertion failed at ../compiler/env/j9methodServer.cpp:144: validateMethodFieldAttributes(attributes, isStatic, cpIndex, isStore, needAOTValidation)
VMState: 0x00050080
	static attributes from client and cache do not match
```
```
Assertion failed at ../compiler/env/j9methodServer.cpp:523: validated
VMState: 0x000501ff
        field attributes from client and cache do not match
```

**Comment by caohaley** [comment]
@ymanton  @mpirvu could you add the ```JitaaS``` tag to this? Is this issue okay or should I make some changes to the wording of anything?

**Comment by dmitry-ten** [comment]
Since I worked on this code, I'll look into it. Does it fail consistently for a particular test?

**Comment by caohaley** [comment]
I ran it last night again and it seems to happen in jit_vich_0 test, where the server hits the assert while client is running the jit_vich_0 test. However, when you run the test just by itself the assert doesn't come up for me. To see the assert, I think make _sanity has to be run.

**Comment by dmitry-ten** [comment]
This just means that the assert being triggered is an intermittent event, so might have to run the same test multiple times. Too bad, I hoped at least one of the tests would consistently trigger it.

**Comment by dmitry-ten** [comment]
Ok, I was able to reproduce this assert by running the test a couple of times.
It happens when we cache an unresolved field in a per-resolved method cache, and later we attempt to validate a cached result against the one just fetched from the client, but the client has already resolved the field, so the attributes do not match.
We have previously decided that validation should not be done against attributes cached per-resolved method, since that cache will exist for the duration of one compilation, so even if attribute gets resolved during compilation, we'll fetch an update soon.
We already skip validation for this case in `fieldAttributes`, but I forgot to skip it for `staticAttributes` and AOT versions of these methods.
The fix should be easy: modify `validateMethodFieldAttributes` to return true if cached attribute is unresolved. 
I can do it myself, or @caohaley can do it, if she wants.

**Comment by caohaley** [comment]
Sure! I will add it in.
