### ISSUE TITLE
Support for Truffle API

### ISSUE THREAD

**Issue by brauliobo** [eclipse/openj9#59]
Does OpenJ9 has support for the Truffle API?

**Comment by mstoodle** [comment]
Well, we haven't tried it. I suppose Truffle might work, since I think it's "just" Java code (no disrespect intended by that; I just mean that OpenJ9 should be able to run pure Java code :) ).

But my guess is that Truffle on OpenJ9 probably won't perform well because OpenJ9 doesn't implement the (optional :) ) JVMCI specification written for Graal, Hotspot, and, I think, the Maxime VM. That means the usual Truffle optimizing down to Graal for native code performance path won't work because it won't know how to cooperate with the OpenJ9 VM rather than HotSpot. As I understand it, implementing JVMCI for OpenJ9 would involve work on both sides of the API and it's not work we currently plan to do (though we would be happy to consider contributions that do so; it's just probably not a "starter" kind of task :) ).

Is that the kind of answer you were looking for, or is there another angle I should be addressing?

**Comment by brauliobo** [comment]
yes, that is what I expected to hear. Hopefully JVMCI will be implemented sooner than later :)

**Comment by sirinath** [comment]
As people start using mixed language development on Truffle* languages with Java the need to support this will become more. Before things go too far it might be an idea to collaborate with OpenJDK / Oracle so that JVMCI / JEP 243 evolves to something that can be implemented on top of OpenJ9 as well.

**Comment by sirinath** [comment]
What would be needed to support Graal / JVMCI on OpenJ9 is to replace the HotSpot specific API within Graal (http://lafo.ssw.uni-linz.ac.at/javadoc/graalvm/all/index.html?jdk/internal/jvmci/hotspot/package-summary.html) with OpenJ9 specific API.

Maybe some generalisation of the code also can be done and up-streamed so Graal / JVMCI on OpenJ9 would be more maintainable.
