### ISSUE TITLE
Track reason for "JITaaS I/O error: reading message size"

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6133]
While running sanity tests on fyre machine I see too many messages on the server saying:
```
JITaaS: Stream failed while compThreadID=1 was reading the compilation request: JITaaS I/O error: reading message size
```
We need to introduce stats about these, understand the cause and determine how serious it is.

**Comment by dmitry-ten** [comment]
I'll look into this.

**Comment by dmitry-ten** [comment]
The error message doesn't appear if every compilation creates a new stream.
With one stream used for multiple compilations what happens is that once a current compilation is done, server puts the entry for method to be compiled back into the compilation queue with `TR::CompilationInfo::requeueOutOfProcessEntry`, so that server takes that entry and blocks in `read`, until a new compilation request is received from the same stream.
But for some reason, `read` sometimes thinks there is some data on the socket when there is none, and attempts to read a compilation request. This results in the above error message. Once stream fails, it is destroyed and recreated the next time a compilation is scheduled on this thread, so it shouldn't be causing any functional issues.
However, I still do not understand why protobuf attempts to read some invalid data, and will need to investigate more.

**Comment by dmitry-ten** [comment]
Just figured out the true reason for these messages: this error appears whenever client destroys a stream that is still connected to a server stream. This happens either when all of the entries in a compilation queue get processed, or when JVM exits. Which accounts for all of the occurrences of this message. 
So, this is not actually a bug, just a weird way for server to learn that a corresponding client stream has been closed.

**Comment by harryyu1994** [comment]
With my latest version checking change, now server and client both have message types, which means we can actually look at how the message client send to server:
```
#JITaaS: Stream failed while compThreadID=1 was reading the compilation request: JITaaS I/O error: reading message size 245
#JITaaS: compThreadID=1 did an early abort
```
```
#JITaaS: compThreadID=1 has successfully compiled java/lang/Thread.start()V
#JITaaS: Stream failed while compThreadID=1 was reading the compilation request: JITaaS I/O error: reading message size 109
```
109: ResolvedMethod_startAddressForJNIMethod
245: VM_getClassFromNewArrayType
222: VM_classHasBeenExtended
A couple of them. So these aren't just random messages, unless those values are leftover from previous reads.

**Comment by harryyu1994** [comment]
> Just figured out the true reason for these messages: this error appears whenever client destroys a stream that is still connected to a server stream. This happens either when all of the entries in a compilation queue get processed, or when JVM exits. Which accounts for all of the occurrences of this message.
> So, this is not actually a bug, just a weird way for server to learn that a corresponding client stream has been closed.

We can add in a change where client informs server that it is closing the connection to fix this, but the priority of this should be minor.
