### ISSUE TITLE
Question: Are static object barriers required for setting J9Module object fields

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#6214]
In java11vmi.c:

```
		if (NULL != j9mod->readAccessHashTable) {
			j9mod->classLoader = classLoader;
			/* The GC is expected to update pointer below if it moves the object */
			j9mod->moduleObject = moduleObject;

			/* Bind J9Module and module object via the hidden field */
			J9OBJECT_ADDRESS_STORE(currentThread, moduleObject, vm->modulePointerOffset, j9mod);

			retval = j9mod;
		}
```

Do we need to use `J9STATIC_OBJECT_STORE` when assigning `moduleObject` to `j9mod->moduleObject` ?

Similar question for `j9mod->moduleName = moduleName;` and  `fromModule->version = J9_JNI_UNWRAP_REFERENCE(version);`

**Comment by tajila** [comment]
@amicic @JasonFengJ9 ^^^

**Comment by JasonFengJ9** [comment]
This could be the cause of `Segmentation error vmState=0x0002000f` discovered in an internal test if GC indeed moved `moduleObject` without updating `j9mod->moduleObject`.

**Comment by amicic** [comment]
Yes, they are required.

**Comment by amicic** [comment]
Let me elaborate a little....

Everything that is not hard root (initial set of object references that determine live object graph/set), in general, will requires object access barrier. I'm not going to elaborate why (depends somewhat on stay of GC).

Hard roots as minimum are Thread slots and Thread stack slots.

Classes are generally not hard roots. Their own liveness is determined by existence of (or lack of ) its instances - we cannot at the start of GC say that a class should stick around, but only at the end of a GC.

They are also another node in object graph that determines what else is also alive (if they continue to live). While only class object is in the heap and have direct object references back to the heap, logically all object references in class structures (statics, module etc) belong to this object and in the same way contribute to object graph shape.

For any change of object graph shape, while GC is in progress, GC has to be notified, otherwise it may miss to identify an object (or a whole subgraph retained by that object).   Writes to object references change the object graph shape and need to notify through store barrier. We have 2 style of Concurrent Mark GCs that rely on store barriers.

Some more sophisticated GCs may also require _load_ object reference barrier. Again, like store barriers, there are not needed on the roots, but (confusingly) for our only GC ATM that rely on them (Concurrent Scavenger) static slots of class are actually treated as roots (still most of other slots in class are not roots). So we right now don't need load barrier for any class slot (in fact for any non-heap reference object slot), but it may change in future....

Some other more sophisticated GCs may also require store and load barriers on _primitive_ fields. We don't have any such GC yet, around, but one can see that such barrier APIs exist and are used throughout the code.

For non-heap reference loads and primitive store/loads, it's not a big concern if we miss to use barriers, but ideally, it should be also good to use them, especially if the part of the code  being modified, already comply with them, so we stay consistent.
