### ISSUE TITLE
sanity.openjdk: java/net/URL/JarHandlerPkgPrefix/JarHandlerPkgPrefix.java failure

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#6466]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/6/testReport/java_net_URL_JarHandlerPkgPrefix_JarHandlerPkgPrefix/java/JarHandlerPkgPrefix/

Public link to the failing test.
If the link is not public, instead include 
- test category (functionality, system, etc): openjdk
- test suite name: jdk_net
- OS/architecture (i.e. Ubuntu 16.04 x64): all 
- public build SHAs (i.e. -version output): 
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+10-201907151810)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-9409a4266, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190715_287 (JIT enabled, AOT enabled)
OpenJ9   - 9409a4266
OMR      - 4beca561
JCL      - 411f32dbbb based on jdk-11.0.4+10)

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
last passing with this version:
21:09:15  "/Users/jenkins/workspace/openjdk11_j9_openjdktest_x86-64_macos/openjdkbinary/j2sdk-image/bin/java" -version
21:09:15  openjdk version "11.0.4" 2019-07-16
21:09:15  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+10)
21:09:15  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.0-m1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190704_276 (JIT enabled, AOT enabled)
21:09:15  OpenJ9   - 655fac772
21:09:15  OMR      - dc661ac3
21:09:15  JCL      - ab99c6f8d4 based on jdk-11.0.4+10)

Passes on hotspot.

Failure output
--------------

22:20:51  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: jar: URL handler not invoked
22:20:51  REASON: User specified action: run main/othervm -Djava.protocol.handler.pkgs=handlers JarHandlerPkgPrefix 
22:20:51  TIME:   1.254 seconds
22:20:51  messages:
22:20:51  command: main -Djava.protocol.handler.pkgs=handlers JarHandlerPkgPrefix
22:20:51  reason: User specified action: run main/othervm -Djava.protocol.handler.pkgs=handlers JarHandlerPkgPrefix 
22:20:51  Mode: othervm [/othervm specified]
22:20:51  elapsed time (seconds): 1.254
22:20:51  configuration:
22:20:51  STDOUT:
22:20:51  STDERR:
22:20:51  java.lang.AssertionError: jar: URL handler not invoked
22:20:51  	at JarHandlerPkgPrefix.main(JarHandlerPkgPrefix.java:59)
22:20:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:20:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:20:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:20:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:20:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:20:51  	at java.base/java.lang.Thread.run(Thread.java:831)
22:20:51  
22:20:51  JavaTest Message: Test threw exception: java.lang.AssertionError: jar: URL handler not invoked
22:20:51  JavaTest Message: shutting down test

**Comment by theresa-m** [comment]
This error goes away when I locally revert https://github.com/eclipse/openj9/pull/6271 (enable scc by default).

@hangshao0 any ideas for what could cause this?

**Comment by hangshao0** [comment]
Just from the error message, it is not clear to me why SCC would cause this issue. The class loaded from the SCC should not be different from the class loaded from the disk.  

You can trying using `-Xshareclasses:bootClassesOnly,verboseIO,verbose` which is equivalent to enabling default SCC but with some verbose output telling you what is loaded from the SCC.

**Comment by hangshao0** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java#L241toL255
The comment says return whether -Xshareclasses is used in the CML. 

So this line should also check if J9SHR_RUNTIMEFLAG_ENABLE_CACHE_NON_BOOT_CLASSES is set at javaVM->sharedClassConfig->runtimeFlags
https://github.com/eclipse/openj9/blob/master/runtime/jcl/common/system.c#L258

Adding the missing check might solve this issue.

**Comment by theresa-m** [comment]
thanks I'll give it a try

**Comment by theresa-m** [comment]
thanks @hangshao0 adding that check has fixed it. just going to run some more tests before opening a pr..

**Comment by theresa-m** [comment]
after talking more with @hangshao0 this is not the right answer to the problem so the investigation is back on. The issue is that the test fails whenever there is a JAR included in the classpath, javatest.jar in this case. It is not related to that particular jar file, I can put in a dummy name of a nonexistent *.jar file and the same behavior occurs.

What I know so far..

The test command includes setting `java.protocol.handler.pkgs` on the command line with `-Djava.protocol.handler.pkgs=handlers JarHandlerPkgPrefix`

The test fails because the package set in this command line option is never searched for java.net.URL protocol handlers and handlers.jar.Handle is needed for the test to pass.

The handler for the protocol "jar" is set prior to the VM being fully booted. Since this check will be false command line options will not be searched: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/java/net/URL.java#L1390

If I remove all jar files from the classpath the handler for the "jar" protocol is created while the test application is running and VM is fully booted.

Still trying to figure out why the handle for the "jar" prototype is being set so early.

**Comment by theresa-m** [comment]
Providers should not be being initialized in https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java#L205 but currently are because BuiltinClassLoader:isSharedClassesEnabled is wrongly returning true when application shared classes are not enabled.
