### ISSUE TITLE
JDK10 build failure handling -classpath paths

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#655]
Building with JDK10 the following command fails due to the native canonicalization of the -cp path. If the command is repeated with the classpath terminated with a "/" it works (ie.".../tools_jigsaw_classes/"). From debugging it seems the Java_java_io_UnixFileSystem_canonicalize0 native method returns an invalid path, seemingly with the macro WITH_PLATFORM_STRING(env, pathname, path) failing. Maybe encoding related?
```
admin@leo01:~/mydocker/ccm/jdk18.3$ /home/admin/mydocker/ccm/jdk18.3/build/linux-x86_64-normal-server-release/jdk/bin/java -Dsun.misc.URLClassPath.debug=true -Xms64M -Xmx1600M -XX:ThreadStackSize=1536 -XX:+UseSerialGC -Xms32M -Xmx512M -XX:TieredStopAtLevel=1 -cp /home/admin/mydocker/ccm/jdk18.3/build/linux-x86_64-normal-server-release/buildtools/tools_jigsaw_classes --add-exports java.base/jdk.internal.module=ALL-UNNAMED build.tools.jigsaw.AddPackagesAttribute /home/admin/mydocker/ccm/jdk18.3/build/linux-x86_64-normal-server-release/jdk
URLClassPath.getResource("build/tools/jigsaw/AddPackagesAttribute.class")
Error: Could not find or load main class build.tools.jigsaw.AddPackagesAttribute
Caused by: java.lang.ClassNotFoundException: build.tools.jigsaw.AddPackagesAttribute
```

**Comment by JasonFengJ9** [comment]
The failure is related to a field `coder` added within `java/lang/String` for `Java 10`. The `classpath` is passed to VM via `-Djava.class.path=`, and assigned to a system property as a `java/lang/String` object which is created by `stringhelpers.cpp:j9gc_createJavaLangString()`. However this string helper method doesn't set the string object field `coder` hence default value `0` is used which means a compressed string (however not enabled yet) while `1` means un-compressed `UTF16` (current coding). This incorrect `coder` value caused the string is not usable.

At this moment, not sure why the extra `/` makes difference, I suspect the string has to invoke the constructor due to this addition hence set `coder` properly.

**Comment by andrew-m-leonard** [comment]
Kudos! Great debugging Jason
