### ISSUE TITLE
Fold runtime/compiler/trj9 directory

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#667]
Now that `tr.source` has been renamed to `compiler` as part of https://github.com/eclipse/openj9/pull/589 I wanted to start a discussion on possibly folding the `trj9` directory as well. To me it currently serves no purpose as its parent `compiler` directory is completely empty.

@0xdaryl notes down some thoughts in https://github.com/eclipse/openj9/issues/550#issuecomment-344695397 which may possibly cause problems. I think the only way to find out would be to implement the change and see what fails.

Before we go down this road, do people even support this idea? Do we have internal or external dependencies on this? As I understand the compiler makefile currently resides in the `trj9` directory. Moving it one level up is sure to break _something_? What is this _something_? Any ideas, comments, or concerns are welcome.

**Comment by mstoodle** [comment]
Thanks for continuing to push along this line, @fjeremic. I think you're evolving the structure of the code towards a better place. I was never happy with t`r.source`, for example :) .

After this change, the openj9 `compiler` directory will have precisely the same structure as the omr `compiler` directory, right?

I *think* that will be ok so long as every header file is consistently smurfed by its project name (which admittedly feels redundant, but I think we're already in this world) so that it can be specifically referenced by another file's #include file directive. Without the smurfing, there may not be a way to distinguish an OMR file from an OpenJ9 file in, say, `#include "codegen/TheIncludeFile.hpp"`.

That #include will *always* find `openj9/runtime/compiler/codegen/TheIncludeFile.hpp` (because it will be earlier on the `IPATH`) and will never find, say,`omr/compiler/codegen/TheIncludeFile.hpp`. That's ok if openj9 only needs to override `TheIncludeFile.hpp` but fails with great sadness if the openj9 version of that file wants to build upon what's in the omr version.

That problem can also be solved by bringing more of the openj9 path into the #include directive (e.g. `#include "omr/compiler/codegen/TheIncludeFile.hpp"` with `omr`'s parent directory on the `IPATH`), but you lose the flexibility to introduce architecture specialization because you must include the full path.

Will continue to ponder...

**Comment by fjeremic** [comment]
> After this change, the openj9 compiler directory will have precisely the same structure as the omr compiler directory, right?

That's correct. This is the intent to ease consumability of the project by flattening and mimicking OMRs structure.



> I think that will be ok so long as every header file is consistently smurfed by its project name (which admittedly feels redundant, but I think we're already in this world) so that it can be specifically referenced by another file's #include file directive. Without the smurfing, there may not be a way to distinguish an OMR file from an OpenJ9 file in, say, #include "codegen/TheIncludeFile.hpp".

IIRC we do something like this already where pretty much all OpenJ9 includes have `trj9/` in them. What you mean by the above is that now we will have to have `runtime/compiler/` instead, if `trj9` gets folded away?

**Comment by mstoodle** [comment]
i think so, unless the header file names are/get smurfed by project/directory (e.g. `OMRTheIncludeFile.hpp` and `J9TheHeaderFile.hpp`) so that the IPATH doesn't sabotage finding the right header file when you *really* want to `#include "codegen/OMRTheIncludeFile.hpp"` .

In most cases where this matters, I would guess we've already smurfed the file names. Outside of extensible classes, I don't think it's as common to reuse header file names across directories/projects (especially where you want a header file named X.hpp to include another header file named X.hpp from some other directory :) ).

**Comment by mstoodle** [comment]
@0xdaryl can you think of any additional scary corner cases to be wary of here?

**Comment by DanHeidinga** [comment]
@fjeremic Any interest in pursuing this?  Otherwise, can you close the issue for now?

**Comment by fjeremic** [comment]
> @fjeremic Any interest in pursuing this? Otherwise, can you close the issue for now?

Yes I do still plan on doing this. We can close this issue and I can reopen it once I'm back in this area?

**Comment by 0xdaryl** [comment]
I don't think dormancy should be the primary criteria for closing an issue because this is still work needed to be done or investigated.  I would suggest creating a "backlog" or "icebox" label for issues such as this that are still valid yet currently have no resources available to complete them.  Perhaps a topic for discussion at the next OpenJ9 hangout.

**Comment by DanHeidinga** [comment]
@0xdaryl I don't want to divert from the purpose of this item but I do want to point out that we've already discussed this on OpenJ9 hangouts - the first one in fact - and came to the agreement that:


> Agreement to close items more quickly.  There’s been a tendency to let items sit but if no one is actively looking at them, it is easy to be overwhelmed by old items.
https://docs.google.com/document/d/1G0fXbVWEmM5fBCTtCbK_4TlsO16Juc9RfepLy_UzPPM/edit?usp=sharing

**Comment by DanHeidinga** [comment]
> Yes I do still plan on doing this. We can close this issue and I can reopen it once I'm back in this area?

Thanks @fjeremic.  I'll close this now then and it can be reopened when we're ready to look at it again.

**Comment by fjeremic** [comment]
Continuing work on this today.
