### ISSUE TITLE
 java.util.concurrent.ConcurrentHashMap memory problem 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6697]
Hi,
when i use java , run spring boot application,  run commnad like this:
jps -l

jmap -histo:live pid

console log like this:

   1:         57214        5670408  [C
   2:          4663        2260616  [B
   3:         42466        1358912  java.util.concurrent.ConcurrentHashMap$Node
   4:         56208        1348992  java.lang.String
   5:         11259        1245808  java.lang.Class
   6:         18533         741320  java.util.LinkedHashMap$Entry
   7:          8014         705232  java.lang.reflect.Method
   8:          5506         641128  [I
   9:         10073         596560  [Ljava.lang.Object;
  10:          7864         545680  [Ljava.util.HashMap$Node;
  11:          9730         544880  java.util.LinkedHashMap
  12:           313         523472  [Ljava.util.concurrent.ConcurrentHashMap$Node;
  13:         27250         436000  java.lang.Object
  14:          8961         286752  java.util.HashMap$Node
  15:          3285         152728  [Ljava.lang.String;
  16:          1540         147840  org.springframework.beans.GenericTypeAwarePropertyDescriptor
  17:           101         141416  [Ljava.nio.ByteBuffer;
  18:          3516         140640  java.lang.ref.SoftReference
  19:          4337         138784  java.lang.ref.WeakReference
  20:          3864         123648  java.util.LinkedList
  21:          5468         112056  [Ljava.lang.Class;
  22:          4655         111720  java.util.ArrayList
  23:          4335         104040  java.beans.MethodRef
  24:          2194          87760  java.util.TreeMap$Entry
  25:          1825          87600  java.util.HashMap

how can i make memory lower ?

 java.util.concurrent.ConcurrentHashMap  is every big

**Comment by ashu-mehra** [comment]
Are you using OpenJ9? If yes, do you see any difference in behavior when using Hotspot JVM?

**Comment by 15838028035** [comment]
no , i am use hotspot jvm ,

**Comment by ashu-mehra** [comment]
Actually this project does not look into problems related to Hotspot JVM.
For Hotspot specific issues, you can use their mailing list or use stackoverflow.com

And coming to your specific concern, the jmap histogram does not give any evidence that the problem is related to JVM. It can be that your application needs that many `java.util.concurrent.ConcurrentHashMap` objects. If you are looking for optimizing your application to reduce heap usage, I would encourage you to use stackoverflow.com for problems where JVM has little role to play.

**Comment by 15838028035** [comment]
okay , thanks
