### ISSUE TITLE
special.system tests not running on 0.16 release build

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7006]
The special.system tests aren't excluded in the 0.16 release branch [1], and `special.system` is included in the TESTS_TARGETS for the 0.16 release build [2], but the tests did not run.

[1] https://github.com/eclipse/openj9/blob/v0.16.0-release/buildenv/jenkins/variables/defaults.yml
[2] https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-0.16.0-Build/build

**Comment by pshipton** [comment]
@AdamBrousseau @llxia

**Comment by AdamBrousseau** [comment]
I think it's because the pipelines (including the variable file) are pulled from master. If you specify the variable file parameters it should work. Can refer to the internal personal build for the params. Either that or modify the job config to pull the pipelines from the release branch. I would recommend the former.

**Comment by pshipton** [comment]
ok, I've set VARIABLE_FILE and trying it here https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-0.16.0-Build/3/

**Comment by pshipton** [comment]
Seems I need to set more, like VENDOR_REPO, VENDOR_BRANCH. Trying more builds.

**Comment by pshipton** [comment]
Thanks, that seemed to fix it
```
10:01:00  TESTS_TARGETS: special.system
[Pipeline] echo
10:01:00  EXCLUDED_TESTS: []
```
