### ISSUE TITLE
OpenJDK8,11,12 LibertyStartup Regression ~40-80% (AIX PPC64)

### ISSUE THREAD

**Issue by piyush286** [eclipse/openj9#7459]
This issue was discovered internally at IBM and is currently being investigated. This issue is created so that the problem can be exposed to the Release 0.17.0 milestone plan.

Liberty startup regression of 35-60% has been introduced between 20190909 and 20190911 builds. The regression slightly changed between 20190911 and 20190926 builds, varying from 17 to 77%. 

The regression is seen on Java 8, 11 and 12 on AIX PPC64.

**Last Known Good Build:**
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+6-201909091237)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-92ad03e, JRE 11 AIX ppc64-64-Bit Compressed References 20190909_351 (JIT enabled, AOT enabled)
OpenJ9   - 92ad03e
OMR      - 7e9584e
JCL      - 3c31c8c based on jdk-11.0.5+6)
```

**First Known Bad Build:**
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+6-201909111832)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-d657426, JRE 11 AIX ppc64-64-Bit Compressed References 20190911_353 (JIT enabled, AOT enabled)
OpenJ9   - d657426
OMR      - 7e9584e
JCL      - 8057a07 based on jdk-11.0.5+6)
```

**Comment by piyush286** [comment]
FYI @pshipton @SueChaplain

**Comment by ymanton** [comment]
Summary of my investigation thus far:

- Measured a 20% regression
- Similar number of compilations at each opt level
- 10x more relocation failures in bad builds (~20 v.s. ~200)
- Startup difference widens to 3x with `-Xnojit`, relocation failures increase 10x in both builds
- Profiling shows us spending much more time in the interpreter with `-Xnojit`
- Regression is **eliminated** with `-Xaot:disableSharedCacheHints`, but it doesn't change the number of relocation failures (still ~200)

Based on the above, and the regression being traced back to #7021 I think the relocation failures and startup gap with `-Xnojit` are not immediately related to the regression and the culprit is indeed SCHints.

**Comment by ymanton** [comment]
It looks like this is working exactly as intended, unfortunately. Note that this was discovered in an environment where `-Xquickstart` is being used.

Previously, due to the compiler bug worked around in #7120, hints were not being reliably stored. A vlog from the "good" build shows this pretty clearly:

```
#INFO:  StartTime: Oct 15 21:14:02 2019
#INFO:  Free Physical Memory: 206280 MB 
#INFO:  CPU entitlement = 800.00
#SCHINTS:  adding hint 0x2000 com/ibm/jit/JITHelpers.getCharFromArrayByIndex(Ljava/lang/Object;I)C
#SCHINTS:  adding hint 0x2000 java/util/concurrent/ConcurrentHashMap.tabAt([Ljava/util/concurrent/ConcurrentHashMap$Node;I)Ljava/util/concurrent/ConcurrentHashMap$Node;
#SCHINTS:  adding hint 0x2000 jdk/internal/misc/Unsafe.getObjectAcquire(Ljava/lang/Object;J)Ljava/lang/Object;
#SCHINTS:  adding hint 0x2000 java/lang/String.lengthInternal()I
#SCHINTS:  adding hint 0x2000 com/ibm/jit/JITHelpers.putCharInArrayByIndex(Ljava/lang/Object;IC)V
#SCHINTS:  adding hint 0x2000 java/lang/String.charAtInternal(I[B)C
```

With a "bad" build we see:

```
#INFO:  StartTime: Oct 15 21:14:32 2019
#INFO:  Free Physical Memory: 206280 MB 
#INFO:  CPU entitlement = 800.00
#SCHINTS:  adding hint 0x2000 com/ibm/jit/JITHelpers.getCharFromArrayByIndex(Ljava/lang/Object;I)C
#SCHINTS:  hint added 0x2000, key = com/ibm/jit/JITHelpers.getCharFromArrayByIndex(Ljava/lang/Object;I)C, scount: 0
#SCHINTS:  adding hint 0x2000 java/util/concurrent/ConcurrentHashMap.tabAt([Ljava/util/concurrent/ConcurrentHashMap$Node;I)Ljava/util/concurrent/ConcurrentHashMap$Node;
#SCHINTS:  hint added 0x2000, key = java/util/concurrent/ConcurrentHashMap.tabAt([Ljava/util/concurrent/ConcurrentHashMap$Node;I)Ljava/util/concurrent/ConcurrentHashMap$Node;, scount: 0
#SCHINTS:  adding hint 0x2000 jdk/internal/misc/Unsafe.getObjectAcquire(Ljava/lang/Object;J)Ljava/lang/Object;
#SCHINTS:  hint added 0x2000, key = jdk/internal/misc/Unsafe.getObjectAcquire(Ljava/lang/Object;J)Ljava/lang/Object;, scount: 0
#SCHINTS:  adding hint 0x2000 java/lang/String.lengthInternal()I
#SCHINTS:  hint added 0x2000, key = java/lang/String.lengthInternal()I, scount: 0
```

Now that hints are being stored we are seeing the effect of the `TR_HintLargeMemoryMethodC` hint, which is throttling the compiler. I checked x86 and the same behaviour is evident, we emit the same hint there as well. The threshold that controls when this particular hint is emitted is `memExpensiveCompThreshold`, setting that to a very large number has no effect on the "good" build, but eliminates the regression in the "bad" build. As far as I can tell the behaviuour on AIX is now in line with all of the other platforms.

**Comment by mpirvu** [comment]
The `TR_HintLargeMemoryMethodC` hint is only used for determining whether to perform a 'forced' AOT upgrade or not. Immediately after an AOT load is executed the JIT has the option of artificially adding an upgrade compilation request to the compilation queue. These upgrades are meant to improve the throughput in the long run (and maybe rampup).
If the `TR_HintLargeMemoryMethodC` is present (presumably this is the current behavior where hints are working but a startup time regression is seen) no forced AOT upgrades wil be queued. If the hints are broken, the JIT will queue such forced AOT upgrades (at warm opt level for bootsptarp methods and at cold for everybody else). I expect the extra compilations due to the forced AOT upgrades to hurt startup, not help. Something is off here.

**Comment by mpirvu** [comment]
Since in @ymanton 's experiments the bad SDK showed more recompilations with "S" designation (request coming from Secondary queue) I looked at how those could come into existence:
After a successful AOT load we check for the existence of the following hints: `TR_HintUpgrade | TR_HintHot | TR_HintScorching`. If they exist the JIT will schedule an upgrade recompilation. If SymbolValidationManager is enabled the JIT uses the secondary queue for the upgrade (`addUpgradeReqToLPQ()`), otherwise it uses the main queue (`queueForcedAOTUpgrade()`). With the latter approach the JIT also check for the expensive hints (`TR_HintLargeMemoryMethodC`), otherwise it does not.
There is an environment variable `TR_DisableQueueLPQAOTUpgrade` that can force the code to use queueForcedAOTUpgrade() rather than addUpgradeReqToLPQ() so we should try this.
However, I cannot reconcile this with the experiments that showed a perf improvement when `memExpensiveCompThreshold` was changed.

**Comment by ymanton** [comment]
`TR_DisableQueueLPQAOTUpgrade=` turns "S"s into "A"s, but doesn't improve startup (seems to hurt slightly in fact).

I went back and tested an even older build, one that predates all of the recent changes to the Hints code and 1) the `TR_HintLargeMemoryMethodC` is emitted and stored, but 2) performance is good.

So it appears that the hint itself doesn't hurt startup and didn't in the past, but with the recent changes to the Hints code emitting it causes something bad to happen. @mpirvu's hunch that we might be clobbering some other hints or data in the SCC while writing out the hints is the next suspect.

**Comment by ymanton** [comment]
The old Hints API had (what looks very much like) a bug that caused us to not update hints unless the incoming hint was a failed validation hint. I'll try to trace the origins of this bit of code later, but it's been in OpenJ9 since day one.

https://github.com/eclipse/openj9/blob/fc0de283a29b33d73813abc58d1fb52f65246dd7/runtime/compiler/env/VMJ9.cpp#L613-L618

The current code doesn't do this; it allows hints to be updated as (presumably) intended, but that negatively affects startup. I've confirmed that adding an equivalent "fix" to current master eliminates the regression. It's not yet clear why allowing hint updates hurts us or which hint(s) might be responsible.

**Comment by ymanton** [comment]
I came to the wrong conclusion above. That code will skip updates if the hint we want to add is already there, unless it's a failed validation hint, in which case it will update just the count.

I went back and looked at the verbose logs and noticed that we sometimes wrote hints that had no relation to the hints we intended to write or wrote previously. For example:

```
#SCHINTS:  adding hint 0x8000 java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I
#SCHINTS:  hint added 0x8000, key = java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I, scount: 0
#SCHINTS:  adding hint 0x8000 java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I
#SCHINTS:  hint updated 0xc004, key = java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I, scount: 0
```

In this case it's not possible for us to have intentionally written `0xc004` based on the previous messages.

```
#SCHINTS:  adding hint 0x2000 java/lang/ClassLoader.defineClassInternal(Ljava/lang/String;[BIILjava/security/ProtectionDomain;Z)Ljava/lang/Class;
#SCHINTS:  hint added 0x2000, key = java/lang/ClassLoader.defineClassInternal(Ljava/lang/String;[BIILjava/security/ProtectionDomain;Z)Ljava/lang/Class;, scount: 0
#SCHINTS:  is hint 2000(1000) java/lang/ClassLoader.defineClassInternal(Ljava/lang/String;[BIILjava/security/ProtectionDomain;Z)Ljava/lang/Class;
#SCHINTS:  adding hint 0x1 java/lang/ClassLoader.defineClassInternal(Ljava/lang/String;[BIILjava/security/ProtectionDomain;Z)Ljava/lang/Class;
#SCHINTS:  hint updated 0x1, key = java/lang/ClassLoader.defineClassInternal(Ljava/lang/String;[BIILjava/security/ProtectionDomain;Z)Ljava/lang/Class;, scount: 0
```

In this case we seem to have lost the `0x2000` hint while writing the `0x1` hint, which is also not possible.

I traced the above back to the same compiler bug fixed in #7120. That PR fixed the test we perform to check if we've read a valid hint from the SCC. The problem is that we have pointers to the flags and count portions of the hint and the compiler dereferences them as well before actually storing the hint, so again we end up with garbage flags and counts.

This explains why everything we tried earlier that prevented hints from being emitted showed a performance improvement because it avoided writing garbage hints.

I rewrote the code to avoid pointers to help the compiler out and I no longer see bad hints being written in the log, but the 25% regression I measured was only reduced to 12%, so there's still a gap to close.

**Comment by piyush286** [comment]
@ymanton @mpirvu I was wondering whether there are any updates on it. Please let me know if you need help with the investigation.

FYI @vij-singh

**Comment by ymanton** [comment]
I've opened PR #7637 to work around the remaining compiler bug. That should close some of the gap.

As for the rest of the missing performance, I've started to focus on validation failures as a possible candidate. A current build with #7637 results in about 2x the number of AOT method validation failures (~30 -> ~70), and each failure causes us to queue up a JIT cold compilation. If we compare failures by type, most of the increase is attributable to the `compilationAotClassReloFailure` type which goes from 10 to 46. Interestingly, the same two builds show no difference in start-up time when the SCC is clear because we don't tend to get many, if any, relocation failures in such cases.

To quantify the effect on start-up I logged every failing method and excluded them from AOT compilation in both the good and bad builds, and the start-up gap shrinks to 1%.

The next step will be to figure out why we see an increase in relocation failures.

**Comment by piyush286** [comment]
@ymanton How much improvement do we expect with #7637? Just curious! We'll be monitoring our regression runs anyway to verify that.

**Comment by ymanton** [comment]
@piyush286 My start-up went from 24.3% longer down to 11.8%.

**Comment by ymanton** [comment]
I discussed this with @mpirvu a little more and he suggested we go back to looking at the hints since earlier experiments with hints disabled seemed to close the gap completely and validation failures and start-up performance in general are very sensitive to hints.

I went back to an even older build that predates any of the hints related changes and looked at what it was doing and found that it was emitting hints that don't seem possible based on the code we had at the time. For example:

```
#SCHINTS:  Found hint in sc, increase scount to: 1000, wanted scount: 19752
```

The `wanted scount: 19752` represents the count that we retrieved from the hint, but there's no way we would ever write a hint with a count like 19752 to the SCC. The code that calculates counts deals with nice round numbers with trailing zeros (10, 100, 250, 3000) and typically caps the counts at numbers like 1000 and 3000. After that I disassembled the old `TR_J9VMBase::isSharedCacheHint()` and found that it too suffered from the same compiler bug.

Based on the above I'm going to guess that we were previously writing very large counts that we didn't mean to, and even though the large counts were never directly used (e.g. the 19752 above is capped at 1000 after we read it back), the counts we intended to write (and are now writing in the "fixed" current builds) were likely lower than 1000. I'm going to try to get a similar effect in current builds by using larger counts and see where that leads.

**Comment by DanHeidinga** [comment]
These kinds of compiler problems make me think of some of the aliasing issues we've had in the VM code previously.  The VM is compiled with `qalias=noansi` to turn off some of the aliasing optimizations that tend to break us.  Does the JIT already compile with that option?

**Comment by ymanton** [comment]
> Does the JIT already compile with that option?

It's used on Linux, but not AIX (for no apparent reason).

This didn't look like a textbook ANSI aliasing violation to me earlier, and since the fix whether it was a bug in our code or the compiler was the same, I didn't focus too much on coming to a conclusion. But looking at it again I think we are indeed at fault.

The problematic code boils down to:

```
int *x = ...
...
int y = *x;
short *a = (short*)&y, *b = (short*)&y + 1;
```

I didn't think this code had any problem at first because I couldn't see any `int*` and `short*` pointing to the same memory, or any casting of the only `int*` in the picture (`int *x`). However `&y` is an `int*` and we cast it to `short*`, so I'm guessing the compiler assumes that `*a` and `*b` can't possibly point to `y` by the letter of the law and the resulting generated code starts to make sense.

Anyway, to date this bug in its various incarnations has somehow both helped and hurt start-up performance due to it living in one place at one time and being refactored and moved to another place.

**Comment by DanHeidinga** [comment]
> It's used on Linux, but not AIX (for no apparent reason).

I think it's worth adding the option to AIX as well to avoid aliasing issues given other platforms won't catch them as they disable strict aliasing.

**Comment by ymanton** [comment]
> It's used on Linux, but not AIX (for no apparent reason).

> I think it's worth adding the option to AIX as well to avoid aliasing issues given other platforms won't catch them as they disable strict aliasing.

@gita-omr FYI the above.

**Comment by ymanton** [comment]
Confirmed that increasing the hint counts we emit for failed validations closes the remaining start-up performance delta that I was measuring.

It seems that in `-Xquickstart` mode (which is what the particular IBM measurements are using) we use lower SCounts than default and could increase the failed validation counts to compensate in order to be able to load more AOT methods.

However as it stands AIX is now behaving like the other platforms and any experimentation with SCounts should be treated as a potential new improvement rather than a regression fix.

**Comment by gita-omr** [comment]
Noted the issue with qalias=noansi. Thanks.

**Comment by vij-singh** [comment]
@gita-omr @ymanton  What is the lastest summary for this issue?

**Comment by piyush286** [comment]
With https://github.com/eclipse/openj9/pull/7637, the startup regressions disappeared in our regression runs.

**Comment by ymanton** [comment]
As far as the behaviour of our code goes, the regression that was introduced by the hints API work is fixed and AIX is now consistent with the other platforms. @piyush286's measurements confirm that the delta he reported is gone. The potential further improvements I came across are best addressed as a new development item so I suggest this issue should be considered resolved and can be closed.

**Comment by DanHeidinga** [comment]
> The potential further improvements I came across are best addressed as a new development item so I suggest this issue should be considered resolved and can be closed.

@ymanton Can you add a link to the new development item tracking the further improvements?

**Comment by ymanton** [comment]
I discussed the potential improvements with @mpirvu and he suggested that the existing hint mechanism can cope with this without any further changes.

The potential improvement here is that in `-Xquickstart` mode we can write failed validation hints with higher SCounts in order to allow for more classes to be loaded and reduce the number of AOT failures. The failed validation hints however are re-emitted with higher and higher SCounts whenever methods fail to load, so after a few iterations we should reach the same counts that we were reaching due to the aliasing/compiler bug previously observed.

I went back to confirm this and increased the number of warmup runs from 3 to 4 to 5 and the gap of ~11% I was seeing dropped to ~4% and ~0.5% so that appears to be the case. Starting with a lower SCount and increasing as necessary has the benefit of finding tighter upper bounds for failing AOT loads at the cost of requiring a few more runs, but it's expected that in a real-world scenario you would run many many times with the same SCC.

Based on this I'm not going to pursue any more changes for this issue.

**Comment by vij-singh** [comment]
Agreed... lets close this

**Comment by andrewcraik** [comment]
@piyush286 if you agree with the above analysis can you please close the issue? if you have additional concerns please raise them so they can be discussed and a plan for resolution identified?

**Comment by piyush286** [comment]
No concerns! Since we've recovered the whole regression, I'll close this issue. Thanks!
