### ISSUE TITLE
Common up logic in StringBuffer and StringBuilder

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#770]
Referencing https://github.com/eclipse/openj9/pull/767 it seems we fixed an issue in StringBuilder but forgot to fix the same issue in StringBuffer. These sorts of problems could be almost entirely avoided if the logic between these two classes are commoned up.

It seems both StringBuilder and StringBuffer extend AbstractStringBuilder. Aside from serialization and some other neusences the logic in all public methods is identical for the two classes so there is a lot of duplication. Could we improve our codebase by commoning up the logic in AbstractStringBuilder?

I would love to hear other peoples thoughts on this.

**Comment by DanHeidinga** [comment]
+1 from me.  `AbstractStringBuilder` is a recent addition to our code base.  It was added to address verifier StackMapTable exceptions due to missing common superclass when compiling java code on OpenJDK, which had the class, and then running on J9, which didn't have it.

Now that's present, we should take advantage of it to clean up the code.

**Comment by andrewcraik** [comment]
This clean-up will need some careful performance measurements - it is possible that changes in fan-in frequency when the code is commoned may require the optimizer (especially the inliner) to do different things. We may also need additional try-to-inline guidance for methods that are veneers that call to the abstract implementation.

I am in favour of the de-duplication but careful performance measurement on a variety of benchmarks will be needed due to the broad usage and performance impact of these classes.

**Comment by pshipton** [comment]
Obsoleted by #1786
