### ISSUE TITLE
What are the reasons for having a separate Java stack?

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#7761]
While working on miscellaneous performance investigations I have stumbled on an article on Java flame graphs from the team over at Netflix [1] in which they generated `perf` reports on Linux and then transformed them into flame graphs to understand a full picture of where time is being spent in the JVM process.

I gave the same thing a try on OpenJ9 and it did not work, presumably because `perf` was unable to walk the backtrace of JIT and interpreted frames because they are not part of the system stack linkage. I am wondering if anyone has historical context on the drivers behind the choice to use a separate Java stack in OpenJ9? Are there advantages/disadvantages which are applicable today?

[1] https://medium.com/netflix-techblog/java-in-flames-e763b3d32166

**Comment by DanHeidinga** [comment]
Related previous discussion: https://github.com/eclipse/openj9/issues/3497

There are pluses and minuses to having separate stacks as you've noted.  I'll call out some of the benefits as you've already noted the major disadvantage (harder to work with native tools like flamegraphs) that I'm aware of.

Benefits:
* java stacks can grow as required and different threads can use different sized stacks.

* For compressedrefs, java stacks can be allocated below the 4 gig mark ensuring that stack allocated objects can be compressed with the appropriate shifts and appear the same as regular compressed objects.  Without this, it is harder for stack allocated objects to refer to other stack allocated objects.

* Works well with zOS stack biasing and offset issues.

* Potential benefits when implementing Project Loom-style continuations as each continuation can have its own java stack rather than needing copies on/off the native stack.

* The runtime has full control over the frame shape allowing for compact frames per java method invocation.  This is likely a bigger benefit to fixed frame platforms.

**Comment by fjeremic** [comment]
Thanks for linking to the relevant #3497 discussion and for your explanation. From the points above is the benefit largely classified as footprint savings or throughput improvements? Have we always had separate stacks? I'm wondering if any experiments have been performed on a unified stack in the past?

For context it may be a reasonable (ambitious) research experiment, perhaps as an academic research experiment, to attempt to unify the stacks and see what the measurable trade-offs may be.

**Comment by DanHeidinga** [comment]
We've had separate stacks as long as I've been involved in the code base and I suspect the heritage goes all the way back to the green-threaded Envy Smalltalk VM.

What would you expect to get out of such an experiment?  What would signify success?

We've done some experiments in the past around supporting Flamegraphs which I'd be more inclined to resurrect and see if get the java stack to be walkable (at least on x86) by system tools like perf, bpf, etc.

**Comment by fjeremic** [comment]
> What would you expect to get out of such an experiment? What would signify success?

Getting call graphs working using system tools such as `perf`, `bpf`, `oprofile`, `gperf`, etc. out of the box, or any other tool which was built to work with HotSpot would definitely be a goal. Another one which comes across frequently is debugging using system tools such as `gdb`, `lldb`, `windbg`, etc. which all understand native stack frames quite well and have a plethora of tools built around them.

**Comment by DanHeidinga** [comment]
> Getting call graphs working using system tools such as `perf`, `bpf`, `oprofile`, `gperf`, etc. out of the box

Sounds like we're on the same page with respect to the end goal.  We're suggesting different paths to get there - one is move entirely to the native stack or try to make the existing java stack walkable by the system tools.

What do you propose is the next step for this issue?  Is it close as the question's been answered or is there some value to keeping it open at this point?

**Comment by fjeremic** [comment]
> What do you propose is the next step for this issue? Is it close as the question's been answered or is there some value to keeping it open at this point?

I think the question has been answered and is now searchable for future reference. Thanks!

**Comment by 0xdaryl** [comment]
First off, thanks for documenting some of the design reasons for the separate stacks.  This question has come up a few times.  I usually fall back on my historical recollection of J9 when it was an embedded product and where the separate stacks facilitated growing the stack and made it easier to start with much smaller Java stacks.  I'm glad to know some of the other benefits as well.

While I agree this particular issue can be closed, I think the larger issue for how to get external tools to walk the OpenJ9 Java stack is still an important one.  Hopefully, there is some commonality among all those tools that can be shared rather than addressing each tool individually.  Maybe an epic issue could be left open for this kind of work, unless one already exists?

Perhaps this is a topic for an OpenJ9 Architecture meeting.  :-)

**Comment by kgibm** [comment]
An alternative might be to embed DWARF information instead of using base pointer register. We recently used `perf record --call-graph dwarf` with J9 with much success to investigate a native JVM issue, and `-Xjit:perfTool` gave us the top stack frame of non-native samples although it would be wonderful if `perf` could walk beyond those top stack frames.

>        --call-graph
>            Setup and enable call-graph (stack chain/backtrace)
>            recording, implies -g. Default is "fp" (for user space).
> 
>                The unwinding method used for kernel space is dependent on the
>                unwinder used by the active kernel configuration, i.e
>                CONFIG_UNWINDER_FRAME_POINTER (fp) or CONFIG_UNWINDER_ORC (orc)
> 
>                Any option specified here controls the method used for user space.
> 
>                Valid options are "fp" (frame pointer), "dwarf" (DWARF's CFI -
>                Call Frame Information) or "lbr" (Hardware Last Branch Record
>                facility).
> 
>                In some systems, where binaries are build with gcc
>                --fomit-frame-pointer, using the "fp" method will produce bogus
>                call graphs, using "dwarf", if available (perf tools linked to
>                the libunwind or libdw library) should be used instead.
>                Using the "lbr" method doesn't require any compiler options. It
>                will produce call graphs from the hardware LBR registers. The
>                main limitation is that it is only available on new Intel
>                platforms, such as Haswell. It can only get user call chain. It
>                doesn't work with branch stack sampling at the same time.
> 
>                When "dwarf" recording is used, perf also records (user) stack dump
>                when sampled.  Default size of the stack dump is 8192 (bytes).
>                User can change the size by passing the size after comma like
>                "--call-graph dwarf,4096".

https://www.kernel.org/doc/man-pages/online/pages/man1/perf-record.1.html
