### ISSUE TITLE
Move P & Z linux machines to cent 7 or RHEL 7

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#7791]
Currently, OpenJ9 build machines on p & z linux are running Ubuntu.  This is different than the OSes we're using for build at Adopt and requires running the binaries on Ubuntu or newer OS levels due to glibc requirements.

Let's migrate the OpenJ9 build machines to use Cent 7 or RHEL 7 to match Adopt and ensure the binaries work across most distros.

This also allows perf testing on existing perf boxes when there are hiccups in the adopt build delivery.

**Comment by DanHeidinga** [comment]
FYI @jdekonin @AdamBrousseau @pshipton

**Comment by AdamBrousseau** [comment]
Note that our zlinux offering from Marist only supports the following OS levels

```
Standard KVM Operating System Support
RHEL8
SLES 15 SP1
Ubuntu 18.04

Continued Operating System Support
Rhel7.7
SLES 12 SP4
Ubuntu 16.04
```
"Continued" means that they will be unsupported "soon"
From Cindy
```
... we do plan to support both Ubuntu 16 & 18 but will encourage user to move up later in the year(2020), likely after 20.4(LTS) became available ...
```

**Comment by pshipton** [comment]
RHEL 7 is fine, we just assumed CentOS 7 would be the available OS. Can you find out how long it will be available. I found "End of Maintenance Support 1" is Aug 2020, and "End of Maintenance Support or Maintenance Support 2 (Product retirement)" is June 2024. Atm RHEL/CentOS 7 is the lowest available glibc version. When it's no longer available we'll have to move to the next OS with the lowest level.

**Comment by AdamBrousseau** [comment]
From Cindy
```
The cloud team has no plan to sunset RHEL 7 at this point so moving to RHEL 7 should be good for quite some time.
```

**Comment by DanHeidinga** [comment]
@AdamBrousseau That covers zLinux.  Are we able to switch the pLinux machines to cent 7 / rhel 7?

**Comment by AdamBrousseau** [comment]
Yes, sorry, I was going to comment but then I thought no news was good news :)

Via OpenStack at OSU we can build Cent 7.3+, Debian 9.3+, Fedora 26+ or Ubuntu 14+. The P at UNB we own so I assume we can put whatever we want there. If we want RHEL instead of Cent we would just need to figure out the licencing.

**Comment by DanHeidinga** [comment]
Cent is fine and avoids dealing with the licensing.  Once the builds have all stabilized after the UNB outage, I'd like to start migrating the compile machines to cent 7 / rhel 7

**Comment by AdamBrousseau** [comment]
Also note the zlinux are due to be "migrated" (recreated from scratch) by the end of the year. Marist is moving all images to a new z15.

**Comment by jdekonin** [comment]
As discussed on OpenJ9 community call on April 1 and 8th, due to the Power KVM host stability (UNB Power8) issue which appears to be resolved; we will not proceed with Cent7 compile machine change or implement the mirrored artifactory solution until we have either a backup plan or a way to get someone in to fix things if there’s a problem.

**Comment by jdekonin** [comment]
The remaining work on this issue was complete with the merge of #8819.  I believe this can be closed.
