### ISSUE TITLE
Setup automatic trigger for Pipeline-OMR-Acceptance-11

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7854]
Due to https://bugs.eclipse.org/bugs/show_bug.cgi?id=553326, I've temporarily split OMR acceptance into 2 jobs, Pipeline-OMR-Acceptance-8 (the original) and Pipeline-OMR-Acceptance-11 (a new job). It seems this reduction in jobs starting at the same time is enough to allow git checkout on master to succeed. It worked well enough to get OMR promoted (manually) over the weekend.

Pipeline-OMR-Acceptance-11 will start a bit later, but it needs to kick off automatically like Pipeline-OMR-Acceptance-8 already does when there are new commits merged. To create 
Pipeline-OMR-Acceptance-11 I copied Pipeline-OMR-Acceptance-8, but the automatic kick off isn't working, I assume it's configured in some other place.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
It's the [mirror job](https://ci.eclipse.org/openj9/view/Infrastructure/job/Mirror-OMR-to-OpenJ9-OMR/) that fires the ABuild via this [pipeline script](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/infrastructure/omrMirror.groovy#L63). I would very much prefer not to add a hack on our side as a (temp) workaround. To do it properly you'd need to coordinate them to fire sequentially with a delay via another wrapper job and pull out the promote into the new job in order to block promote on both jobs.

**Comment by pshipton** [comment]
I've put the delay into Pipeline-OMR-Acceptance-11 using the Quiet period. For the promote, I'll just do it manually for now. I'm hoping we can go back to the original OMR-Acceptance build once Eclipse has a chance to look at the problem, meanwhile I don't want all the OMR changes to queue up.
