### ISSUE TITLE
Operator Options for BigDecimal and BigInteger.

### ISSUE THREAD

**Issue by PowerUser1234** [eclipse/openj9#796]
-The way things are, BigDecimal and BigInteger are not integral types.
this means that the following operators cannot be directly used on their variables:

+,-,*,/,%,++,--,**,//,%%,+=,-=,*=,/=,%=

Can all these be brought in for BigDecimal and BigInteger at least, along with
my proposed changes with 

https://github.com/eclipse/openj9/issues/795

?

**Comment by JamesKingdon** [comment]
Hi, thanks for raising this issue.
As you pointed out, BigDecimal and BigInteger are Classes, not Java primitives, so to do what you ask requires operator overloading. Operator overloading is not part of the Java language, and we can't add something like that while remaining compliant with the specification, which we are legally bound to do in order to continue to use the Java name and branding.
To have the language changed would require proposing a new Java Specification Request (JSR) through the Java Community Process - https://www.jcp.org/en/jsr/overview

**Comment by DanHeidinga** [comment]
@PowerUser1234 As James stated, operator overloading is a topic to broach with the JCP or by raising a JEP at OpenJDK.  I'm sorry we're unable to take this idea further at OpenJ9 at this time.
