### ISSUE TITLE
Different results presented by method Method.toString

### ISSUE THREAD

**Issue by felipepontes-research** [eclipse/openj9#803]
Method.toString method presents different results as presented by Oracle Hotspot JVM when executing the following program:

	import java.lang.reflect.Method;
	public class A {
		public static void main(String[] args) throws NoSuchMethodException {
			Method hashCodeMethod = A.class.getMethod("hashCode");
			System.out.println(hashCodeMethod.toString());
		}
 	}

**Affected versions (compiled from repository):**

openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-_2017_12_06_11_34-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171206_000000 (JIT enabled, AOT enabled)
OpenJ9   - ed54836
OMR      - addcf79
OpenJDK  - 8685bef based on jdk8u152-b16)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using OpenJ9 java
	3. Run it using Oracle HotSpot java

**Current result:**

OpenJ9: public int java.lang.Object.hashCode()
Hotspot: public native int java.lang.Object.hashCode()

**Expected result:**

Both JVMs presenting the same method signature.

**Comment by fjeremic** [comment]
This is because of the following definition:

https://github.com/eclipse/openj9/blob/ac222893324f4aed7bb5d3c2f59484f305a3e0d6/jcl/src/java.base/share/classes/java/lang/Object.java#L132-L134

IIRC the JCL specification for `java.lang.Object.hashCode()` does not dictate whether or not the method is marked `native`. In fact looking at the Javadoc for the method for the Oracle version (https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#hashCode--) it is defined as `public int hashCode()` but as per the Current result section in your description HotSpot marks it as `native`.

This is a JDK difference but I do not think either of them are incorrect.

**Comment by pshipton** [comment]
The question has been answered, please reopen if there is still a problem.
