### ISSUE TITLE
cent6-x64-1 NoRouteToHost

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8163]
Disabled the machine.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/218
```
java.rmi.ConnectIOException: Exception creating connection to: 192.168.10.197; nested exception is: 
	java.net.NoRouteToHostException: No route to host (Host unreachable)
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by rajdeepsingh1** [comment]
Investigation in progress -  looking for `192.168.10.197` machine

**Comment by rajdeepsingh1** [comment]
Due to limited permissions on the OJ9 Jenkins platform I am unable to check the configuration / parameters for `cent-x64-1` 

The IP `192.168.10.197` does not seem to be assigned to any machine in the network as well. 

Do the following tests (below) for the other cent6-x64* machines try to reach the same IP? `192.168.10.197` - if so , are they successful?

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/218/testReport/org.openj9.test.attachAPI/TestManagementAgent/

**Comment by pshipton** [comment]
@rajdeepsingh1 the tests only communicate with the machine they are running on. cent-x64-1 is incorrectly configured in some way with the IP address 192.168.10.197, perhaps in the /etc/hosts file. We've seen this before, @jdekonin can explain how to fix it.

**Comment by pshipton** [comment]
See https://github.com/eclipse/openj9/issues/7820#issuecomment-561398357 for the previous problem/solution.

**Comment by rajdeepsingh1** [comment]
@pshipton

Thanks Peter! - I had checked the /etc/hosts file on the jumpbox prior and it seems `cent6-x64-1` was already assigned to the correct IP .208 rather than .197.

I have made a configuration change just now on the `centx6-x64-1` machine itself and have rebooted it. It is back online now. Let me know if there are any further issues.
