### ISSUE TITLE
Docs for "Configuring your Runtime Environment" is 404

### ISSUE THREAD

**Issue by simmel** [eclipse/openj9#82]
Might be the wrong place to report it but I found no other.

On the "Read the docs"-page, https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/welcome/welcome_javasdk_version.html, when you press "Configuring your Runtime Environment" you get the message:
The requested resource is not found: /support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.multiplatform.90.doc/user/configuring.html

**Comment by Bluevisitor** [comment]
I see that too. No worries, I've contacted the guys who handle those docs and they're on the case.

Expect another update when this issue is resolved.

**Comment by SueChaplain** [comment]
@simmel Hi Simon. We are planning on providing a better view of the docs at that site that supports both IBM Java 9 SDK beta customers as well as people who are building OpenJDK with an OpenJ9 VM. The welcome page and links will change and we'll be separating out a VM reference that reflects the code at OpenJ9.  Watch this space!

In the meantime, I think this is the topic that will help you with configuring the Runtime Environment: https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.multiplatform.90.doc/configuring.html

Please note that some of the information here might relate specifically to the IBM SDK, rather than an OpenJDK build with OpenJ9.  If you have any questions, please let me know.

**Comment by simmel** [comment]
Thank you for the detailed update Sue!

**Comment by doveye** [comment]
@simmel Hi Simon. The link issue is now fixed (actually, the link has gone!) and the VM reference that Sue mentioned in comment #82 has been created. The intro page for that is https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/j9vm_reference.html. This should make it easier for people to find info that is relevant to OpenJ9 :)

**Comment by ymanton** [comment]
@doveye, the link "Welcome - Eclipse OpenJ9 users" on this page is https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/welcome/welcome_javasdk_version.html is broken FYI. It points to https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.vm.9.0.doc/j9vm_reference.html?view=kc which doesn't exist.

**Comment by doveye** [comment]
Fixed, thanks @ymanton :)
(you might need to hard-refresh the browser cache to show a recent update in the IBM Knowledge Center)
