### ISSUE TITLE
Add mechanism to gracefully terminate JITServer 

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#8228]
Currently there is no workflow to terminate the JITServer and it needs to be killed manually.
Add ~~`JITServer_DestroyServer`~~ `stopJITServer` API that would gracefully terminate the JITServer.
Once the API is available, jitserver launcher should be updated to use this API.

**Comment by ashu-mehra** [comment]
JITServer, being a server, does not exit by itself. We need some mechanism to let the server process know that it needs to shutdown. We can do this by starting up a new process which would communicate to the jitserver process over socket, asking it to shutdown but then it would also allow any external process to terminate the jitserver (provided it can connect on that port). 
We can use other IPC mechanisms which would work only for local processes like shared memory or named-pipes.

I also looked at how the open-liberty and tomcat handle the shutdown. In case of open-liberty we run a script that starts up another java process which communicates with the server process using socket and sends a command to the server to shutdown. Server also presents an auth challenge that the process requesting for shutdown needs to fulfil. Challenge is in the form of a file that server process creates which the other process needs to delete to prove it has required (write) access.
Tomcat has similar mechanism of starting up a new java process that communicates with the server process over socke but it does not seem to present any authorization.

I feel named pipes present a simple interface for this kind of communication and we can set the desired permission on the named-pipe similar to a file, so we don't really need to worry about authorization as well.

Once we decide on what kind of mechanism we should use, `JITServer_DestroyServer` api can then be developed around it.
@DanHeidinga  @mpirvu your thoughts on this?

**Comment by mpirvu** [comment]
@ashu-mehra Could you please detail the sequence of operations?
Who creates the named pipe? It should have the same permissions as the server.
If the server creates the named pipe and it is supposed to destroy it, what happens if the server dies before it has a chance to do so?
What happens if there are several servers on the same machine operating on different ports? We need different named pipes.

**Comment by ashu-mehra** [comment]
Some more points that were discussed with Marius:
1. The named pipe would be created by the server. 
2. We can use the port number or pid of the JITServer process to create a unique named pipe under user's home directory, just like we do for shared class cache.
3. If there are multiple JITServer's running, user would need a way to identify them when terminating them. Again, the pid can be one way to identify the servers. But it is not going to be intuitive to the user. Alternatively we can have the user give a name to the JITServer process which must be unique across all JITServers running in the system.
4. If a user-supplied name is used for identifying JITServer, same can also be used to create the named pipe.
5. Open question is how to clean the named pipe if the server terminates abruptly. It would keep lying in the system unless cleaned up manually. This can be more problematic for automated testing as the code is not yet mature, and if server crashes it will leave behind artifacts which can prevent obstruct future testing.
@mpirvu I see we have signal handler in JIT (`jitSignalHandler`) to protect against crashes during compilation. Would that be appropriate place to perform the cleanup?
6. When JITServer receives a termination request all in-progress compilation requests should be aborted.

If this approach of using named-pipe is complicating things, we can go back to using sockets. Probably for now it would be sufficient as the JITServer is still a technology preview only, and not expected to be used in production.

@DanHeidinga can you please share your opinion on this?

**Comment by mpirvu** [comment]
> I see we have signal handler in JIT (jitSignalHandler) to protect against crashes during compilation. Would that be appropriate place to perform the cleanup?

Yes, but only if we are about to terminate the process.

**Comment by ashu-mehra** [comment]
@DanHeidinga can you please provide your inputs on this.

**Comment by ashu-mehra** [comment]
> do we have existing port library apis to create named pipes?

Nope, I don't think we have port library apis for that.

> Do they work across the platforms we support (and plan to extend JITServer support to in the future)?

It works in Linux [1]. Windows also has named pipes [2] but they differ from Linux in some respects.
Fortunately AIX [3] and z/OS [4] seem to have these APIs as well.

[1] http://man7.org/linux/man-pages/man3/mkfifo.3.html
[2] https://docs.microsoft.com/en-us/windows/win32/ipc/named-pipes
[3] https://www.ibm.com/support/knowledgecenter/ssw_aix_72/m_bostechref/mknod.html
[4] https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbcpx01/fifopip.htm

**Comment by ashu-mehra** [comment]
I should also mention following section from man page [1] for pipe:
```
   Portability notes
       On some systems (but not Linux), pipes are bidirectional: data can be
       transmitted in both directions between the pipe ends.  POSIX.1
       requires only unidirectional pipes.  Portable applications should
       avoid reliance on bidirectional pipe semantics.
```
This implies, unlike sockets, we would need pair of pipes for two-way communication.

[1] http://man7.org/linux/man-pages/man7/pipe.7.html

**Comment by ashu-mehra** [comment]
@DanHeidinga do you see any other issues in using named pipes for this work? Are there any other options or suggestions?

**Comment by DanHeidinga** [comment]
I'd like to see more details on deployment scenarios here as they'll drive the way users interact with (and how they want to shut down) the jitserver.

The first use case is the user running `jitserver --port=... --address=....` in a terminal.  
Shutdown options:
* same terminal: ctrl-c
* terminal on same machine: `jitserver --port=... --address=.... --shutdown`?

For Cloud (Kube?) deployments, would jitserver be running as part of the `pod`?  Or as a separate `pod` in the cluster?  Is the intention to have a jitserver per pod (basically per app or group of containers) or one per customer shared by all applications?

Is the intention to have the jitserver as a shared service used by multiple clusters (aka different users) as a piece of shared infrastructure or done as something each cluster / group pf users would use?

Many shutdown scenarios amount to variations of "kill the container running the jitserver".  Is graceful shutdown needed in those cases?  

Many services need a way to drain their request queue and stop taking new requests before they are shutdown.  Is that something being built into the protocol?

My preferred way for same user scenarios is to have messages in the protocol that tell the server to stop accepting new requests, and other messages to tell it to shutdown.  

For multi-user scenarios (aka shared jitserver), the server would need to be configured to only accept these messages with some kind of authenticated user (owner of the service) and to otherwise drop them.

Sorry, this is a bit of a brain dump.

How does the proposed pipe solution fit with the different use cases?  Do you see it as the right approach given the partial set of scenarios above?

fyi @mpirvu @mstoodle

**Comment by ashu-mehra** [comment]
> Many shutdown scenarios amount to variations of "kill the container running the jitserver". Is graceful shutdown needed in those cases?
Many services need a way to drain their request queue and stop taking new requests before they are shutdown. Is that something being built into the protocol?

So far we have been shutting down JITServer by killing it and it has worked. I believe any active JITClients are resilient to handle disconnection from JITServer, is that correct @mpirvu ?
I am sure, in such case, killing the container wouldn't be a problem, which brings us to the question: do we really need graceful shutdown?
If clients are not affected, then probably we don't really need to worry about graceful termination of JITServer.
@mpirvu your opinion on this?

**Comment by mpirvu** [comment]
> For Cloud (Kube?) deployments, would jitserver be running as part of the pod? Or as a separate pod in the cluster? Is the intention to have a jitserver per pod (basically per app or group of containers) or one per customer shared by all applications?

The intent was to have JITServer running in its own pod serving many other pods/applications.

> Many shutdown scenarios amount to variations of "kill the container running the jitserver". Is graceful shutdown needed in those cases?

The client can survive diconnects from the server (for any reason). Graceful shutdown is a nice to have feature, but not a requirement from that point of view.

> Many services need a way to drain their request queue and stop taking new requests before they are shutdown. Is that something being built into the protocol?

At this point we don't have that kind of functionality. The server going away means that the client will encounter an error while reading/writing from the socket and an exception is thrown and handled such that the client will retry the compilation locally.

> My preferred way for same user scenarios is to have messages in the protocol that tell the server to stop accepting new requests, and other messages to tell it to shutdown.
For multi-user scenarios (aka shared jitserver), the server would need to be configured to only accept these messages with some kind of authenticated user (owner of the service) and to otherwise drop them.

The authentication is the delicate part in this whole shutdown process and the named pipe solution proposed by @ashu-mehra seems to have the fewest disadvantages, though we would have to implement from scratch because portlib does not support named pipes at the moment.

**Comment by DanHeidinga** [comment]
> The authentication is the delicate part in this whole shutdown process and the named pipe solution proposed by @ashu-mehra seems to have the fewest disadvantages, though we would have to implement it from scratch because portlib does not support named pipes at the moment.

Can you expand on how the named pipe addresses the cloud (k8) / non-local machine shutdown scenarios?

**Comment by ashu-mehra** [comment]
> the cloud (k8) / non-local machine shutdown scenarios?

I guess you meant shutting down the server from a system different from where it is running.
In that case named pipe solution cannot be used. For that we have to use sockets, that's the only way to communicate. 

But why do we need that kind of shutdown? User can instead issue the shutdown command on the system hosting the server using ssh. Is that not feasible in cloud scenarios?

Do web servers like open-liberty or tomcat support that kind of remote shutdown? 
As per my understanding of open-liberty shutdown mechanism (which is mentioned in earlier [comment](https://github.com/eclipse/openj9/issues/8228#issuecomment-578839695)), I don't think it is possible.
But it should be possible to do that with tomcat. So there is no standard approach followed by the web servers.

I guess I have to go back to my question: do we need that kind of shutdown capability?

Another question is if the server is shutdown by killing the container, do we still perform graceful shutdown?

**Comment by DanHeidinga** [comment]
Rereading though this issue and I think we're going down a rabbit trail....

The original proposal was that modeling the JITServer creation apis on the JavaVM innvocation apis made a lot of sense.  It lead us to create the `JITServer_CreateServer` call modelling the `JNI_CreateJavaVM`.  Correspondingly, the invocation api has a `JNI_DestroyJavaVM` call that needs an equivalent api point in JITServer - `JITServer_DestroyServer`.

This allows custom launchers to start and stop a JITServer in a clean way.

All other ways of cleanly shutting down a server would use this api, regardless of whether its socket based or named pipe based.

Let's get the `JITServer_DestroyServer` created as one task.  Specifying how it will be called by the default `jitserver` executable is a separate issue

**Comment by DanHeidinga** [comment]
Remote management of an appserver is of vital importance for managing deployments, especially as the number of servers goes up.

A solution that requires direct machine access via ssh is basically a non-starter.

> Another question is if the server is shutdown by killing the container, do we still perform graceful shutdown?

I think we do.  Server management will be important and we'll need a way for a remote actor to control the server to do things like tell it stop accepting new connections and drain any in-progress compiles, to tell it shutdown, maybe to pull diagnostics from it.

The `JITServer_DestroyServer` api point is something that can be used by what-ever the eventual connection process is to shut the server down.  It's the primitive we need to start with.

Sketching out the larger remote administration process (K8 Operator anyone?) is a different design.

**Comment by ashu-mehra** [comment]
PR #8844 addresses this issue, but we are not yet using the `stopJITServer` api in jitserver launcher. As such it wouldn't be beneficial for that PR alone to go into 0.20 release. So this issue and merging of PR #8844 should be deferred until 0.20 release is done.
