### ISSUE TITLE
OpenJ9 ignores the -Xnoaot switch

### ISSUE THREAD

**Issue by AleksNo** [eclipse/openj9#8422]
Hi, since version 0.17 OpenJ9 ignores the -Xnoaot-switch.

And it creates an image in the C:\Users\Username\AppData\Local\javasharedresources directory. I have tested it with Windows 10 64 bit. Version 0.18.1 is affected too. This issue is reproducible with every Java application i've tested.

Thank you

**Comment by pshipton** [comment]
> OpenJ9 ignores the -Xnoaot

Can you please give more details about what you are seeing and what you expect to see?
FWIW On a 0.18 build for Windows `java -Xnoaot -version` shows `(JIT enabled, AOT disabled)` which is the expected behavior.

> And it creates an image in the C:\Users\Username\AppData\Local\javasharedresources directory

This is expected because https://www.eclipse.org/openj9/docs/version0.16/#some-class-data-sharing-is-enabled-by-default

**Comment by dsouzai** [comment]
Closing based on inactivity; @AleksNo please reopen if you're still having this problem.
