### ISSUE TITLE
Investigate adding an artifactory server at UNB

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#8425]
With the increasing number of machines located at UNB and the 1G interface for these machines to the outside world there has been failures that suspiciously appear to be bandwidth related when downloading the SDK under test.

This issue is to track discussion on what could be done to reduce the amount of traffic across the network thereby reducing the possibility of network congestion causing download failures.

**Comment by jdekonin** [comment]
fyi @AdamBrousseau @pshipton

**Comment by AdamBrousseau** [comment]
Related #2637

**Comment by AdamBrousseau** [comment]
Brain-dump:
- Logic gets a bit fancy because of 1) OSU p machines and 2) UNB VPN
- Map of Art servers: index geo.
- Default server - geo (osu)
- Test pipe gets geo (local), build desc gets Default
- Do we support plinux osu/unb cross? (ub16). Machines are labelled `ci.geo.xxx`.
   - Yes
   - Note, moving to rh7. https://github.com/eclipse/openj9/issues/7791 Shouldn't matter since we will move both unb/osu machines over.
- Bugzilla to add second server to jenkins config (jiro casc unsupported iirc)

#### variables
```
artifactory:
   server:
      default: osu
      osu: xxx
      unb: xxx
```
#### Build
- Always upload default
- If geo exists & !default, upload
- Build desc gets default

#### Test
- if second upload occurred, pass test geo link and additional label for geo. else test gets default link (no extra labels).

#### Use cases
##### Current
- Build/test at ibm/marist/softlayer
   - no change
- Build at OSU (plinux)
   - no change, can test at OSU or UNB
- Build at UNB (plinux)
   - Double upload, tests forced to stay at UNB (lose 3 test machines)
- Build at UNB (osx/xlinux)
   - Double upload, tests forced to stay at UNB (no loss of machines)
##### Possible future
- 2 public pools of platform XYZ
   - Art server at geo ABC (non-default)
   - build runs at geo ABC, test will be forced to stay at ABC.
      - May significantly reduce number of test machines available for this build.
   - IMO we shouldn't necessarily worry about a problem we don't (yet) have and may never have. We could adjust things if we come across new use cases. Hopefully the logic is generic enough (not hardcoded) so that it is expandable without too much refactor.

**Comment by AdamBrousseau** [comment]
Update:
To cover 3rd use case above. In order to not limit where a test runs, which makes orchestrator side logic more simple. Rather than passing a specific url to the test pipelines we pass a url with a variable name to cover the server half (eg. `$PREFERRED_ARTIFACTORY/path/to/sdk.tar.gz`). Each node/machine is configured with a jenkins env variable with this value. This is set in the eclipse/jiro git repo. When the test pipeline passes the url to the get.sh script, the variable should resolve on the node. Further, internally where we only have 1 server, we should be able to set this as a global variable to avoid setting it on every machine.

To test:
Node variable and global variable are resolvable in the test jenkinsfile. Does not need to be resolvable within get.sh because it should be resolved when the pipeline passes it to get.sh.

**Comment by AdamBrousseau** [comment]
This re-introduces the problem of compiling at OSU and testing at UNB, the SDK will attempt to be fetched from UNB but it will only be at OSU. Will need to rethink this a bit.
