### ISSUE TITLE
product crashes at startup when upgrading from 13.0.1-openj9-0.17 to 13.0.2-openj9-0.18

### ISSUE THREAD

**Issue by jcompagner** [eclipse/openj9#8517]
4 files are generated i 7zipped them here: http://download.servoy.com/openj9-0.18.7z

This is an eclipse based product where in the eclipse.ini file i just switch the vm
And if i run it with OpenJDK 13.0.1 it works fine, just switching the vm:

-vm
D:\servoy_inst\201912_rc2\developer\jdk-13.0.2+8-jre/bin/j9vm/jvm.dll
-vmargs
-Xshareclasses:nonfatal
-Xms40m
-Xmx1G
--add-modules=ALL-SYSTEM

will always crash it right away at startup generating always 4 files.

**Comment by pshipton** [comment]
```
1XHEXCPMODULE  Compiling method: org/eclipse/osgi/container/ModuleDatabase.findCapabilities(Lorg/osgi/resource/Requirement;)Ljava/util/List;
NULL           
1XHFLAGS       VM flags:000000000005FF04
```

**Comment by pshipton** [comment]
Possible dup of #8175 and #7890 @dsouzai

**Comment by dsouzai** [comment]
Heh, do we have the means to get a Windows build with symbols, because without it I can't take a look at the core file.

This likely is a dup of the two issues @pshipton mentioned, of which I don't know the root cause yet. However, @jcompagner, as a workaround, you could try adding `-Xjit:dontUsePersistentIprofiler` to the JVM parameters; assuming it's the same problem it _should_ stop the crash.

**Comment by jcompagner** [comment]
yes with those 2 vm args it starts up.

**Comment by dsouzai** [comment]
@jcompagner I had a question regarding this issue; Did you ever run the product with 0.17 on the same machine before trying out 0.18? I'm asking because I'm curious as to whether there's an existing default SCC that was created by the previous JVM version.

**Comment by jcompagner** [comment]
yes i did, and i now just reverted the whole update to that .18 release and it just works in the same machine..
Exactly the same product of us (eclipse based) and running that by just toggling in the eclipse.ini file between the .17 and .18 will make it run in the first and crash in the second.

**Comment by jcompagner** [comment]
But you are saying if i would just delete the shared cache it would work?
(not that that is something i can tell all our clients todo...)

**Comment by dsouzai** [comment]
> But you are saying if i would just delete the shared cache it would work?

Because I don't know what the root cause is I can't say that with any certainty. However, in our internal tests, the crash we were seeing was caused by the JVM loading from a cache that was created from a different java process (the one running the Jenkins slave) which I believe was running a different OpenJ9 version. I wanted to see if you were in a similar situation, which seems to be the case. It doesn't reveal anything mindblowing, but it's relevant information to have I suppose.

That said, it is worth deleting the SCC and trying.

> (not that that is something i can tell all our clients todo...)

I'd say that when changing JVM versions, it is probably good practice to delete the SCC. While the class sharing parts of the SCC may work between versions, the AOT code won't; OpenJ9 will not load any AOT code from the SCC if it was generated from a different JVM version.

**Comment by pshipton** [comment]
> I'd say that when changing JVM versions, it is probably good practice to delete the SCC

Note that this occurs automatically, when possible. On Windows it's not possible when a JVM is holding the cache open, as this prevents the cache file from being deleted.

**Comment by jcompagner** [comment]
that should go automatically and if it can't delete it for some reasons it should not start using the old cache! it should then just don't use anything at all.. 
i have on purpose: -Xshareclasses:nonfatal
so if something is not correct always start but then without the shared class cache.

To me it looks weird if something goes wrong in reuse (let it be delete, or what ever) that then the vm starts using the wrong/old stuff.. Just start without using a cache at all..

**Comment by pshipton** [comment]
Yes, there is a bug, it shouldn't be crashing. Once we track it down it will be resolved to no longer crash.

**Comment by jcompagner** [comment]
ok deleting the cache myself does start it up.
The first time i tested this again it was still locked because i use the same stuff also for my own Eclipse.
So i couldn't delete it myself also, but even when i released the lock and i started it again it still crashes didn't update the file.

If i then manually delete the file and then start 0.18 it worked.
If i then switched back to 0.17 i did see the file updated (the time stamp did change)
If i then switched back to 0.18 it does work!  (i see the file updated)

Now i can't seem to be able to crash 0.18....
Even when i do create the cache with a 0.16 (my normal eclipse) 
What ever i try now create with .16 (make sure it it is locked) then start .18 or .17 then .18 it all works now.
So i wonder now what my initial state was, and why i can't get to that anymore..

**Comment by jcompagner** [comment]
ah can reproduce it if i restore my original file (the cache that was created 18-11-2019)
then if i make sure that file is locked the 0.18 crashes.
But if i let my 0.16 generated a new file then it works so it is something with my old file from last year
i zipped that:

http://download.servoy.com/C290M13F1A64P_sharedcc_jcomp_G41L00.7z

Wouldn't it be better if that name of the shared cache would have the version of openj9 vm in it?
If people are using older version through each other for some reasons (that can happen easily for our clients that has multiply copies of our product version installed and we ship the vm within our product)

I guess the problem is then when to delete the old files...
