### ISSUE TITLE
Support reusing successful builds when re-triggering Jenkins PR tests

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#8518]
Not sure if this is feasible, perhaps someone with infrastructure expertise can chime in. Would it be possible for `Jenkins test *`  build triggers to reuse an existing successful build if test failures due to infrastructure occur? I find that most of the time for example the `Test_openjdk8_j9_sanity.functional*` type jobs are the ones which fail with various connection issues and when you re-launch the test via the Jenkins trigger it will rebuild the entire JVM again.

This causes a delay in the testing and unnecessarily wastes machine resources. If the `Jenkins test *` trigger were to be improved to check for existing successful builds based off the same SHA from a previous run we could skip the build entirely and go right to testing the JVM.

This would save both machine time and cut down the amount of time a PR is in "waiting to be merged pending successful test" phase.

**Comment by fjeremic** [comment]
@AdamBrousseau @pshipton thoughts?

**Comment by pshipton** [comment]
Restarting failed (red status) testing is already supported. You need to open the parent job of the test and there will be "restart" or "abort" link that you can use if you are logged in.

**Comment by fjeremic** [comment]
> Restarting failed (red status) testing is already supported. You need to open the parent job of the test and there will be "restart" or "abort" links that you can use if you are logged in.

Will the PR status update accordingly?

**Comment by pshipton** [comment]
> Will the PR status update accordingly?

Yup

**Comment by AdamBrousseau** [comment]
Red failure will produce a PR "X", restart will change it back to yellow "in progress".

We've thought of this before. Nobody has taken the time to do it.
See #2316 and #2859 
I think what Pete has mentioned mostly solves your concern, although it takes some active monitoring because it will eventually time out and abort.

The hard part about the SHAs is you start to make decisions which may cause unexpected behaviour. The sha we actually build is the merge sha which changes every time the head of the repo changes. We could look at the sha of the PR instead. If the repo is broken, gets fixed, a PR hasn't changed, how do we know we should be recompiling rather than reusing. Could introduce separate trigger commands depending on if the user wants to rebuild or just retest. This is more committer education and complicates the story. Not sure what the best solution is.
