### ISSUE TITLE
Semantics of TR::allocationFence opcode

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/openj9#8574]
I'm trying to understand the semantics of the`TR::allocationFence` IL opcode in the JIT. I think it's emitted right after allocations and code generators that don't need the memory fence can ignore it but I don't quite understand what it does.

Can someone shed some light on this? :slightly_smiling_face: 
@andrewcraik @cathyzhyi @fjeremic @0xdaryl

**Comment by fjeremic** [comment]
I believe it has to do with the memory model of the target architecture. IIRC the only platform where we emit something would be Power. @zl-wang or @ymanton may be most knowledgeable in that area.

**Comment by zl-wang** [comment]
yes, it has to do with POWER's weakly-consistent memory concerning object header's safety (otherwise, JVM can crash).  Java Memory Model even didn't talk about this explicitly, but it obviously assumed that JVM is safe to run.  As an example,

>      obj1.field = new MyClass(); 

There are at least two groups of memory stores here (new object header initialization vs. the store to obj1.field).  Without the allocationFence, POWER hardware can reorder the two groups of store observing from a third party (say, another thread reading obj1.field).  Now, that third party can crash due to garbages in new object header.

**Comment by Leonardo2718** [comment]
Alright, I think my question has been answered so I am going to close this now.
