### ISSUE TITLE
Get Test_AccessController:test_doPrivileged tests running at least for Java 8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#858]
The following tests are excluded for both Java 8 & 9 without any explanation. For starters, they need to be evaluated for Java 8 to determine why they are failing, and then fixed. Once Java 8 is fixed we can determine the proper action for Java 9.

- org.openj9.test.java.security.Test_AccessController:test_doPrivilegedWithCombiner4
- org.openj9.test.java.security.Test_AccessController:test_doPrivileged_createAccessControlContext

**Comment by pdbain-ibm** [comment]
I'll take this.

**Comment by pdbain-ibm** [comment]
Several issues:
1) Test creates some custom URLClassLoaders, which are unable to load framework classes such as the logger classes.  We fix this by checking the package name in the classloader and using the system classloader for framework classes.

2) Certain tests, particularly test_doPrivileged_createAccessControlContext() run fine when the test
is run standalone by adding a main() method but fail when run under TestNG.  I believe that this may be due to reflection by TestNG.

**Comment by pdbain-ibm** [comment]
We get a NoClassDefFound on AppNoCreateACCPriv$1, a PrivilegedAction internal class.
In fact, loading any inner class in AppNoCreateACCPriv throws a NCDF exception.
Test also fails with Oracle JDK and Java 8: not a regression.

**Comment by pdbain-ibm** [comment]
1) NCDF caused by a security exception when TestNG tries to write to the log file.  Updating the policy file.
2) Custom classloaders fail to load classes in the test framework: update them to handle those packages specially.

**Comment by pdbain-ibm** [comment]
Pull request https://github.com/eclipse/openj9/pull/1076 opened.
Depends on other forthcoming changes before merging.
