### ISSUE TITLE
Increased CPU utilization with JITServer since 0.18.1

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8699]
Comparing SDKs from February 2020 to 0.18.1 SDK I observed a 10% increase in CPU consumed by the client. This is typically caused by an increase in the number of messages exchanged between client and server, but in this cause I don't see a clear increase (344K vs 341K).
Looking at the categories that have increased in recent SDKs I see 4.7K messages of type `ResolvedMethod_definingClassFromCPFieldRef` (this is a new message due to some new code in the optimizer) and 13K messages of type `ResolvedMethod_getRemoteROMClassAndMethods` (jumping from 2.7K).

**Comment by mpirvu** [comment]
I instrumented the code to see where `ResolvedMethod_getRemoteROMClassAndMethods` messages come from and found this piece of code which could be optimized:
```
#ifdef J9_PROJECT_SPECIFIC
static int numConcreteClasses (List<TR_PersistentClassInfo>* subClasses)
  {

  TR::Compilation* comp = TR::comp();
  int count = 0;
  ListIterator<TR_PersistentClassInfo> i(subClasses);
  for (TR_PersistentClassInfo *ptClassInfo = i.getFirst(); ptClassInfo; ptClassInfo = i.getNext())
    {
    TR_OpaqueClassBlock* clazz = ptClassInfo->getClassId();
    if  (!TR::Compiler->cls.isInterfaceClass(comp, clazz) && !TR::Compiler->cls.isAbstractClass(comp, clazz))
      {
      count++;
      }
    }

  return count ;
  }
#endif
```
The routine in question takes a list of subclasses for a particular class and for each subclass tests whether that subclass is an interface or an abstract class. The JITServer is forced to fetch each such subclass in order to perform the queries.
`numConcreteClasses` is actually used in only one place like this
`     if (searchSucceeded && numConcreteClasses(&subClasses) < 2 && rvm)`
so we only want to know if the number of concrete classes in the given hierarchy is smaller than 2 or not. 


To reduce the number of messages between client and server one of the following optimizations can be performed:
1) JITServer sends the entire list of subclasses to the client which packs all those subclasses and sends them in a single message to the JITServer. This technique reduces the number of messages, but does not reduce the overhead of packing a class, nor does it reduce network bandwidth. One disadvantage is that we may transmit information about some classes that are already cached locally. Thus, it may be better to prune the list of classes sent by JITServer to the client
2) Stop counting as soon as two concrete classes are found. The efficiency of this method depends on soon we find those concrete classes. In some cases we may have to scan the entire list. Nevertheless, there is a clear improvement over what we have today.
3) Scan the list of subclasses for any classes that are cached locally at the JITServer. We may be able to find 2 concrete classes and then no message needs to be sent. This approach builds on top of (2).

**Comment by mpirvu** [comment]
@chrisc66 Could you please work on this item and implement solution (3) and (2) as described above? Thanks

**Comment by chrisc66** [comment]
Thanks, I will look into this issue.

**Comment by chrisc66** [comment]
Looks like this is a OMR code, a pull request will be opened to OMR repo once finished. 

There is only one reference of `numConcreteClasses` function at `if (searchSucceeded && numConcreteClasses(&subClasses) < 2 && rvm)`. I am going to modify this function directly as suggested in (2), so that it returns true once two concrete classes are found. 

Looking into (3), we want JITServer to scan the list of subclasses cached locally. If there are already two concrete classes, message to client is not needed anymore. 

From my understanding, JITServer send a message `ResolvedMethod_getRemoteROMClassAndMethods` to query return value of `JITServerHelpers::packRemoteROMClassInfo` from client. When client executes this function, OMR code is executed, including `numConcreteClasses`.  

I haven't found a good location to let JITServer to scan locally cached subclasses before sending a message. Any suggestion where this logic (3) should go? @mpirvu

**Comment by mpirvu** [comment]
You create a frontend query from `numConcreteClasses()`, something called `noMultipleConcreteClasses(classList)` and override that at the server
