### ISSUE TITLE
JDK8 JITServer : ClassLoadingTest_special_12_FAILED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8707]
Failure link
------------

From an internal build `Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/24`:
```
00:23:01  openjdk version "11.0.7-internal" 2020-04-14
00:23:01  OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxjitNightly)
00:23:01  Eclipse OpenJ9 VM (build ibm_sdk-ff26ace9d6, JRE 11 Linux amd64-64-Bit Compressed References 20200229_4 (JIT enabled, AOT enabled)
00:23:01  OpenJ9   - ff26ace9d6
00:23:01  OMR      - c93afcc6b
00:23:01  JCL      - e0e94184e0b based on jdk-11.0.7+5)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
CLT Loaded Class: java.lang.StringIndexOutOfBoundsException
CLT Test failed:
CLT java.lang.NullPointerException
CLT 	at java.base/java.util.HashMap.get(HashMap.java:552)
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.addClass(ClassMapHog.java:219)
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:119)
CLT 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
CLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
CLT 	at java.base/java.lang.Thread.run(Thread.java:834)
CLT <<<
CLT 
CLT 21:25:55.661 - Test failed. Details recorded in execution log.
CLT 21:26:02.115 - Test failed. Details recorded in execution log.
CLT 21:26:03.219 - Test failed. Details recorded in execution log.
CLT stderr Unhandled exception
CLT stderr Type=Segmentation error vmState=0x00000000
CLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000080
CLT stderr Handler1=00007F44702460F0 Handler2=00007F446B9837C0 InaccessibleAddress=0000000000000000
CLT stderr RDI=00007F4415A213F8 RSI=00000000019763B0 RAX=0000000000000170 RBX=00000000018D6C00
CLT stderr RCX=006100760061006A RDX=006100760061006A R8=0000000000000000 R9=0000000000000000
CLT stderr R10=00007F446915DCF0 R11=FFFFFFFFFFFFFFFF R12=0000000001927C88 R13=0000000001976760
CLT stderr R14=00007F4415A214C4 R15=00007F4414A56750
CLT stderr RIP=00007F44701CE472 GS=0000 FS=0000 RSP=00007F4414A563D0
CLT stderr EFlags=0000000000010206 CS=0033 RBP=00007F44702F7F04 ERR=0000000000000000
CLT stderr TRAPNO=000000000000000D OLDMASK=0000000000000000 CR2=000000200148D210
CLT stderr xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
CLT stderr xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
CLT stderr xmm2 00007f4414a56780 (f: 346384256.000000, d: 6.913479e-310)
CLT stderr xmm3 0061006a00200067 (f: 2097255.000000, d: 7.565971e-307)
CLT stderr xmm4 0042002e006c0071 (f: 7078001.000000, d: 2.002645e-307)
CLT stderr xmm5 0061006400700055 (f: 7340117.000000, d: 7.565930e-307)
CLT stderr xmm6 0074007000650063 (f: 6619235.000000, d: 1.780211e-306)
CLT stderr xmm7 0069007200650073 (f: 6619251.000000, d: 1.112614e-306)
CLT stderr xmm8 0074006100740073 (f: 7602291.000000, d: 1.780191e-306)
CLT stderr xmm9 006c0061006e0069 (f: 7209065.000000, d: 1.246107e-306)
CLT stderr xmm10 0061006a00200067 (f: 2097255.000000, d: 7.565971e-307)
CLT stderr xmm11 0042002e006c0071 (f: 7078001.000000, d: 2.002645e-307)
CLT stderr xmm12 0061006400700055 (f: 7340117.000000, d: 7.565930e-307)
CLT stderr xmm13 0074007000650063 (f: 6619235.000000, d: 1.780211e-306)
CLT stderr xmm14 0069007200650073 (f: 6619251.000000, d: 1.112614e-306)
CLT stderr xmm15 006f006900730072 (f: 7536754.000000, d: 1.379617e-306)
CLT stderr Module=/home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
CLT stderr Module_base_address=00007F44701B3000
CLT stderr Target=2_90_20200229_4 (Linux 4.4.0-174-generic)
CLT stderr CPU=amd64 (4 logical CPUs) (0xf6f3a000 RAM)
CLT stderr ----------- Stack Backtrace -----------
CLT stderr (0x00007F44701CE472 [libj9vm29.so+0x1b472])
CLT stderr (0x00007F44701C5B30 [libj9vm29.so+0x12b30])
CLT stderr (0x00007F4470281852 [libj9vm29.so+0xce852])
CLT stderr ---------------------------------------
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
00:47:49  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system/otherLoadTest&PLATFORM=x86-64_linux&TARGET=ClassLoadingTest_special_12

**Comment by pshipton** [comment]
@mpirvu

**Comment by a7ehuo** [comment]
I'll take a look at this one. It still happens with the latest internal build `Test_openjdk8_j9_special.system_x86-64_linux_jit_Nightly/42`.

**Comment by a7ehuo** [comment]
Reproduced the NPE with `-Xjit:optLevel=noOpt`. Compared the compilation logs from the jitserver and non-jitserver on `java/util/HashMap.getNode(ILjava/lang/Object;)Ljava/util/HashMap$Node` for `line:578`. Haven't found any difference. 

```
CLT Test failed:
CLT java.lang.NullPointerException
CLT     at java.util.HashMap.getNode(HashMap.java:578)
CLT     at java.util.HashMap.get(HashMap.java:557)
CLT     at net.adoptopenjdk.test.classloading.ClassMapHog.addClass(ClassMapHog.java:221)
CLT     at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:119)
CLT     at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
CLT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT     at java.lang.reflect.Method.invoke(Method.java:498)
CLT     at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:113)
CLT     at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
CLT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
CLT     at java.lang.Thread.run(Thread.java:821)
CLT <<<
```

**Comment by a7ehuo** [comment]
Many thanks to the suggestion from @ymanton and @mpirvu, the difference between jitserver and non-jitserver is narrowed down with method `java/util/HashMap.resize()[Ljava/util/HashMap$Node;` `-Xjit:noOpt,disableAllocationInlining`, to when it writes barrier info in `Performing Instruction Selection`. 
```
jitserver
------------------------------
 | Write barrier info:
 |   GC mode = 7:RealTime
 |   Node = awrtbari 0x7fc4c928dcc0  sourceObject = 0x7fc4c9293210
 |   Action flags: dirtyCardTableOutOfLine
------------------------------
```
```
non-jitserver
------------------------------
 | Real Time Write barrier info:
 |   GC mode = 7:RealTime
 |   Node = awrtbari 0x7fe30ed97cc0  sourceObject = 0x7fe30ed9d210
 |   Action flags: doInternalControlFlow
------------------------------
```

non-jitserver calls `J9::X86::TreeEvaluator::VMwrtbarRealTimeWithoutStoreEvaluator()` and jitserver calls `J9::X86::TreeEvaluator::VMwrtbarWithoutStoreEvaluator()`.  It means jitserver calls `setRealTimeGC(true)` and non-jitserver calls `setRealTimeGC(true)` in `J9::Options::fePreProcess()`. Since the configuration is global, jitserver doesn't get the update VM configuration from the client as per compilation.

https://github.com/eclipse/openj9/blob/c209fa52b9fe2ac81846d6fbff7f3a8b2452526a/runtime/compiler/control/J9Options.cpp#L1251-L1257

Since the `ClassLoadingTest_special_12` runs with `-Xgcpolicy:metronome`,  starting the jitserver with `-Xgcpolicy:metronome` will make the issue go away. The test passes. Next we'll need to look at set up these VM configurations as per compilation or per client at the server.

**Comment by mpirvu** [comment]
We can either make `TR::Options::_realTimeGC` a non-static field and change `TR::Options::getCmdLineOptions()->realTimeGC()` to comp->getOptions()->realTimeGC() or just introduce a limitation: JITServer does not support RealTime mode (if RealTime mode, then never issue requests remotely).
If it's not too much work, the first approach is preferable.

**Comment by a7ehuo** [comment]
I'll look into the implementation of the first approach.

**Comment by a7ehuo** [comment]
For solution one, a few files as below in OpenJ9 need to be updated to use `comp->getOptions()->realTimeGC()`. OMR code already accesses `_realTimeGC` through the Compilation object options. 

```
	modified:   arm/codegen/J9ARMEvaluator.cpp
	modified:   arm/codegen/J9TreeEvaluator.cpp
	modified:   control/CompilationThread.cpp
	modified:   control/HookedByTheJit.cpp
	modified:   control/J9Options.cpp
	modified:   control/J9Options.hpp
	modified:   env/J9VMEnv.cpp
	modified:   env/VMJ9.cpp
	modified:   p/codegen/J9PPCSnippet.cpp
	modified:   p/codegen/J9TreeEvaluator.cpp
	modified:   x/codegen/AllocPrefetchSnippet.cpp
	modified:   x/codegen/J9TreeEvaluator.cpp
	modified:   z/codegen/J9TreeEvaluator.cpp
```

However, `Options::_realTimeGC` might still need to be kept as `static` due to the usage of it in the following files when the Compilation object doesn’t exist. 

Meanwhile during my test, I'm seeing `realTimeGC` is `1` in packOptions() at the client, but it becomes `0` in `unpackOptions()` at the server. Still debugging this weird issue. 

*  `jitReleaseCodeStackWalk()` - Don't think it would cause an issue at the server 
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/HookedByTheJit.cpp#L6809
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/HookedByTheJit.cpp#L6821
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/HookedByTheJit.cpp#L6887
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/HookedByTheJit.cpp#L6907

* `jitHookReleaseCodeGCCycleEnd()` - Don't think it would cause an issue at the server 
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/HookedByTheJit.cpp#L6934

* `setUpHooks()` - Not sure if it'd be an issue at the server
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/HookedByTheJit.cpp#L7144

* `CompilationInfo::startCompilationThread()` - Compilation object doesn’t exist yet. Might not be an issue for the compilation at the server.
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/CompilationThread.cpp#L2840

* `CompilationInfoPerThread::processEntry()` - Executed at the client and shouldn’t be an issue. 
https://github.com/eclipse/openj9/blob/633f659b6322460478bcd0af5c0b8c7206a9a720/runtime/compiler/control/CompilationThread.cpp#L4156

**Comment by mpirvu** [comment]
`TR::Options::getCmdLineOptions()` resolves to the `global` options object so we can still make _realTimeGC field as non-static

**Comment by mpirvu** [comment]
Note that we can safely use `TR::Options::getCmdLineOptions()` in all places that are not used by JITServer (most code in HookedByTheJIT.cpp, rossa.cpp etc)

**Comment by mpirvu** [comment]
I checked the places in CompilationThread.cpp and HookedByTheJIT.cpp and we should be fine
