### ISSUE TITLE
PR builds don't support aarch64_linux

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#8797]
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md lists 'Linux on aarch64' `aarch64_linux` with short name `alinux64`, but only the short name is recognized.

**Comment by keithc-ca** [comment]
FYI @AdamBrousseau

**Comment by AdamBrousseau** [comment]
PR builds only accept the shortnames. Unless I'm not following, this is expected.

**Comment by keithc-ca** [comment]
I missed this before:
```
<platform> is one of the platform shorthands above
```
('short names' would be more consistent than 'shorthand')

What is the motivation for this restriction?

**Comment by AdamBrousseau** [comment]
I'm fine with rewording that line from `shorthands` to `short names`.
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy#L109-L136
The short names are provided for developer convenience so they don't have to type out the entire spec name. If we were to accept both versions, the way the code is written, we'd have to essentially double the amount of cases in that variable. We could probably come up with some kind of check to know if the value was short or not and convert only if necessary. Not sure what the priority would be on an item like that though. That being said, I wouldn't mind modifying the story a bit since only the PR builds use the shortnames and all other builds use the full names.

**Comment by keithc-ca** [comment]
Where is the code that would need to change if we decided to support both kinds of names?

**Comment by AdamBrousseau** [comment]
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions.groovy#L749
This code translates short spec names into full spec names.

**Comment by keithc-ca** [comment]
That doesn't seem relevant to this issue: What would change in order to support use of long names?

**Comment by AdamBrousseau** [comment]
L752 queries the hashmap for the full spec name (longPlatform)
```
def longPlatform = SHORT_NAMES["${shortName}"]
```
