### ISSUE TITLE
Accelerate Float.floatToIntBits on Z

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#890]
It has been reported that `Float.floatToIntBits` API is slow on Z compared to other platforms. A simple unit benchmark exercising this path will be able to show the difference:

```
import java.lang.Float;

public class JavaFloats {

   public static void main(String[] args) {

      float[] fbuf = {65.56f,66.89f,67.98f,68.82f,69.55f,70.37f,65.56f,66.89f,67.98f};

      int[] ibuf = new int[9];

      try {
        Thread.sleep(10000);
      }
      catch(Exception e) {
      }

      for (int x = 0; x < 200000000; x++) {

         for (int z = 0; z < fbuf.length; z++) {
            ibuf[z] = Float.floatToIntBits(fbuf[z]);
         }

         for (int y = 0; y < ibuf.length; y++) {
            float output = Float.intBitsToFloat(ibuf[y]);
         }
      }
   }
}
```

Digging into this it seems (credits to @joransiu) it appears that we don't fast path some of these APIs on Z. Namely the codegen query `getSupportsInliningOfTypeCoersionMethods` returns false on the Z codegen. There is no reason why we shouldn't enable this.

The above unit benchmark will effectively exercise JNI overhead as `Float.intBitsToFloat` boils down to a native call [3].

The task here is two fold:

1. Enable support for inlining of type coersion methods on the Z codegen
2. Validate all evaluators which get enabled as a result for performance

We need to be careful for the second task here. To give an example the following is the evaluator for `TR::fbits2i` IL which `Float.floatToIntBits` will map to:

https://github.com/eclipse/omr/blob/47bb8f39668c04505c651e54ef49c792441e1392/compiler/z/codegen/FPTreeEvaluator.cpp#L1201-L1288

This evaluator stores the floating point to a temp memory slot and then loads the integer from there. There is also a path with uses `LDGR` which is what we should really use. The alternative path is for architectures below z9. Our current ALS in OMR is set to z9 so this evaluator needs to be simplified to a simple `LDGR` instruction. Other evaluators need to be checked similarly which are enabled by the `getSupportsInliningOfTypeCoersionMethods` guard.

[1] https://github.com/eclipse/openj9/blob/26f8c7edb1fe37253d001243c0ce14473334d07f/runtime/compiler/trj9/env/VMJ9.cpp#L7897-L7903
[2] https://github.com/eclipse/openj9/search?utf8=%E2%9C%93&q=setSupportsInliningOfTypeCoersionMethods&type=
[3] https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/00e69f903e2ca179e999c27b3cfbe4cb536d8e72/jdk/src/share/classes/java/lang/Float.java#L789

**Comment by fjeremic** [comment]
@sehirst could you please take a look at this one?

**Comment by mphunt** [comment]
Hi all, is there any news on when this might be done and included in a release? Thanks!

**Comment by mstoodle** [comment]
@fjeremic @sehirst any timelines you can predict?

**Comment by sehirst** [comment]
I'm working on it. Our upcoming release for Java 8 is SR5 FP10 which should be out sometime this month, so it won't make that. The following one is in March and it's possible we'll make that but I think it will probably end up in the April release. I don't have version numbers for March and April yet. I'll update here again.

**Comment by sehirst** [comment]
I'm working on this now and will make an update when I'm getting close to opening a Pull Request.

**Comment by sehirst** [comment]
The opt is actually enabled on z. Unlike the other platforms, it's enabled in omr:
`self()->setSupportsInliningOfTypeCoersionMethods();`
(https://github.com/eclipse/omr/blob/f698070a815a92a8f1da548b6de042ef73bcd9e7/compiler/z/codegen/OMRCodeGenerator.cpp#L788)

I used fjeremic's `JavaFloats` and collected a tracelog to confirm that the opt actually runs. This means if there's a performance gap it's at the codegen level and how we implement this on z vs other platforms.

A quick comparison of what happens on x86 vs z shows a big difference in what code is generated for the `fbits2i` node. On z we have
``` [     0x3ffdb34b000]   RISBGN  GPR_0295,GPR_0290,30,189,2      
 [     0x3ffdb34b110]   LE      FPR_0293, Shadow[<array-shadow>] 8(GPR_0295,&GPR_0289)
 [     0x3ffdb34b4c0]   TCEB    FPR_0293,3f
 [     0x3ffdb34b5b0]   BRC     VGNOP(0x8), Label L0099         # (Start of internal control flow) 
 [     0x3ffdb34bcd0]   TCEB    FPR_0293,f
 [     0x3ffdb34bdc0]   BRC     VGNOP(0x8), Label L0096 
 [     0x3ffdb34bec0]   BRC     NOP(0xf), Label L0099   
 [     0x3ffdb34bfc0]   Label L0096:    
 [     0x3ffdb34c0c0]   TCEB    FPR_0293,10
 [     0x3ffdb34c1b0]   BRC     VGNOP(0x8), Label L0098 
 [     0x3ffdb34c2b0]   Label L0097:    
 [     0x3ffdb34c3b0]   LE      FPR_0293,#697 =X(ffffffffff800000) 0(GPR_0291)
 [     0x3ffdb34c4a0]   BRC     NOP(0xf), Label L0099   
 [     0x3ffdb34c5a0]   Label L0098:    
 [     0x3ffdb34c6a0]   LE      FPR_0293,#697 =X(7f800000) 0(GPR_0291)
 [     0x3ffdb34c9d0]   ASSOCREGS
 [     0x3ffdb34c790]   Label L0099:    # (End of internal control flow)      
 POST: 
 {AssignAny:GPR_0291:R} {AssignAny:FPR_0293:R}
 [     0x3ffdb34cab0]   STE     FPR_0293, Auto[<auto slot -1>] ?+0(GPR5)
 [     0x3ffdb34cc20]   STE     FPR_0293, Auto[<auto slot -1>] ?+0(GPR5)
 [     0x3ffdb34ce10]   L       GPR_0296, Auto[<auto slot -1>] ?+0(GPR5)
```

On x86 we have
```
[0x7f4b953484c0]       mov     GPR_3809, dword ptr [&GPR_3776+4*GPR_3792+0x8]          # L4RegMem, SymRef  unknown field[#787  Shadow +8] [flags 0x80000605 0x0 ]
```

For the same trees:
``` n410n    (  0)  iRegStore GPR6                                                                       [     0x3ffdb076fe0] bci=[1,4,755] rc=0 vc=1098 vn=- li=49 udi=- nc=1
 n407n    (  4)    fbits2i                                                                            [     0x3ffdb076ef0] bci=[1,1,755] rc=4 vc=1098 vn=- li=- udi=- nc=2
 n186n    (  1)      floadi  <array-shadow>[#477  Shadow] [flags 0x80000605 0x0 ]                     [     0x3ffdb0729e0] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=1
 n185n    (  1)        aladd (X>=0 internalPtr sharedMemory )                                         [     0x3ffdb072990] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=2 flg=0x8100
 n804n    (  3)          ==>aRegLoad (in &GPR_0289) (X!=0 SeenRealReference sharedMemory )
 n184n    (  1)          lsub (highWordZero X>=0 cannotOverflow )                                     [     0x3ffdb072940] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=2 flg=0x5100
 n182n    (  1)            lshl (X>=0 cannotOverflow )                                                [     0x3ffdb0728a0] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=2 flg=0x1100
 n181n    (  1)              i2l (highWordZero X>=0 )                                                 [     0x3ffdb072850] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=1 flg=0x4100
 n805n    (  3)                ==>iRegLoad (in GPR_0290) (X>=0 cannotOverflow canBeAssignedToHPR SeenRealReference )
 n180n    (  1)              iconst 2 (Unsigned X!=0 X>=0 )                                           [     0x3ffdb072800] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=0 flg=0x4104
 n183n    (  1)            lconst -8 (X!=0 X<=0 )                                                     [     0x3ffdb0728f0] bci=[-1,92,20] rc=1 vc=1098 vn=- li=- udi=- nc=0 flg=0x204
 n806n    (  3)      ==>aRegLoad (in GPR_0291) (SeenRealReference sharedMemory )
```

**Comment by sehirst** [comment]
Considering x codegen has reduced this to a simple memory to memory operation, we might be doing more work than we need to in the z evaluator. I'm looking into that now.

**Comment by fjeremic** [comment]
> Considering x codegen has reduced this to a simple memory to memory operation, we might be doing more work than we need to in the z evaluator. I'm looking into that now.

It looks like the reference count of node `n186n` is one, meaning that the load has not been evaluated yet. Judging by the fact that x86 generates a single `mov` from memory to register I bet they're recognizing this pattern and not evaluating the load underneath the `fbits2i` but instead simply generating a memory reference and loading from it directly. 

We should do a similar optimization on z, in addition to getting rid of all that INF, NaN, etc. handling that we don't need. AFAIK we should really only need a direct from memory load path, and a path which evaluates the first child and uses an `LGDR` type instruction.

**Comment by fjeremic** [comment]
@dchopra001 has been actively investigating this issue. @dchopra001 can you please provide an update on your latest findings if possible?

**Comment by dchopra001** [comment]
I have a patch here that mimics the x86 evaluator's behaviour : https://github.com/dchopra001/omr/commit/1ea30f3aa7561df2c99ab667db565788414857b8

We can do a bit more cleanup and reorganization of this evaluator. For example, we generate the exact same STE instruction twice for no good reason (Note: tempMR and tempMR1 are equivalent):
https://github.com/eclipse/omr/blob/884959f423d0e969ffec7340b695e4ed13daabf3/compiler/z/codegen/FPTreeEvaluator.cpp#L1257-L1271

We also don't need any of the branch instructions to normalize NaN values unless the node's `normalizeNaN` property is set (as in the x86 evaluator).

However I'm not able to reproduce the original performance difference observed between Z and x86. @mphunt If you are aware of the Intel CPU Architecture and versions of OpenJDK 1.7 and IBMJava 8 that the benchmark was run on, then can you please let me know? It should help in trying to reproduce the problem accurately.

**Comment by mphunt** [comment]
See below, it's a bit of a mishmash of java versions and hardware, but shows the kind of difference I've seen.

**Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz**
**java version "1.7.0_171"**
OpenJDK Runtime Environment (rhel-2.6.13.0.el6_9-x86_64 u171-b01)
OpenJDK 64-Bit Server VM (build 24.171-b01, mixed mode)
time java Demo2

real    0m2.863s
**user    0m2.775s**
sys     0m0.014s


**IBM z13**
**java version "1.8.0"**
Java(TM) SE Runtime Environment (build pxz6480sr4fp5-20170421_01(SR4 FP5))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux s390x-64 Compressed References 20170419_344392 (JIT enabled, AOT enabled)
J9VM - R28_20170419_1004_B344392
JIT  - tr.r14.java_20170419_344392
GC   - R28_20170419_1004_B344392_CMPRSS
J9CL - 20170419_344392)
JCL - 20170420_01 based on Oracle jdk8u131-b11
time java Demo2

real    0m8.511s
**user    0m8.055s**
sys     0m0.036s


**Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz**
**java version "1.7.0"**
Java(TM) SE Runtime Environment (build pxa6470sr9fp20-20151106_01(SR9 FP20))
IBM J9 VM (build 2.6, JRE 1.7.0 Linux amd64-64 Compressed References 20151019_272770 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR9_20151019_2234_B272770
JIT  - tr.r11_20151005_102425.01
GC   - R26_Java726_SR9_20151019_2234_B272770_CMPRSS
J9CL - 20151019_272770)
JCL - 20151105_01 based on Oracle jdk7u91-b15
time java Demo2

real    0m5.595s
**user    0m5.392s**
sys     0m0.216s

**Comment by dchopra001** [comment]
**Update:**
To continue this investigation further, I've reproduced this issue on newer builds from AdoptOpenJDK. There was a performance difference between Z and x86 seeing on OpenJ9. However that gap is closed with the patch available in my comment above (https://github.com/eclipse/openj9/issues/890#issuecomment-386389044).

Since there is no longer a difference between the two platforms on OpenJ9, we only need to do a comparison between OpenJDK+Hotspot and OpenJDK+OpenJ9 for further investigation. 

I grabbed a couple of recent JVM builds from https://adoptopenjdk.net. Below is the version information for the two builds:

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse **OpenJ9** VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_01_00-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Below is the data when running the `JavaFloats` benchmark with the following command:
`time taskset -a -c 0,1,2,3 ./java JavaFloats`

![screen shot 2018-07-16 at 7 46 27 am](https://user-images.githubusercontent.com/11260919/42757045-8ea01568-88cc-11e8-8416-cc47b0adf42e.png)

Based on the above data, OpenJ9 is 1.8x slower on average. I tried a couple of experiments based on @andrewcraik's suggestions, and it seems like the biggest culprit here may be startup time, and not the performance of the `FloatToIntBits` API itself. 

As a quick experiment, I extended the time that the benchmark runs for by incrementing the length of the outer `for` loop to 2 billion iterations. The idea behind this is to allow the JIT Compiler more time to optimize the program. This way we are measuring the performance at steady state. The results are below:
![screen shot 2018-07-16 at 8 32 13 am](https://user-images.githubusercontent.com/11260919/42758824-c7892e9a-88d2-11e8-83e2-dbe50c5f8fea.png)

There is a significant improvement here. OpenJ9 is ~1.2x slower now. These numbers are still factoring in the startup time. I suspect the numbers will be better if we avoid the slowdown caused by startup.

I'm running some more experiments and will report back with the results soon.

**Comment by fjeremic** [comment]
> To continue this investigation further, I've reproduced this issue on newer builds from AdoptOpenJDK. There was a performance difference between Z and x86 seeing on OpenJ9. However that gap is closed with the patch available in my comment above (#890 (comment)).

@dchopra001 is this ready for delivery? It seems like a good overall change that we should check in the mean while.

**Comment by dchopra001** [comment]
Below are the data for running the modified benchmark on the same x86 machine as before:

<img width="199" alt="screen shot 2018-07-25 at 10 33 02 pm" src="https://user-images.githubusercontent.com/11260919/43238122-cee0a63e-905a-11e8-8391-5435958dbea9.png">

As we can see above, OpenJ9 performs ~9% better than HotSpot. Based on this, we can conclude that the performance gap we saw earlier was strictly due to startup, and the performance of the `Float` APIs is not an issue. 

 As per my comment here: 
https://github.com/eclipse/openj9/issues/890#issuecomment-386389044, OpenJ9's performance on Z is better than x86 after the patch is implemented. So the next step would be to open up a Pull Request to commit this patch for Z. I'll report back with update Z performance numbers after. We should expect to see at least ~9% improvement in performance.

**Comment by dchopra001** [comment]
I've opened up a WIP Pull Request here: https://github.com/eclipse/omr/pull/2800

**Comment by fjeremic** [comment]
Fixed in https://github.com/eclipse/omr/pull/2800.

**Comment by dchopra001** [comment]
For reference, I'm putting an explanation here on the performance of the API on Z after the changes introduced by #2800.

Results for OpenJ9 on x86 vs. Z:
x86 (Haswell) - 47.499s
z13 - 50.684s
 
There's a gap of ~6.7% on Z observed here. The reason for this is that this API's specifications (https://docs.oracle.com/javase/8/docs/api/java/lang/Float.html#floatToIntBits-float-) require values such as positive infinity, negative infinity, and NaN to be single canonicalized values. These values of course are compliant with how the IEEE-754 standard represents them. Since the x86 architecture mostly follows this standard as well, some of the handling is simplified here. On Z, multiple standards for representing floating point numbers are supported, and so need we to be a little more thorough here. This is the main reason why we are observing this smaller gap between the two platforms now.
