### ISSUE TITLE
Power KVM host cpu problems

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#9061]
@rajdeepsingh1.  We seemed to be having problems with stability with the power hosts at UNB.

Recent changes to that environment have been the addition of an instance for storage (#8425) for @AdamBrousseau and also the addition of 6 * cent7 (#8819) instances for @vsebe.

Last week discussing on the OpenJ9 call, we had decide to postpone completing these tasks because we didn't want to make the host unstable when there was nobody on site.  As I understand via slack discussion that might no longer be the case.  Can you please detail what configuration change(s) you have made on the host and why/if you believe this host is now stable.

Attention: @DanHeidinga @pshipton

**Comment by rajdeepsingh1** [comment]
The `powerkvm1` host was experiencing many failures due to CPU lock ups occurring on this host. The VMs were utilizing many resources (vCPU) once the `cent7-ppcle-*` machines were created, which deemed the host unstable. Any new machine install or clone was failing to run at its full potential.

I was able to remove OMR machines `ub1604-p8-unb-11 to ub1604-p8-unb-15` since they were not getting any jobs. These machines each had 8 vCPU (x5) which were able to give us more resources and stability on our host, alongside CPU to our new `cent-pplce-*` machines. 

Once the machines were removed and `cent7-ppcle-*` machines were powered on, they started experiencing different issues, with sporadic CPU issues still occurring. It seems the host itself started to assigned 8 sockets per machines rather than vCPU. This caused a spike on the host (`powerkvm01`) CPU.

The CPU utilization on both the host and VMs has been normalized after modifying the VMs topology sockets/cores/threads with correct values and adding a code block to their configurations. I've monitored the `powerkvm01` host CPU utilization when `p` machines residing on this host are taking jobs simultaneously and the CPU has been stable, with no spikes in utilization and only compounding to about ~40% of utilization during jobs.

**Comment by DanHeidinga** [comment]
> Last week discussing on the OpenJ9 call, we had decide to postpone completing these tasks because we didn't want to make the host unstable when there was nobody on site.

Today's community call came to the same conclusion - if we lose those machines we can't get through our testing ppcle in a night and would have to remove testing (the xl build maybe?) so better to wait.

We can proceed when we have a way to get someone on site to fix any issues or when we have an alternative place to get machines in case this fails.

**Comment by jdekonin** [comment]
@rajdeepsingh1 do you believe this has been addressed?  Can we close this issue?

**Comment by rajdeepsingh1** [comment]
@jdekonin , yes this has been addressed. Issue can be closed.
