### ISSUE TITLE
Big memory regression with OpenJ9 0.20

### ISSUE THREAD

**Issue by edrevo** [eclipse/openj9#9622]
Java -version output
--------------------

```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Linux amd64-64-Bit Compressed References 20200416_574 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)
```

Summary of problem
------------------

We recently updated to OpenJ9 0.20 in an attempt to avoid https://github.com/eclipse/openj9/issues/9600. We have seen a big increase in memory consumption of our services compared to OpenJ9 0.18.1.

Here's a list of memory consumptions of different services:

| Service | Working set 0.18.1 | Working set 0.20 | % Change     |
|---------|------------------|------------------|--------------|
| A       | 382              | 536              | 40,31413613  |
| B       | 518              | 502              | -3,088803089 |
| C       | 204              | 307              | 50,49019608  |
| D       | 130              | 243              | 86,92307692  |
| E       | 219              | 319              | 45,66210046  |
| F       | 188              | 370              | 96,80851064  |

Full disclosure: given that we are trying to avoid https://github.com/eclipse/openj9/issues/9600, we have changed our JAVA_OPTS a bit.

0.18.1 JAVA_OPTS: `-Xtune:virtualized -Xshareclasses:cacheDir=/jvmcache -Xjit:enableSelfTuningScratchMemoryUsageBeforeCompile`
0.20 JAVA_OPTS: `-Xtune:virtualized -Xshareclasses:cacheDir=/jvmcache,nonfatal,name=openj9-020 -Xnoaot -Xscmx512M -Xjit:enableSelfTuningScratchMemoryUsageBeforeCompile`

Diagnostic files
----------------

I am happy to provide any diagnostic files you need.

**Comment by edrevo** [comment]
As per https://openj9.slack.com/archives/C862YFGL9/p1589892789019900?thread_ts=1589865809.019600&cid=C862YFGL9, this big memory increase might in fact be due to disabling AOT.

I'll try 0.18.1 without AOT and see what happens

**Comment by mpirvu** [comment]
@edrevo 
Hmm, in my experience disabling AOT does not increase the footprint. I am going to guess that this is a transient increase due to the memory needed by the JIT compiler (scratch memory).
Could you please send us some diagnostic files for one of the services that have the biggest discrepancy (D or F)? We would need a javacore and the smaps.
The javacore can be generated by sending "kill -3" to your java process. If in doubt about the location of the javacore, you could add these to the java command line: ` -Xdump:java:events=user,file=someDirectory/javacore.\%pid.\%seq.txt`
For smaps just copy `/proc/JAVAPID/smaps` file.

**Comment by edrevo** [comment]
Ok, here's some more info. I have deployed the same services, with the same JAVA_OPTS (`-Xtune:virtualized -Xshareclasses:cacheDir=/jvmcache,nonfatal,name=<name>
    -Xnoaot -Xscmx512M -Xjit:enableSelfTuningScratchMemoryUsageBeforeCompile`) but with openj9 0.18.1 and 0.20.

Here are some stats after several minutes of inactivity:

| Service | Working set 0.18.1 | Working set 0.20 | 
|---------|------------------|------------------|
| A       | 293              | 379 
| B       | 247 | 342
| C       | 295| 473


I'm attaching the smaps for service C, which has the biggest discrepancy: [smaps.zip](https://github.com/eclipse/openj9/files/4657504/smaps.zip)

For the javadump core, I'll need to change a couple of things in my deployment to be able to get it. I'll get back to you later with the javacore.

Many thanks for looking at this issue!

**Comment by edrevo** [comment]
Sorry for my n00bness, but I can't seem to be able to get the javadump core. Sending a kill -3 signal to the java process doesn't generate the expected file. The only thing I see is a spike in the memory:

![image](https://user-images.githubusercontent.com/1845771/82465813-fb135280-9abf-11ea-928f-28930cd5bc54.png)


My JAVA_OPTS contains `-Xdump:java:events=user,file=/javacore.\%pid.\%seq.txt`. However, no "javacore*" file is being generated anywhere (I expected it to be in the root, but `find / -name javacore*` doesn't find anything either)

**Comment by mpirvu** [comment]
Is it possible that the user the service runs as does not have write permissions to the "/" directory?
Maybe try with `-Xdump:java:events=user,file=/tmp/javacore.\%pid.\%seq.txt`

**Comment by edrevo** [comment]
Process is running as root in my environment. I have tried dumping to /tmp too, but no luck either :(

**Comment by edrevo** [comment]
Apperently core dumps in k8s aren't straightforward. You need SSH access to the machine (which I don't have): https://medium.com/@shuanglu1993/how-to-generate-coredump-for-containers-running-with-k8s-1a3f4a7e75b2

**Comment by mpirvu** [comment]
If you cannot SSH to the machine how did you send "kill -3" and how did you collect the smaps? Sorry, but I have no experience with k8.
I ran an experiment to make sure it works: I launched a Docker container running Liberty app server with openj9 (Java11 0.20) with a command line like:
`docker run -d --rm -m=1G --cpus="4.0" --mount source=sccvolume,target=/output/.classCache -e JAVA_HOME=/opt/ibm/java -p 9090:9090  -e JVM_ARGS="-Xdump:java:events=user,file=/tmp/javacore.\%pid.\%seq.txt" --name openj9 liberty-acmeair:openj9_11`
Found the PID of my java process (outside container), sent signal with "sudo kill -3 4899", logged into the container with `docker exec -it 764a0556fa93 /bin/bash` and inspected the /tmp directory. In there I found  `javacore.1.0001.txt` (that 1 is the PID of the process as seen from inside the container).

If you leave the service idle for a while, does the memory consumption come down? I am asking because the JIT may consume quite a bit of memory while compiling, but after compilations are done, all that memory is released back to the OS.

**Comment by edrevo** [comment]
I can run commands into the containers, but for whatever reason the dumps aren't being created in the container's filesystem (and I can't access the host's filesystem).

I have continued to tweak my JAVA_OPTS to deal with #9600 and with my latest JAVA_OPTS (basically, I have re-enabled AOT: `-Xtune:virtualized -Xshareclasses:cacheDir=/jvmcache,nonfatal,name=core-openj9-020 -Xaot:loadExclude={akka/stream/impl/GraphStageIsland.onIslandReady*} -Xscmx512M -Xjit:enableSelfTuningScratchMemoryUsageBeforeCompile`) I don't see such a big difference between 0.18 and 0.20 anymore.

I'm going to close this issue since I can't give you the necessary dumps at the moment. Thanks for looking into the issue!

**Comment by mpirvu** [comment]
As an FYI, in the upcoming release (0.21) under -Xtune:virtualized we have reduced the maximum scratch memory  space a compilation thread can use from 256M to 16M. This means much smaller memory spikes, but a few expensive compilations may need to be performed at a lower optimization level, degrading long term throughput by a few percentage points. We thought this was a good tradeoff.
