### ISSUE TITLE
MauveMultiThreadLoadTest_special_19_FAILED : NPE at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:106)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9754]
Failure link
------------

From an internal build `Test_openjdk8_j9_special.system_ppc64le_linux_Nightly_mauveLoadTest/29`:
```
22:09:28  openjdk version "1.8.0_262-internal"
22:09:28  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_05_30_21_17-b00)
22:09:28  Eclipse OpenJ9 VM (build ibm_sdk-3986247cbd, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20200530_423 (JIT enabled, AOT enabled)
22:09:28  OpenJ9   - 3986247cbd
22:09:28  OMR      - c9875870b
22:09:28  JCL      - 285e6577719 based on jdk8u262-b04)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
=============================================== 
Running test MauveMultiThreadLoadTest_special_19 ... ===============================================
--

LT  PASS: gnu.testlet.java.beans.PropertyDescriptor.constructorTest2: new PropertyDescriptor() (should fail) (number 0)
LT  Test failed:
LT  java.lang.NullPointerException
LT  	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:106)
LT  	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest2.constructor1Tests(constructorTest2.java:600)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest2.test(constructorTest2.java:700)
LT  	at sun.reflect.GeneratedMethodAccessor964.invoke(Unknown Source)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:823)
LT  <<<

MauveMultiThreadLoadTest_special_19_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
22:46:35  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/mauveLoadTest&PLATFORM=ppc64le_linux&TARGET=MauveMultiThreadLoadTest_special_19

**Comment by pshipton** [comment]
Some on Java 11 as well, although not until Sunday night. The others started on Friday night.

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly/387
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_xl_Nightly/176

**Comment by pshipton** [comment]
```
        this.readMethodName = readMethodName;
        if (readMethodName != null && getReadMethod() == null) {     <--- NPE reported here
```

**Comment by pshipton** [comment]
Tried to reproduce with some grinders, but no success. These run on plinux using the same Friday night JVM as reported in https://github.com/eclipse/openj9/issues/9754#issuecomment-636859678
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Nightly/406/OpenJ9-JDK8-ppc64le_linux-20200530-014508.tar.gz 
https://ci.eclipse.org/openj9/view/Test/job/Grinder/898
https://ci.eclipse.org/openj9/view/Test/job/Grinder/899

**Comment by rpshukla** [comment]
I have been able to reproduce failures on zlinux for MauveSingleThreadLoadTest_OpenJ9_0 and MauveMultiThreadLoadTest_special_13. I will try running the same tests with cfg simplification disabled to see if that is causing the problem.

**Comment by rpshukla** [comment]
Update: the same grinders pass with `-Xjit:disableCFGSimplification` so this seems to be a problem with CFG simplification.

**Comment by rpshukla** [comment]
I suspect that the problem is related to this CFG simplification pattern: https://github.com/eclipse/omr/blob/7d9ec945ed0a87e5898c2e92912db18cac01d7a8/compiler/optimizer/OMRCFGSimplifier.cpp#L645

I'm going to run those grinders again with CFG simplification enabled and the environment variable `TR_disableSimplifyNullToException` set to see if the problem goes away.

**Comment by andrewcraik** [comment]
Given OMR has a commit pending for a similar pattern please post your explanation of why the pattern fails once you have it.

**Comment by rpshukla** [comment]
The grinders pass when `TR_disableSimplifyNullToException` is set. I'm looking into what's going wrong with `OMR::CFGSimplifier::simplifyNullToException`.

**Comment by rpshukla** [comment]
Still trying to figure out what's going wrong with simplifyNullToException. If this needs to be fixed quickly, I have opened a PR to disable this simplification: https://github.com/eclipse/omr/pull/5273

**Comment by rpshukla** [comment]
I've opened PR #9783 to disable CFG simplification in openj9 while I continue to investigate this issue.

**Comment by rpshukla** [comment]
Update: the cause of the NullPointerException seems to be a bug in Monitor Elimination. Monitor Elimination manipulates the catch blocks and exception edges created by this CFG Simplification pattern.

Here, monitor elimination tries to add a new exception edge from the NULLCHK block created by CFG simplification to a new catch block created by monitor elimination:
https://github.com/eclipse/openj9/blob/fc545f28f0aba766cca8f78f37d5e4fb9a2f1f4d/runtime/compiler/optimizer/MonitorElimination.cpp#L4529

Then, monitor elimination removes the old exception edge:
https://github.com/eclipse/openj9/blob/fc545f28f0aba766cca8f78f37d5e4fb9a2f1f4d/runtime/compiler/optimizer/MonitorElimination.cpp#L4541

The problem is that `OMR::CFG::addExceptionEdge` silently fails to add a new exception edge if there is an existing edge that catches the same exceptions:
https://github.com/eclipse/omr/blob/b99d3036d8a20592a04fdcd77bca176e794e326d/compiler/infra/OMRCfg.cpp#L202-L211

This leaves the NULLCHK node created by CFG simplification without any exception edge to a catch block. Thus, when the NULLCHK fails, an uncaught NullPointerException is thrown.

I have opened https://github.com/eclipse/omr/pull/5406 to create a new OMR CFG method which will add an exception edge even when there is an existing one.
