### ISSUE TITLE
System test failures on AIX

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9798]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly/394
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/394
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64_aix_Nightly/892/

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly/382/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly/387/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly/107/

https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_sanity.system_ppc64_aix_Nightly/91
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.system_ppc64_aix_Nightly/92
```
Can't open perl script "/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly/openjdk-tests/TKG/../../jvmtest/system/daaLoadTest/..//stf/stf.core/scripts/stf.pl": A file or directory in the path name does not exist.
```

**Comment by pshipton** [comment]
@Mesbah-Alam can you please take a look.

**Comment by Mesbah-Alam** [comment]
This is due to not running the systemtest.getDependency build manually in openj9 Jenkins after https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/347 was resolved. I ran them on the other 3 Jenkins instances but the openj9 one was missed - my bad. 

The actual failure is : 

```
23:35:58  BUILD FAILED
23:35:58  /home/****/workspace/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
23:35:58  /home/****/workspace/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly/openjdk-tests/system/common.xml:255: The following error occurred while executing this line:
23:35:58  /home/****/workspace/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly/openjdk-tests/system/common.xml:209: The following error occurred while executing this line:
23:35:58  /home/****/workspace/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly/openjdk-tests/system/stf/stf.build/include/top.xml:241: src '/tmp/log4j-2.13.3/apache-log4j-2.13.3-bin.zip' doesn't exist.
```

The job is getting prereqs from https://ci.eclipse.org/openj9/job/systemtest.getDependency/185/ - which doesn't contain the latest log4j jar (as its scheduled run took place before my changes were delivered). 

The [latest](https://ci.eclipse.org/openj9/job/systemtest.getDependency/186/ ) systemtest.getDependency run does contain the latest jars however. 

So, the failures will disappear if the failed jobs were re-run. 

@pshipton

**Comment by pshipton** [comment]
Ok thanks, I did run systemtest.getDependency this morning, so this should be resolved.
