### ISSUE TITLE
Another performance problem of modded Minecraft

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse/openj9#9815]
Java -version output
--------------------
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Windows 7 amd64-64-Bit Compres
sed References 20200422_667 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5e623848e9 based on jdk8u252-b09)
```

Summary of problem
------------------

Sometimes running (fabric modded) modpack on openj9 may lead to longer [tick time](https://minecraft.gamepedia.com/Tick) lower performance compare to hotspot.
Here are screenshots of F3 GUI
(-Xjit:disableGuardedStaticFinalFieldFolding options is not useful)
openj9:
![2020-06-06_21.28.23.png](https://i.loli.net/2020/06/06/bYDSnwuLtQmaXkj.png)
hotspot:
![2020-06-06_20.53.57.png](https://i.loli.net/2020/06/06/tsDEC5nrh7qcgJl.png)

Diagnostic files
----------------

jit log and gc log(zip compress):
[LogVerbose.20200606.205706.zip](https://github.com/eclipse/openj9/files/4740125/LogVerbose.20200606.205706.zip)

[verbosegc.20200606.205706.4140.zip](https://github.com/eclipse/openj9/files/4740123/verbosegc.20200606.205706.4140.zip)

**Comment by andrewcraik** [comment]
This isn't clearly a JIT issue yet - @amicic could you check the verbose gc logs and see if there is a GC issue here before we dig into profiles and code? Once we have that we have a better idea where we need to look.

**Comment by andrewcraik** [comment]
@BeverlyXu can you monitor and help make sure we move this forward like the last one?

**Comment by amicic** [comment]
So, we are comparing 36ms (OpenJ9) vs 26ms (Hotspot) tick time, right?. Is the problem that average is higher or average is mostly equal, but there is stuttering where tick can sharply jump considerably above 50ms threshold? The former is more likely to be JIT issue, while the latter is more likely to be GC issue (or some other low level issue)

We indeed had a couple of long GCs. Worst one is 1.3sec, but not clear why it was so long, since the real work GC did is very comparable to some short other GCs.  I'm showing two GC cycles next to each other one with 1.3sec and the other one much shorter with very similar amount of objects moved (6.5M vs 5M). Noramally this should be done well within 10s of ms.
 There are some other reasons why first GC is so much longer. Could be OS related (paging), could be some other process stealing CPU cycles...

```
<exclusive-start id="6332" timestamp="2020-06-06T21:26:36.567" intervalms="226230.506">
  <response-info timems="48.510" idlems="24.285" threads="1" lastid="0000000002BE6700" lastname="Render thread" />
</exclusive-start>
<af-start id="6333" threadId="0000000005604180" totalBytesRequested="40" timestamp="2020-06-06T21:26:36.737" intervalms="226461.713" type="nursery" />
<cycle-start id="6334" type="scavenge" contextid="0" timestamp="2020-06-06T21:26:36.917" intervalms="226625.721" />
<gc-start id="6335" type="scavenge" contextid="6334" timestamp="2020-06-06T21:26:37.187">
  <mem-info id="6336" free="432409544" total="2546991104" percent="16">
    <mem type="nursery" free="0" total="691798016" percent="0">
      <mem type="allocate" free="0" total="622592000" percent="0" />
      <mem type="survivor" free="0" total="69206016" percent="0" />
    </mem>
    <mem type="tenure" free="432409544" total="1855193088" percent="23">
      <mem type="soa" free="413856712" total="1836640256" percent="22" />
      <mem type="loa" free="18552832" total="18552832" percent="100" />
    </mem>
    <remembered-set count="3878" />
  </mem-info>
</gc-start>
<allocation-stats totalBytes="618232208" >
  <allocated-bytes non-tlh="728" tlh="618231480" />
  <largest-consumer threadName="Server thread" threadId="0000000005603800" bytes="545054256" />
</allocation-stats>
<gc-op id="6337" type="scavenge" timems="542.907" contextid="6334" timestamp="2020-06-06T21:26:37.747">
  <scavenger-info tenureage="14" tenuremask="4000" tiltratio="89" />
  <memory-copied type="nursery" objects="167946" bytes="6343024" bytesdiscarded="81264" />    _<<<< only 6.5M of objects moved_
  <memory-copied type="tenure" objects="5842" bytes="203008" bytesdiscarded="864" />
  <finalization candidates="9" enqueued="9" />
  <ownableSynchronizers candidates="161" cleared="68" />
  <references type="soft" candidates="26" cleared="0" enqueued="0" dynamicThreshold="9" maxThreshold="32" />
  <references type="weak" candidates="93" cleared="9" enqueued="6" />
  <references type="phantom" candidates="545" cleared="460" enqueued="460" />
</gc-op>
<gc-end id="6338" type="scavenge" contextid="6334" durationms="584.025" usertimems="78.001" systemtimems="15.601" timestamp="2020-06-06T21:26:37.777" activeThreads="4">
  <mem-info id="6339" free="1048483264" total="2546991104" percent="41">
    <mem type="nursery" free="616166536" total="691798016" percent="89">
      <mem type="allocate" free="616166536" total="622592000" percent="98" />
      <mem type="survivor" free="0" total="69206016" percent="0" />
    </mem>
    <mem type="tenure" free="432316728" total="1855193088" percent="23" macro-fragmented="0">
      <mem type="soa" free="413763896" total="1836640256" percent="22" />
      <mem type="loa" free="18552832" total="18552832" percent="100" />
    </mem>
    <pending-finalizers system="9" default="0" reference="466" classloader="0" />
    <remembered-set count="2994" />
  </mem-info>
</gc-end>
<cycle-end id="6340" type="scavenge" contextid="6334" timestamp="2020-06-06T21:26:37.787" />
<allocation-satisfied id="6341" threadId="0000000005603800" bytesRequested="40" />
<af-end id="6342" timestamp="2020-06-06T21:26:37.787" threadId="0000000005604180" success="true" from="nursery"/>
<exclusive-end id="6343" timestamp="2020-06-06T21:26:37.787" durationms="1288.905" />    _<<<<<<< very long!!! not clear where is extra 0.7sec that elapsed on top of Scavenge gc-op 0.5sec_

<exclusive-start id="6344" timestamp="2020-06-06T21:27:04.589" intervalms="28094.617">
  <response-info timems="12.983" idlems="6.496" threads="1" lastid="0000000005B2F400" lastname="Server-Worker-89" />
</exclusive-start>
<af-start id="6345" threadId="0000000005604180" totalBytesRequested="64" timestamp="2020-06-06T21:27:04.589" intervalms="27850.986" type="nursery" />
<cycle-start id="6346" type="scavenge" contextid="0" timestamp="2020-06-06T21:27:04.589" intervalms="27686.814" />
<gc-start id="6347" type="scavenge" contextid="6346" timestamp="2020-06-06T21:27:04.589">
  <mem-info id="6348" free="432312112" total="2546991104" percent="16">
    <mem type="nursery" free="0" total="691798016" percent="0">
      <mem type="allocate" free="0" total="622592000" percent="0" />
      <mem type="survivor" free="0" total="69206016" percent="0" />
    </mem>
    <mem type="tenure" free="432312112" total="1855193088" percent="23">
      <mem type="soa" free="413759280" total="1836640256" percent="22" />
      <mem type="loa" free="18552832" total="18552832" percent="100" />
    </mem>
    <remembered-set count="5092" />
  </mem-info>
</gc-start>
<allocation-stats totalBytes="616054032" >
  <allocated-bytes non-tlh="364176" tlh="615689856" />
  <largest-consumer threadName="Server thread" threadId="0000000005603800" bytes="377018440" />
</allocation-stats>
<gc-op id="6349" type="scavenge" timems="27.596" contextid="6346" timestamp="2020-06-06T21:27:04.619">
  <scavenger-info tenureage="14" tenuremask="4000" tiltratio="89" />
  <memory-copied type="nursery" objects="85850" bytes="4767872" bytesdiscarded="164440" />  _<<<<< about 5M objects moved, relatively short 28ms_
  <memory-copied type="tenure" objects="1019" bytes="71304" bytesdiscarded="1208" />
  <finalization candidates="237" enqueued="237" />
  <ownableSynchronizers candidates="106" cleared="16" />
  <references type="soft" candidates="32" cleared="0" enqueued="0" dynamicThreshold="9" maxThreshold="32" />
  <references type="weak" candidates="239" cleared="43" enqueued="22" />
  <references type="phantom" candidates="3647" cleared="3559" enqueued="3559" />
</gc-op>
<gc-end id="6350" type="scavenge" contextid="6346" durationms="28.326" usertimems="62.400" systemtimems="0.000" timestamp="2020-06-06T21:27:04.619" activeThreads="4">
  <mem-info id="6351" free="1049888568" total="2546991104" percent="41">
    <mem type="nursery" free="617658800" total="691798016" percent="89">
      <mem type="allocate" free="617658800" total="622592000" percent="99" />
      <mem type="survivor" free="0" total="69206016" percent="0" />
    </mem>
    <mem type="tenure" free="432229768" total="1855193088" percent="23" macro-fragmented="0">
      <mem type="soa" free="413676936" total="1836640256" percent="22" />
      <mem type="loa" free="18552832" total="18552832" percent="100" />
    </mem>
    <pending-finalizers system="237" default="0" reference="3581" classloader="0" />
    <remembered-set count="4213" />
  </mem-info>
</gc-end>
<cycle-end id="6352" type="scavenge" contextid="6346" timestamp="2020-06-06T21:27:04.669" />
<allocation-satisfied id="6353" threadId="0000000005603800" bytesRequested="64" />
<af-end id="6354" timestamp="2020-06-06T21:27:04.669" threadId="0000000005604180" success="true" from="nursery"/>
<exclusive-end id="6355" timestamp="2020-06-06T21:27:04.669" durationms="75.818" />
```

**Comment by amicic** [comment]
Verbose GC logs from HotSpot would be valuable, to so see if they suffer from those sudden long GCs.

**Comment by dmitripivkine** [comment]
Also `usertimems` (actually utilized by GC) is very close for both GC cycles in example - `"78.001"` vs `"62.400"`. Looks like resources are taken externally

**Comment by 1a2s3d4f1** [comment]
''' -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCDateStamps -Xloggc:gc.log '''  get hotspot gc log
[hotspot-gc-log.zip](https://github.com/eclipse/openj9/files/4750104/hotspot-gc-log.zip)
New openj9 gc and jit log:
screenshots(spark mod can show gc time):

openj9:
![2020-06-09_12.42.44.png](https://i.loli.net/2020/06/09/VzsY2HpqEnR5WZL.png)
hotspot:
![2020-06-09_13.11.20.png](https://i.loli.net/2020/06/09/NywPHovR28C9rZh.png)

**Comment by 1a2s3d4f1** [comment]
Hotspot can use 3000MB physical memory but when openj9 lag ,It was only use 1454MB physical memory

**Comment by amicic** [comment]
I did not realize right away that bottom right corner is showing the timeline of TPS (or delay expressed in ms). Now that I understand it, here are the observations:

In both set of screen shorts it can be seen that average delays are higher for OpenJ9 (32ms vs 24ms for Hotspot), what is far more likely a JIT problem that GC. 

Worst case, which is more likely to be GC problem, in the first set of screen shots was better for OpenJ9 (88ms vs Hotspot 125ms), while in second set better for Hotspot (34ms vs 64ms).

The Tick textual log (left, middle-bottom) reports GC times and it roughly indicates that OpenJ9 performs better. 

Anyhow, I analyzed the provided verbose GC logs, and OpenJ9 GC is indeed somewhat better. Average pause times are 1/2 of Hotspots, and while about 50% more frequnt, overall OpenJ9 still spend less time in  (Stw-The-World) GCs;

  | OpenJ9 | Hotspot
-- | -- | --
Total GC time (sec) | 21.7 | 30.5
Average GC time (ms) | 35 | 72
Num of GCs | 627 | 422
Duration of run (sec) | 1125 | 1248

Worst case pause times are somewhat comparable. I'm showing below all pauses >300ms that are will be likely be observed as a freeze during game-play. While I'm no expert for Hotspot logs, I'd say that cause of those delays (as for OpenJ9 too) is unlikely to be real GC work, but more likely a lower level problem within OS or due to CPU starvation.

Overall, OpenJ9 GC performs well in relative terms (comparing to Hotspot).


Hotspot:
j9build@rhel7x64vm20 /team/amicic $ grep 'Times:.*real=[1-9]' gc.log
 [Times: user=0.28 sys=0.03, **real=2.80 secs**]
j9build@rhel7x64vm20 /team/amicic $ grep 'Times:.*real=0\.[3-9]' gc.log
 [Times: user=2.17 sys=0.13, **real=0.60 secs**]
 [Times: user=1.67 sys=0.00, **real=0.43 secs**]
 [Times: user=0.25 sys=0.00, **real=0.99 secs**]
 [Times: user=0.97 sys=0.00, **real=0.84 secs**]
 [Times: user=0.06 sys=0.00, **real=0.41 secs**]
j9build@rhel7x64vm20 /team/amicic $ grep 'Times:' gc.log |awk -F\= '{x+=$4} END {print x, NR, x/NR}'
30.5 422 0.0722749

OpenJ9:
j9build@rhel7x64vm20 /team/amicic $ grep 'exclusive-end.*durationms=\"[1-9][0-9][0-9][0-9]\.' verbosegc.20200609.122412.4580.txt
<exclusive-end id="6246" timestamp="2020-06-09T12:33:28.315" **durationms="1140.479"** />
j9build@rhel7x64vm20 /team/amicic $ grep 'exclusive-end.*durationms=\"[3-9][0-9][0-9]\.' verbosegc.20200609.122412.4580.txt
<exclusive-end id="632" timestamp="2020-06-09T12:24:29.801" **durationms="441.214"** />
<exclusive-end id="5723" timestamp="2020-06-09T12:30:33.671" **durationms="307.860"** />
<exclusive-end id="5938" timestamp="2020-06-09T12:31:41.020" **durationms="305.826"** />
<exclusive-end id="5951" timestamp="2020-06-09T12:31:44.216" **durationms="399.674"** />
<exclusive-end id="5964" timestamp="2020-06-09T12:31:46.272" **durationms="586.539"** />
<exclusive-end id="5977" timestamp="2020-06-09T12:31:49.020" **durationms="581.695"** />
<exclusive-end id="5989" timestamp="2020-06-09T12:32:00.772" **durationms="490.877"** />
<exclusive-end id="6002" timestamp="2020-06-09T12:32:03.455" **durationms="386.098"** />
<exclusive-end id="6210" timestamp="2020-06-09T12:33:21.929" **durationms="885.861"** />
j9build@rhel7x64vm20 /team/amicic $ grep 'exclusive-end' verbosegc.20200609.122412.4580.txt |awk -F\" '{x+=$6} END {print x, NR, x/NR}'
21732.4 627 34.6609

**Comment by 1a2s3d4f1** [comment]
Use  `-Xshareclasses:none` turn off share class

TICK Time:
avg delays 32->29 
min delays 28->26

**Comment by DanHeidinga** [comment]
Retargeting this to the 0.22.0 release as investigation is still ongoing

**Comment by 1a2s3d4f1** [comment]
Disable share class cache `-Xshareclasses:none`
tick average delays was low 2ms (disable aot was not use)

**Comment by 1a2s3d4f1** [comment]
Try remove ImmersivePortalsMod mod.
Now openj9 vs hotspot
screenshots:
hotspot:
![2020-06-26_12.42.19.png](https://i.loli.net/2020/06/26/omGbyzjfS2vMhFY.png)
openj9:
![2020-06-26_13.06.23.png](https://i.loli.net/2020/06/26/l8fAG6UPCbIayru.png)

ImmersivePortalsMod: (https://github.com/qouteall/ImmersivePortalsMod)
I do not know why remove a mod can fix performance problem.

**Comment by BeverlyXu** [comment]
@1a2s3d4f1 would you please take another GC log with the ImmersivePortals Mod removed? If the GC behavior is similar with and without the mod, then we could look into other possible causes of the delay.

**Comment by 1a2s3d4f1** [comment]
[verbosegc.20200701.003217.3608.zip](https://github.com/eclipse/openj9/files/4855781/verbosegc.20200701.003217.3608.zip)

gc log (not ImmersivePortalsMod mod)

**Comment by BeverlyXu** [comment]
@1a2s3d4f1 This log looks like it's only 2k? Would you be able to get a log similar to what you had before?  ~MB in size.

**Comment by 1a2s3d4f1** [comment]
log file size : 1.40MB
[verbosegc.20200708.125032.5772.zip](https://github.com/eclipse/openj9/files/4888575/verbosegc.20200708.125032.5772.zip)

**Comment by BeverlyXu** [comment]
@amicic would you please take a look at the log without the mod? User has reported that by removing the mod, the performance problem was fixed. If the new gc log shows similar behavior as the one with the mod, then we can go into verbose logs to look at potential JIT problems. Thank you!

**Comment by amicic** [comment]
Various metrics are fairly close to each other. Overall, well behaved GC.

Variant | OpenJ9 mod | OpenJ9 NO mod
-- | -- | --
Concurrent collection count | 26 | 22
Forced collection count | 0 | 0
GC Mode | gencon | gencon
Global collections - Mean garbage collection pause (ms) | 83.3 | 76.0
Global collections - Mean interval between collections  (ms) | 20364 | 21963
Global collections - Number of collections | 29 | 26
Global collections - Total amount tenured (MB) | 8338 | 7408
Largest memory request (bytes) | 10939392 | 67108872
Number of collections triggered by allocation failure | 574 | 429
Nursery collections - Mean garbage collection pause (ms) | 30.8 | 41.3
Nursery collections - Mean interval between collections  (ms) | 1971 | 1760
Nursery collections - Number of collections | 571 | 425
Nursery collections - Total amount flipped (MB) | 5318 | 4694
Nursery collections - Total amount tenured (MB) | 1704 | 1590
Proportion of time spent in garbage collection pauses  (%) | 1.93 | 2.94
Proportion of time spent unpaused (%) | 98.07 | 97.06
Rate of garbage collection (MB/minutes) | 6868 | 6967

**Comment by 1a2s3d4f1** [comment]
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Windows 7 amd64-64-Bit Compres
sed References 20200715_763 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 4fe4692246 based on jdk8u262-b10)
```
Happen in 1.16.1 modded minecraft (no that mod)

Openj9 TPS delays min:17ms   avg:19ms  max:32ms
Hotspot TPS delays min:12ms  avg:15ms  max:28ms

Screenshots:
Hotspot:
![2020-07-18_20.48.40.png](https://i.loli.net/2020/07/18/264PXut5LrnxfpH.png)
openj9:
![2020-07-18_21.07.12.png](https://i.loli.net/2020/07/18/8Bl4Nt9KXuZzcO7.png)

GC log:[verbosegc.20200718.210754.3104.zip](https://github.com/eclipse/openj9/files/4941734/verbosegc.20200718.210754.3104.zip)

JIT log:[LogVerbose.20200718.210755.zip](https://github.com/eclipse/openj9/files/4941733/LogVerbose.20200718.210755.zip)

**Comment by 1a2s3d4f1** [comment]
Game TPS delays:
Openj9: min:14ms  avg:16ms
Hotspot:min:11ms  avg:12ms

JIT log and GC log:
[LogVerbose.20200720.200928.zip](https://github.com/eclipse/openj9/files/4947715/LogVerbose.20200720.200928.zip)
[verbosegc.20200720.200927.7836.zip](https://github.com/eclipse/openj9/files/4947716/verbosegc.20200720.200927.7836.zip)

**Comment by BeverlyXu** [comment]
@1a2s3d4f1 
Looking at the two LogVerbose files from 0720 and 0609, it looks like the two runs are having different settings. Notably,  `shiftAmount` shows different values, and this normally means different heap sizes. There is a chance that the mod itself implicitly sets the heap size. Please double check. 

We would like to have two verbose logs that have the exact same setup, except for the mod being on and off. So we can have an apple to apple comparison. Please also include the TPS numbers with it. Thank you!

**Comment by 1a2s3d4f1** [comment]
@BeverlyXu 
I was get different LogVerbose ,
1.16.1, 29 mods jvm memory:1024mb It is still have  performance problem when not add that mod.

Test game version 1.16.1(add mod version is 1.15.2)
No ImmersivePortalsMod 
Game TPS delays(1.16.1):
Openj9: min 14ms avg 16ms （often avg 17ms）
Hotspot: min 11ms avg 12ms

0720 LogVerbose was 1.16.1 29mods game ,so it is different than 0609.

**Comment by BeverlyXu** [comment]
Hi @1a2s3d4f1, I saw some of your previous comments and our discussion was removed from the thread. Was the problem no longer reproducible? Please let us know how we could further help. Thank you!

**Comment by 1a2s3d4f1** [comment]
Thank your help ,This issue is not happen
