### ISSUE TITLE
Inconsistency with OtherRecompilationTrigger

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#9860]
`j9jit_testarossa_err()` can send an `OtherRecompilationTrigger` event, and it is handled in `TR::DefaultCompilationStrategy::processEvent()`.
When `TR::Recompilation::getJittedBodyInfoFromPC()` returns a NULL, `processEvent()` crashes immediately as it tries to access `bodyInfo->getMethodInfo()`.  On the other hand, `j9jit_testarossa_err()` allows `getJittedBodyInfoFromPC()` to return a NULL when it sends out the event.  There is an inconsistency in handling the NULL between the two functions.

https://github.com/eclipse/openj9/blob/13a2f387f24005170b29e818e52e9415d09f88e2/runtime/compiler/control/rossa.cpp#L321

https://github.com/eclipse/openj9/blob/13a2f387f24005170b29e818e52e9415d09f88e2/runtime/compiler/control/CompilationController.cpp#L1471-L1474

What is the best way to fix this?
- Add a NULL check in `processEvent()`
- Just return from `j9jit_testarossa_err()` without sending the event when `getJittedBodyInfoFromPC()` returns a NULL
- Anything else?

**Comment by knn-k** [comment]
The crash in `processEvent()` happens with AArch64 runtime without support for recompilation as reported in #9574.
I don't know why it tries to send the `OtherRecompilationTrigger` event when recompilation is not supported.

**Comment by knn-k** [comment]
I opened PR #9862 as a fix for this.

**Comment by 0xdaryl** [comment]
@mpirvu : FYI for any opinion you have on the best way to fix this.

**Comment by mpirvu** [comment]
In theory, for a recompilation to take place we must have a jittedBodyInfo for the existing method body. This is the reason why `TR::DefaultCompilationStrategy::processEvent()` does not have a check on  NULL. In fact, in several places in CompilationThread.cpp there are comments like this "// because this is a recompilation, the persistentJittedBodyInfo must exist".

I would like to understand more about this scenario. `TR_MethodEvent::OtherRecompilationTrigger` is used for recompilations triggered from jitted code (EDO or GCR for instance) or if async compilation is disabled. Since recompilations are disabled for AArch64, are you running with asynchronous compilation disabled?

**Comment by 0xdaryl** [comment]
Async compilation is not disabled on AArch64.

**Comment by knn-k** [comment]
I tried to recreate the crash in the debugger to see where `TR::DefaultCompilationStrategy::processEvent()` is called from, but my attempts been unsuccessful.

**Comment by knn-k** [comment]
Recompilation is enabled on AArch64, and this problem will be invisible.

**Comment by knn-k** [comment]
I would like my fix #9862 to be reviewed and merged anyway, because it is obvious that the assumption on potential NULL from `getJittedBodyInfoFromPC()` is different between `j9jit_testarossa_err()` and `processEvent()`.
