### ISSUE TITLE
OpenJ9 cannot build android project

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9871]
See the details in https://github.com/AdoptOpenJDK/openjdk-support/issues/127

Instead of building the user's app, I tried building the default app. While I didn't duplicate the same error, I did get some NullPointerExceptions. I tried again with `-Xshareclasses:none` and got a different NPE. I tried again with `-Xint` and it built successfully.

**Comment by pshipton** [comment]
There are also problems when using 0.21.0-m1 (with JIT). I saw a NullPointerException and then UnsupportedOperationException when I re-tried the build.

**Comment by DanHeidinga** [comment]
There's another Android issue being investigated as well that may be related: https://github.com/eclipse/openj9/issues/8823

**Comment by DanHeidinga** [comment]
Does this problem still occur with the 0.21.0 milestone builds?  I expect the fix for  #8823 should have addressed this as well

The OpenJ9 0.21.0 Milestone 2 builds are available
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u262-b07_openj9-0.21.0-m2
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.8+8_openj9-0.21.0-m2
https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/tag/jdk-14.0.1+7_openj9-0.21.0-m2
