### ISSUE TITLE
JVMSHRC129E Attempt to set readerCount to -1!

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9893]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/394
SharedClasses.SCM01.MultiThreadMultiCL_0
```
MTM5 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM3 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM4 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM1 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM2 stderr JVMSHRC129E Attempt to set readerCount to -1!
```
```
MTM1 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NullPointerException
MTM1 stderr 	at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getCalendarProvider(JRELocaleProviderAdapter.java:349)
MTM1 stderr 	at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getLocaleServiceProvider(JRELocaleProviderAdapter.java:115)
MTM1 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:281)
MTM1 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
MTM1 stderr 	at java.base/java.util.Calendar.createCalendar(Calendar.java:1692)
MTM1 stderr 	at java.base/java.util.Calendar.getInstance(Calendar.java:1629)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.logMessage(LoaderSlaveMultiThreadMultiCL.java:120)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.run(LoaderSlaveMultiThreadMultiCL.java:102)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.main(LoaderSlaveMultiThreadMultiCL.java:59)
MTM1 stderr Caused by: java.lang.NullPointerException
MTM1 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:231)
MTM1 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
MTM1 stderr 	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:969)
MTM1 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
MTM1 stderr 	... 9 more
```

**Comment by pshipton** [comment]
@hangshao0

**Comment by hangshao0** [comment]
A writer trying to lock the cache needs to wait for all readers to finish. The waiting time is controlled by `CACHE_LOCK_PATIENCE_COUNTER`. There are multiple readers now. I guess the current value of `CACHE_LOCK_PATIENCE_COUNTER` might not be big enough.

**Comment by hangshao0** [comment]
I added some debug info and I see we timed out on `CACHE_LOCK_PATIENCE_COUNTER`. After I increase `CACHE_LOCK_PATIENCE_COUNTER`, I am still seeing the time out. I need to figure out why.

`JVMSHRC129E` is also there in the following build:
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/395/, which passed. So this message won't cause the job to fail. 

Build [394 ](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/394)failed due to the `NullPointerException`, which seems to be a different issue from `JVMSHRC129E`.

**Comment by pshipton** [comment]
For the NPE, may be the same issue as https://github.com/eclipse/openj9/issues/8972

**Comment by pshipton** [comment]
I assume JVMSHRC129E isn't in the builds previous to #9811?

**Comment by pshipton** [comment]
I checked a few earlier builds and didn't find JVMSHRC129E.

**Comment by hangshao0** [comment]
> I assume JVMSHRC129E isn't in the builds previous to #9811?

It was not there before this commit.

**Comment by hangshao0** [comment]
The timeout is caused by:

Thread 1: Locking the cache with the write mutex, waiting for readers to finish. (SH_CacheMap::updateROMClassResource)
Thread 2: Holding the class segment mutex, waiting for the write lock. (Storing ROMClass to the SCC)
Thread 3: Entered the read mutex, waiting for the class segment mutex. (SH_CacheMap::findROMClass)

We should not acquire the class segment mutex inside the read mutex. It is caused by the recent change in SH_CacheMap::findROMClass().
