### ISSUE TITLE
org.openj9.test.java.lang.Test_ClassLoader tests are excluded for Java 8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#995]
The org.openj9.test.java.lang.Test_ClassLoader tests (openj9/test/Java8andUp/src_80/org/openj9/test/java/lang/Test_ClassLoader.java) are excluded for Java 8. The tests need to be fixed if necessary to work property on Java 8, and included.

**Comment by pdbain-ibm** [comment]
Per Dan's request, I'll look at this.

**Comment by pdbain-ibm** [comment]
The tests are already running in Java 8 and 9.  Both are passing:
PASSED: test_classloaders
PASSED: test_latestUserDefinedLoader

===============================================
    JCL_TEST_Test-Annotation-ClassLoader
    Tests run: 2, Failures: 0, Skips: 0
===============================================

There is an exclusion in TestConfig/resources/excludes/latest_exclude_SE90.txt, but it doesn't seem to be excluding anything.

**Comment by pdbain-ibm** [comment]
Further to above comment: there are actually TWO "Test_ClassLoader" test classes: one in the org.openj9.test.java.lang package and the second in org.openj9.test.annotationClassLoader.
The latter is running and passing.  The former exists in the OpenJ9 repository but the testng and playlist files are in an internal repo.

Since the test implementation is already open source, I am moving the playlist and testng entries to 
the open source repo.

The test passes when  run manually but fails in personal builds:
```
FAILED: test_getResource
java.lang.AssertionError: Unable to find resource
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from sun.misc.Launcher$AppClassLoader@f4341f65(file:/tmp/bld_378145/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from sun.misc.Launcher$AppClassLoader@f4341f65(file:/tmp/bld_378145/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_ClassLoader.test_getResource(Test_ClassLoader.java:72) from sun.misc.Launcher$AppClassLoader@f4341f65(file:/tmp/bld_378145/openj9/jvmtest/IBM_Internal/Java8andUp_IBM_Internal/GeneralTest.jar)
```

 I'm investigating.

**Comment by pdbain-ibm** [comment]
The IBM_Internal copy of the test fails, but the open-source version works fine.
I will remove the IBM_Internal copy first, then enable the OpenJ9 version.

**Comment by pshipton** [comment]
Do they run the same tests?
